Repository micronaut-projects/micronaut-core, pull requests merged in 2018-06, with the labels that each got.

#326 Add support for non singleton beans
  spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java
  spring/src/main/java/io/micronaut/spring/beans/MicronautSpringBeanFactory.java
  spring/src/test/groovy/io/micronaut/spring/beans/MicronautBeanProcessorSpec.groovy
Labels: type: enhancement

#324 config path add micronaut
  src/main/docs/guide/httpServer/staticResources.adoc
Labels: type: docs

#323 Metrics - Cleanup & Test Fix
  configurations/micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/management/endpoint/FilteredMetricsEndpointSpec.groovy
  configurations/micrometer-core/src/test/groovy/io/micronaut/docs/IndexController.java
  configurations/micrometer-core/src/test/groovy/io/micronaut/docs/MeterFilterFactory.java
  configurations/micrometer-core/src/test/groovy/io/micronaut/docs/SimpleMeterRegistryConfigurer.java
  gradle.properties
  src/main/docs/guide/management/providedEndpoints/metricsEndpoint.adoc
Labels: type: improvement
