Repository micronaut-projects/micronaut-core, pull requests merged in 2020-08, with the labels that each got.

#3878 Bump micronaut-cassandra to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#3867 Bump micronaut-grpc to 2.0.2
  gradle.properties
Labels: type: dependency-upgrade

#3894 Bump micronaut-servlet to 1.0.2
  gradle.properties
Labels: type: dependency-upgrade

#3874 Add new utility methods for GraalVM and refactor
  core/src/main/java/io/micronaut/core/graal/AutomaticFeatureUtils.java
Labels: relates-to: graal

#3911 Bump micronaut-grpc to 2.0.3
  gradle.properties
Labels: type: dependency-upgrade

#3930 Oracle updates
  build.gradle
  gradle.properties
Labels: relates-to: build

#3959 Bump micronaut-graphql to 1.4.0
  gradle.properties
Labels: type: dependency-upgrade

#3889 Adds tests to validate property loading with custom config locations and environment order
  inject/custom-config/application-env1.yml
  inject/custom-config/application-env2.yml
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
Labels: type: improvement

#3975 Bump micronaut-graphql to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3976 Bump micronaut-gcp to 2.0.2
  gradle.properties
Labels: type: dependency-upgrade

#3966 Added support for maps with multiple values for property injection
  inject-java/src/test/groovy/io/micronaut/inject/property/FieldPropertyInject.java
  inject-java/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
Labels: type: enhancement

#3980 Bump micronaut-mongodb to 2.1.1
  gradle.properties
Labels: type: dependency-upgrade

#3982 Bump micronaut-mongodb to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#3985 Bump micronaut-gcp to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3986 Bump micronaut-mongodb to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3988 Bump micronaut-micrometer to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3990 Bump micronaut-aws to 2.0.2
  gradle.properties
Labels: type: dependency-upgrade
