Repository micronaut-projects/micronaut-core, pull requests merged in 2020-09, with the labels that each got.

#3991 Add Micronaut Oracle Cloud to the BOM
  build.gradle
  gradle.properties
Labels: type: enhancement

#3997 Bump micronaut-oracle-cloud to 1.0.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#3998 Bump micronaut-jackson-xml to 1.1.1
  gradle.properties
Labels: type: dependency-upgrade

#3999 Bump micronaut-jackson-xml to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4015 Bump micronaut-picocli to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4022 Bump micronaut-gcp to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4025 Bump micronaut-openapi to 1.5.3
  gradle.properties
Labels: type: dependency-upgrade

#4028 Bump micronaut-openapi to 2.1.0
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#4035 Bump micronaut-azure to 2.0.0
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#4037 Bump micronaut-oracle-cloud to 1.0.0.RC3
  gradle.properties
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudInstanceMetadata.java
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataConfiguration.java
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataKeys.java
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudMetadataResolver.java
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/OracleCloudNetworkInterface.java
  runtime/src/main/java/io/micronaut/discovery/cloud/oraclecloud/package-info.java
Labels: type: dependency-upgrade

#4038 Bump micronaut-gcp to 3.1.0
  build.gradle
  gradle.properties
  parent/build.gradle
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeInstanceMetadata.java
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeInstanceMetadataResolver.java
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeMetadataConfiguration.java
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeMetadataKeys.java
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeNetworkInterface.java
  runtime/src/main/java/io/micronaut/discovery/cloud/gcp/package-info.java
Labels: type: dependency-upgrade

#4039 Bump micronaut-aws to 2.1.0.RC1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#4042 Bump micronaut-aws to 2.1.0.RC2
  gradle.properties
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonComputeInstanceMetadataResolver.java
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonEC2InstanceMetadata.java
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonMetadataConfiguration.java
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonNetworkInterface.java
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/EC2MetadataKeys.java
  runtime/src/main/java/io/micronaut/discovery/cloud/aws/package-info.java
  src/main/docs/guide/cloud/cloudConfiguration.adoc
Labels: type: dependency-upgrade

#4044 Bump micronaut-flyway to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4046 Bump micronaut-flyway to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4043 Support for JDK 14 records in introspection
  build.gradle
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/JavaParser.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/ClassElement.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject/src/main/java/io/micronaut/inject/processing/JavaModelUtils.java
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement

#4050 Bump micronaut-nats to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4059 Bump micronaut-flyway to 2.1.1
  gradle.properties
Labels: type: dependency-upgrade

#4060 Bump micronaut-flyway to 2.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4055 Bump micronaut-groovy to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4040 Bump micronaut-picocli to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4064 Bump micronaut-gcp to 3.1.1
  gradle.properties
Labels: type: dependency-upgrade

#4061 Upgrade to Netty 4.1.52
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
  test-suite/build.gradle
Labels: type: dependency-upgrade

#4074 Bump micronaut-neo4j to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4078 Bump micronaut-oracle-cloud to 1.0.0.RC4
  gradle.properties
Labels: type: dependency-upgrade

#3761 Create threads named after its executor/event-loop
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupRegistry.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyThreadFactory.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/threading/ThreadSelectionSpec.groovy
  runtime/src/main/java/io/micronaut/scheduling/executor/ExecutorConfiguration.java
  runtime/src/main/java/io/micronaut/scheduling/executor/ExecutorFactory.java
  runtime/src/main/java/io/micronaut/scheduling/executor/IOExecutorServiceConfig.java
  runtime/src/main/java/io/micronaut/scheduling/executor/NamedThreadFactory.java
  runtime/src/main/java/io/micronaut/scheduling/executor/ScheduledExecutorServiceConfig.java
  runtime/src/main/java/io/micronaut/scheduling/executor/UserExecutorConfiguration.java
  runtime/src/test/groovy/io/micronaut/scheduling/ScheduledFixedRateSpec.groovy
Labels: type: enhancement

#4057 Bump micronaut-kafka to 2.1.1
  gradle.properties
  src/main/docs/guide/httpServer/reactiveServer.adoc
Labels: type: dependency-upgrade

#4068 Dependency upgrades
  benchmarks/build.gradle
  build.gradle
  gradle.properties
  gradle/geb.gradle
  http-client/build.gradle
  http/build.gradle
  inject-java/build.gradle
  inject/build.gradle
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/EnvironmentPropertySourceSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy
  runtime/build.gradle
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
Labels: type: dependency-upgrade

#4081 Bump micronaut-spring to 2.1.1
  gradle.properties
Labels: type: dependency-upgrade

#4071 Bump micronaut-rabbitmq to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4027 Add support for a default environment
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
  runtime/src/main/java/io/micronaut/runtime/Micronaut.java
  src/main/docs/guide/config/environments.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement

#4088 Bump micronaut-acme to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4086 Bump micronaut-grpc to 2.0.5
  gradle.properties
Labels: type: dependency-upgrade

#4105 Bump micronaut-kafka to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4106 Bump micronaut-kotlin to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4092 Bump micronaut-cassandra to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4075 Bump micronaut-neo4j to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4108 Bump micronaut-gcp to 3.2.0
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#4012 Liveness and readiness probes
  management/src/main/java/io/micronaut/management/endpoint/health/HealthEndpoint.java
  management/src/main/java/io/micronaut/management/health/indicator/HealthCheckType.java
  management/src/main/java/io/micronaut/management/health/indicator/annotation/Liveness.java
  management/src/main/java/io/micronaut/management/health/indicator/annotation/Readiness.java
  management/src/main/java/io/micronaut/management/health/indicator/service/ServiceReadyHealthIndicator.java
  management/src/test/groovy/io/micronaut/management/endpoint/EndpointsPortSpec.groovy
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
Labels: type: enhancement

#4130 Bump micronaut-test to 2.1.0.M1
  gradle.properties
Labels: type: dependency-upgrade

#3921 Add API to make it easier to write method interceptors and support Kotlin suspend functions
  aop/build.gradle
  aop/src/main/java/io/micronaut/aop/InterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/CompletionStageInterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/InterceptedMethodUtil.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/PublisherInterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/SynchronousInterceptedMethod.java
  aop/src/main/kotlin/io/micronaut/aop/util/CompletableFutureContinuation.kt
  core/src/main/java/io/micronaut/core/async/publisher/Publishers.java
  core/src/main/java/io/micronaut/core/type/Argument.java
  core/src/main/java/io/micronaut/core/type/ReturnType.java
  core/src/main/java/io/micronaut/core/util/KotlinUtils.java
  function-client/src/main/java/io/micronaut/function/client/aop/FunctionClientAdvice.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/test/groovy/io/micronaut/http/client/aop/StreamSpec.groovy
  runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java
  runtime/src/main/java/io/micronaut/retry/intercept/RecoveryInterceptor.java
  runtime/src/main/java/io/micronaut/scheduling/async/AsyncInterceptor.java
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendClient.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendService.kt
  tracing/src/main/java/io/micronaut/tracing/interceptor/TraceInterceptor.java
  validation/src/main/java/io/micronaut/validation/ValidatingInterceptor.java
  websocket/src/main/java/io/micronaut/websocket/interceptor/ClientWebSocketInterceptor.java
Labels: type: enhancement

#4121 Bump micronaut-azure to 1.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4147 Bump micronaut-cache to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4144 Bump micronaut-aws to 2.0.3
  gradle.properties
Labels: type: dependency-upgrade

#4158 Bump micronaut-test to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4170 Bump micronaut-data to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4182 Bump micronaut-graphql to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4169 Bump micronaut-servlet to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4167 Bump micronaut-jaxrs to 1.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4166 Bump micronaut-liquibase to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4159 Bump micronaut-security to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4188 Bump micronaut-security to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4164 Bump micronaut-liquibase to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4192 Bump micronaut-security to 2.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4198 doc: Move multitenancy-gorm docs to groovy module
  src/main/docs/guide/multitenancy/multitenancyGorm.adoc
Labels: type: docs

#4200 Bump micronaut-oracle-cloud to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4202 Bump micronaut-aws to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4213 Bump micronaut-redis to 3.0.0
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#4215 Bump micronaut-micrometer to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4214 Bump micronaut-sql to 3.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4216 Bump micronaut-sql to 3.1.0
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#4220 Bump micronaut-gcp to 3.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4221 Bump micronaut-kotlin to 2.1.1
  gradle.properties
Labels: type: dependency-upgrade
