Repository micronaut-projects/micronaut-core, pull requests merged in 2020-04, with the labels that each got.

#2997 Maven Parent POM
  build.gradle
  gradle.properties
  gradle/publishing.gradle
  parent/build.gradle
  settings.gradle
  src/main/docs/guide/cli/createProject.adoc
  src/main/docs/guide/cli/reloading/automaticRestart.adoc
  src/main/docs/guide/cli/reloading/springloaded.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/quickStart/creatingServer.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#3063 Add retry predicate support for @Retryable and @CircuitBreaker
  runtime/src/main/java/io/micronaut/retry/annotation/CircuitBreaker.java
  runtime/src/main/java/io/micronaut/retry/annotation/DefaultRetryPredicate.java
  runtime/src/main/java/io/micronaut/retry/annotation/RetryPredicate.java
  runtime/src/main/java/io/micronaut/retry/annotation/Retryable.java
  runtime/src/main/java/io/micronaut/retry/intercept/AnnotationRetryStateBuilder.java
  runtime/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java
  runtime/src/test/groovy/io/micronaut/retry/intercept/CircuitBreakerRetrySpec.groovy
  runtime/src/test/groovy/io/micronaut/retry/intercept/SimpleRetryInstanceSpec.groovy
  runtime/src/test/groovy/io/micronaut/retry/intercept/SimpleRetrySpec.groovy
Labels: status: awaiting feedback

#3074 Don't load RefreshInterceptor in function and android environments.
  runtime/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshInterceptor.java
  runtime/src/test/groovy/io/micronaut/runtime/context/scope/RefreshScopeSpec.groovy
  runtime/src/test/groovy/io/micronaut/runtime/context/scope/refresh/RefreshInterceptorSpec.groovy
Labels: type: bug

#3083 Fix grammar
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
Labels: type: docs
