Repository micronaut-projects/micronaut-core, pull requests merged in 2020-12, with the labels that each got.

#4624 refactor: del uncessary @Inject ann in constructor
  http-client-core/src/main/java/io/micronaut/http/client/bind/DefaultHttpClientBinderRegistry.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http/src/main/java/io/micronaut/http/resource/ResourceLoaderFactory.java
  management/src/main/java/io/micronaut/management/health/indicator/jdbc/JdbcIndicator.java
  router/src/main/java/io/micronaut/web/router/naming/ConfigurableUriNamingStrategy.java
  router/src/main/java/io/micronaut/web/router/resource/StaticResourceConfiguration.java
  router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
  router/src/main/java/io/micronaut/web/router/version/VersionAwareRouterListener.java
  router/src/main/java/io/micronaut/web/router/version/resolution/HeaderVersionResolver.java
  router/src/main/java/io/micronaut/web/router/version/resolution/ParameterVersionResolver.java
  runtime/src/main/java/io/micronaut/reactive/rxjava2/RxJava2Instrumentation.java
  runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java
  tracing/src/main/java/io/micronaut/tracing/instrument/hystrix/TracingHystrixConcurrentStrategy.java
  validation/src/main/java/io/micronaut/validation/ValidatingInterceptor.java
  validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
Labels: type: improvement

#4628 refactor: RouteVersionFilter to ease override
  router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
Labels: type: improvement

#4577 Bump micronaut-neo4j to 4.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4575 fix: protect against npe thrown by nullable bean context
  aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java
Labels: type: bug

#4650 Bump micronaut-sql to 3.3.4
  gradle.properties
Labels: type: dependency-upgrade

#4652 Bump micronaut-data to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4654 Bump micronaut-spring to 2.1.2
  gradle.properties
Labels: type: dependency-upgrade

#4687 add documentation for Netty transport Linux ARM64
  src/main/docs/guide/httpServer/serverConfiguration.adoc
Labels: type: docs

#4691 Bump micronaut-jackson-xml to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4692 Bump micronaut-spring to 3.1.0
  gradle.properties
Labels: type: dependency-upgrade

#4698 Support for defining ConfigurationProperties with records
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/records/RecordBeansSpec.groovy
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement

#4710 Bump micronaut-test to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4713 Bump micronaut-flyway to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4714 Bump micronaut-liquibase to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4715 Bump micronaut-rabbitmq to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4696 Add configuration option to trim string values to null
  runtime/src/main/java/io/micronaut/jackson/JacksonConfiguration.java
  runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java
  runtime/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java
  runtime/src/test/groovy/io/micronaut/jackson/JacksonSetupSpec.groovy
Labels: type: improvement

#4705 Bump micronaut-openapi to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4700 Bump micronaut-gcp to 3.4.0
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#4671 Bump micronaut-aws to 2.2.4
  gradle.properties
Labels: type: dependency-upgrade

#4708 Bump micronaut-openapi to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4720 Bump micronaut-rabbitmq to 2.2.2
  gradle.properties
Labels: type: dependency-upgrade

#4721 Bump micronaut-rabbitmq to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#4722 Bump micronaut-test to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#4723 Bump micronaut-liquibase to 3.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4724 Bump micronaut-flyway to 3.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4725 Bump micronaut-jackson-xml to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4742 Bump micronaut-rxjava3 to 1.1.1
  gradle.properties
Labels: type: dependency-upgrade

#4740 Bump micronaut-security to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4747 Bump micronaut-servlet to 2.1.2
  gradle.properties
Labels: type: dependency-upgrade

#4749 Bump micronaut-maven-plugin to 1.1.2
  gradle.properties
Labels: type: dependency-upgrade

#4750 Bump micronaut-aws to 2.2.5
  gradle.properties
Labels: type: dependency-upgrade

#4760 Bump micronaut-openapi to 2.2.2
  gradle.properties
Labels: type: dependency-upgrade
