Repository micronaut-projects/micronaut-core, pull requests merged in 2020-06, with the labels that each got.

#3394 Bump micronaut-sql to 2.2.5
  gradle.properties
Labels: type: dependency-upgrade

#3401 Bump micronaut-kafka to 2.1.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#3400 Update to Micronaut-Flyway 2.0.0.M1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#3398 Bump micronaut-netflix to 2.0.0.RC1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#3402 Bump micronaut-neo4j to 3.0.0.RC1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#3407 Bump micronaut-jaxrs to 1.0.1
  gradle.properties
Labels: type: dependency-upgrade

#3408 Bump micronaut-redis to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3409 Bump micronaut-jackson-xml to 1.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3410 Bump micronaut-picocli to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3411 Bump micronaut-hibernate-validator to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3413 Bump micronaut-elasticsearch to 2.0.0.M2
  gradle.properties
Labels: type: dependency-upgrade

#3420 Bump micronaut-jmx to 2.0.0.M1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#3421 Bump micronaut-azure to 1.0.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3419 Improvement to allow creation of Map<String,Object> properties
  inject/build.gradle
  inject/src/main/java/io/micronaut/context/env/PropertySource.java
  inject/src/test/java/io/micronaut/context/PropertySourceTest.java
Labels: type: improvement

#3429 Bump micronaut-micrometer to 2.0.0.RC3
  gradle.properties
Labels: type: dependency-upgrade

#3430 Bump micronaut-test to 1.2.0.RC5
  gradle.properties
Labels: type: dependency-upgrade

#3431 Bump micronaut-liquibase to 2.0.0.M1
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#3438 Reduce RxJava2 wrappers
  runtime/src/main/java/io/micronaut/reactive/rxjava2/RxInstrumentedWrappers.java
Labels: type: improvement

#3436 Bump micronaut-security to 2.0.0.M3
  build.gradle
  gradle.properties
  src/main/docs/guide/introduction/upgrading.adoc
Labels: type: dependency-upgrade

#3442 Bump micronaut-sql to 2.2.6
  gradle.properties
Labels: type: dependency-upgrade

#3445 Bump micronaut-flyway to 2.0.0.M2
  gradle.properties
Labels: type: dependency-upgrade

#3446 Bump micronaut-servlet to 1.0.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3453 Bump micronaut-kubernetes to 2.0.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#3448 Bump micronaut-kubernetes to 1.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3457 Bump micronaut-gcp to 2.0.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3458 Bump micronaut-spring to 2.1.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3460 Bump micronaut-sql to 2.3.0
  build.gradle
  gradle.properties
  management/build.gradle
  src/main/docs/guide/cloud/clientSideLoadBalancing/netflixRibbon.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationAwsParameterStore.adoc
  src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryRoute53.adoc
  src/main/docs/guide/configurations/dataAccess.adoc
  src/main/docs/guide/configurations/dataAccess/hibernateSupport.adoc
  src/main/docs/guide/configurations/dataAccess/mongoSupport.adoc
  src/main/docs/guide/configurations/dataAccess/mysqlSupport.adoc
  src/main/docs/guide/configurations/dataAccess/neo4jSupport.adoc
  src/main/docs/guide/configurations/dataAccess/postgresSupport.adoc
  src/main/docs/guide/configurations/dataAccess/redisSupport.adoc
  src/main/docs/guide/configurations/dataAccess/sqlSupport.adoc
  src/main/docs/guide/configurations/otherConfigurations/rabbitmq.adoc
  src/main/docs/guide/httpClient/clientAnnotation.adoc
  src/main/docs/guide/httpClient/clientAnnotation/netflixHystrix.adoc
  src/main/docs/guide/httpServer/datavalidation.adoc
  src/main/docs/guide/httpServer/sessions.adoc
  src/main/docs/guide/ioc/beanValidation.adoc
Labels: type: dependency-upgrade

#3461 Bump micronaut-hibernate-validator to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#3464 Bump micronaut-data to 1.1.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3480 Bump micronaut-grpc to 2.0.0.M4
  gradle.properties
Labels: type: dependency-upgrade

#3484 Bump micronaut-sql to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#3490 Bump micronaut-spring to 2.1.0.RC3
  gradle.properties
Labels: type: dependency-upgrade

#3493 Bump micronaut-test to 1.2.0.RC6
  gradle.properties
Labels: type: dependency-upgrade

#3494 Bump micronaut-sql to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#3495 Bump micronaut-micrometer to 2.0.0.RC4
  gradle.properties
Labels: type: dependency-upgrade

#3501 Bump micronaut-reactor to 1.0.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3499 Bump micronaut-data to 1.1.0.RC3
  gradle.properties
Labels: type: dependency-upgrade

#3503 doc: transaction management changes
  gradle.properties
  src/main/docs/guide/introduction/upgrading.adoc
Labels: type: docs

#3506 Remove thread factory tracing
  runtime/src/main/java/io/micronaut/scheduling/instrument/ThreadFactoryInstrumenter.java
Labels: type: bug

#3509 Bump micronaut-servlet to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3510 Bump micronaut-elasticsearch to 2.0.0.RC2
  gradle.properties
Labels: type: dependency-upgrade

#3513 Bump micronaut-sql to 2.3.3
  gradle.properties
Labels: type: dependency-upgrade

#3521 Bump micronaut-kafka to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3522 Bump micronaut-gcp to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3524 Bump micronaut-spring to 2.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3526 Bump micronaut-micrometer to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3523 Bump micronaut-test to 1.2.0
  gradle.properties
Labels: type: dependency-upgrade

#3531 Bump micronaut-data to 1.1.0
  gradle.properties
Labels: type: dependency-upgrade

#3529 Bump micronaut-kotlin to 1.0.1
  gradle.properties
Labels: type: dependency-upgrade

#3536 Bump micronaut-acme to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3541 Bump micronaut-elasticsearch to 2.0.0.RC3
  gradle.properties
Labels: type: dependency-upgrade

#3540 Bump micronaut-sql to 2.3.4
  gradle.properties
Labels: type: dependency-upgrade

#3551 Bump micronaut-data to 1.1.1
  gradle.properties
Labels: type: dependency-upgrade

#3556 Bump micronaut-redis to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#3558 Bump micronaut-sql to 2.3.6
  gradle.properties
Labels: type: dependency-upgrade

#3568 Bump micronaut-grpc to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3569 Bump micronaut-reactor to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3570 Bump micronaut-neo4j to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3571 Bump micronaut-flyway to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#3573 Bump micronaut-redis to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#3586 Support `Optional` in interface config
  core/src/main/java/io/micronaut/core/type/ReturnType.java
  inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
  runtime/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java
Labels: type: improvement

#3584 Add support for Http2 settings.
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
Labels: type: enhancement
