Repository micronaut-projects/micronaut-core, pull requests merged in 2021-05, with the labels that each got.

#5372 Bump micronaut-kafka to 3.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5373 Bump micronaut-data to 2.4.2
  gradle.properties
Labels: type: dependency-upgrade

#5360 Support for introspections on public / package protected fields
  core/src/main/java/io/micronaut/core/annotation/Introspected.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanFieldWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/introspection.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/beans/IntrospectionSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/beans/User.groovy
  test-suite/src/test/java/io/micronaut/docs/ioc/beans/IntrospectionSpec.java
  test-suite/src/test/java/io/micronaut/docs/ioc/beans/User.java
Labels: type: enhancement

#5355 Bump micronaut-cache to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5380 Bump micronaut-gcp to 3.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5387 bump up micronaut security to 2.3.4
  gradle.properties
Labels: type: dependency-upgrade

#5385 Bump micronaut-jms to 1.0.0.M2
  gradle.properties
Labels: type: dependency-upgrade

#5397 Bump micronaut-kafka to 3.3.2
  gradle.properties
Labels: type: dependency-upgrade

#5402 Bump micronaut-cassandra to 3.1.1
  gradle.properties
Labels: type: dependency-upgrade

#5404 Bump micronaut-cassandra to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#5415 Bump micronaut-kubernetes to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#5410 Bump micronaut-cassandra to 4.0.0
  gradle.properties
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#5436 Bump micronaut-nats to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5444 Bump micronaut-data to 2.4.3
  gradle.properties
Labels: type: dependency-upgrade

#5452 Bump micronaut-test to 2.3.4
  gradle.properties
Labels: type: dependency-upgrade

#5455 Bump micronaut-oracle-cloud to 1.3.5
  gradle.properties
Labels: type: dependency-upgrade

#5456 Bump micronaut-liquibase to 3.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5461 Bump micronaut-picocli to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5466 Bump micronaut-discovery-client to 2.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5472 Fix checkstyle
  http-client-core/src/main/java/io/micronaut/http/client/loadbalance/AbstractRoundRobinLoadBalancer.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: improvement

#5473 Fix annotate not working when invoked multiple times by different visitors
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/AnnotateReplacesSpec.groovy
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
Labels: type: bug

#5471 bump up azure functions java library version to 1.4.2
  build.gradle
  gradle.properties
Labels: relates-to: build, type: dependency-upgrade

#5477 Bump micronaut-graphql to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5470 Bump micronaut-azure to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#5475 Bump micronaut-flyway to 3.7.0
  gradle.properties
Labels: type: dependency-upgrade

#5498 Bump micronaut-graphql to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5482 Bump micronaut-jms to 1.0.0.M3
  gradle.properties
Labels: type: dependency-upgrade
