Repository micronaut-projects/micronaut-core, pull requests merged in 2021-09, with the labels that each got.

#6075 fix: if proxy request is not mutable call mutate
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/ProxyHttpClientMutableRequestSpec.groovy
Labels: type: bug

#6076 test: add @RestoreSystemProperties to test modifying system Properties
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
Labels: type: improvement

#6086 Bump micronaut-maven-plugin to 3.0.2
  gradle.properties
Labels: type: dependency-upgrade

#6088 Bump micronaut-data to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#6101 feat: allow SameSite case insensitive binding
  http-server-netty/src/test/groovy/io/micronaut/http/cookie/SameSiteCaseInsensitiveViaConfigurationSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/cookie/SameSiteJsonValueSpec.groovy
  http/src/main/java/io/micronaut/http/cookie/SameSiteConverter.java
Labels: type: bug

#6091 Bump micronaut-security to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#6103 Bump micronaut-openapi to 3.0.2
  gradle.properties
Labels: type: dependency-upgrade

#6104 Bump micronaut-liquibase to 3.4.1
  gradle.properties
Labels: type: dependency-upgrade

#6105 Bump micronaut-liquibase to 4.0.3
  gradle.properties
Labels: type: dependency-upgrade

#6114 fix: access parent request from Reactor Context in HTTP ClientFilter
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/context/HttpClientFilterRequestInReactorContextSpec.groovy
Labels: type: bug

#6123 Bump micronaut-openapi to 3.0.3
  gradle.properties
Labels: type: dependency-upgrade

#6128 Bind to port zero get random port.
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
Labels: type: improvement

#6120 Don't block the event loop when reading inputstream.
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/InputStreamBodyBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/InputStreamBodySpec.groovy
  inject/src/main/java/io/micronaut/context/BeanProvider.java
Labels: type: bug

#6090 Initial support for factories for primitive types
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/factory/FactoryBeanFieldSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/aop/simple/Mutating.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/FactoryBeanDefinitionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanfield/FactoryBeanFieldSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  inject/src/main/java/io/micronaut/inject/writer/ArrayAwareSignatureWriter.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  src/main/docs/guide/ioc/factories.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/factories/primitive/CylinderFactory.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/factories/primitive/EngineSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/factories/primitive/V8Engine.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/primitive/CylinderFactory.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/primitive/EngineSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/primitive/V8Engine.kt
  test-suite/src/test/java/io/micronaut/docs/factories/primitive/CylinderFactory.java
  test-suite/src/test/java/io/micronaut/docs/factories/primitive/EngineSpec.java
  test-suite/src/test/java/io/micronaut/docs/factories/primitive/V8Engine.java
Labels: type: enhancement

#6137 Allow refreshing the server SSL configuration using a RefreshEvent
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshEventListener.java
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScope.java
  context/src/test/groovy/io/micronaut/runtime/context/scope/refresh/RefreshEventListenerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/SslRefreshSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/CertificateProvidedSslBuilder.java
  management/src/main/java/io/micronaut/management/endpoint/refresh/RefreshEndpoint.java
  src/main/docs/guide/httpServer/serverConfiguration/https.adoc
Labels: type: improvement

#6122 Correctly handle absence of request in RequestScope
  http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  inject/src/main/java/io/micronaut/context/scope/AbstractConcurrentCustomScope.java
  runtime/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java
Labels: type: bug

#6152 Support an API to start multiple netty servers
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshEventListener.java
  context/src/main/java/io/micronaut/scheduling/executor/DefaultExecutorSelector.java
  context/src/main/java/io/micronaut/scheduling/executor/ExecutorSelector.java
  core/src/main/java/io/micronaut/core/util/RegexPathMatcher.java
  http-client-core/src/main/java/io/micronaut/http/client/annotation/Client.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpContentProcessorResolver.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/StreamTypeHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBinderRegistrar.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/PublisherBodyBinder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/DefaultCustomizableResponseTypeHandlerRegistry.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/FileTypeHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/FileTypeHandlerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/stream/NettyStreamedCustomizableResponseType.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/NettyMultiServerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/TestNettySecondaryServer.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/CacheControlSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/UpgradeSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  inject-groovy/src/test/groovy/io/micronaut/inject/factory/named/ImplicitNamedSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/BeanContext.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  router/src/main/java/io/micronaut/web/router/resource/StaticResourceResolver.java
  router/src/main/java/io/micronaut/web/router/resource/StaticResourceResolverFactory.java
  router/src/test/groovy/io/micronaut/web/router/resource/StaticResourceResolverSpec.groovy
  src/main/docs/guide/httpServer/serverConfiguration/secondaryServers.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/secondary/SecondaryServerTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/secondary/SecondaryServerTest.kt
  test-suite/src/test/java/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.java
  test-suite/src/test/java/io/micronaut/docs/http/server/secondary/SecondaryServerTest.java
Labels: type: enhancement

#6163 Bump Micronaut Test to 3.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6166 Use nanoTime for durations
  context/src/main/java/io/micronaut/runtime/Micronaut.java
Labels: type: improvement

#6168 Replace use of @Overrides with caching
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
Labels: type: bug

#6170 Fix support nullable inputstream
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpContentProcessor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/InputStreamBodyBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/FluxBodySpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/InputStreamBodySpec.groovy
  http-server/src/main/java/io/micronaut/http/server/binding/RequestArgumentSatisfier.java
Labels: type: bug

#6172 Bump micronaut-jaxrs to 3.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6184 Makes exception more informative, fixes #5418
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
Labels: type: improvement

#6199 Fix missing BOM properties
  build.gradle
  gradle/libs.versions.toml
Labels: type: bug

#6201 Support for repeatable qualifiers
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  core/src/test/groovy/io/micronaut/core/annotation/AnnotationValueSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/InMemoryByteCodeGroovyClassLoader.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyAnnotationElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyElementFactory.java
  inject-groovy/src/test/groovy/io/micronaut/inject/qualifiers/repeatable/RepeatableQualifierSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaAnnotationElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaElementFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/annotation/AnnotationQualifierSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/annotationmember/NonBindingQualifierSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/named/NamedQualifierSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/repeatable/RepeatableQualifierSpec.groovy
  inject/src/main/java/io/micronaut/context/scope/AbstractConcurrentCustomScope.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject/src/main/java/io/micronaut/inject/ast/AnnotationElement.java
  inject/src/main/java/io/micronaut/inject/qualifiers/AnnotationMetadataQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
  inject/src/main/java/io/micronaut/inject/qualifiers/RepeatableAnnotationQualifier.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
Labels: type: enhancement

#6203 Fix race condition with writing last http content
  http-client/src/test/groovy/io/micronaut/http/client/ProxyHttpClientMutableRequestSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/reactive/HandlerSubscriber.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
Labels: type: bug

#6204 Fixes setting up of duplicate headers in MutableHttpMessage. Fixes #6192
  http/src/main/java/io/micronaut/http/MutableHttpMessage.java
  http/src/test/groovy/io/micronaut/http/MutableHttpMessageSpec.groovy
Labels: type: bug

#6213 Add ElementType.ANNOTATION_TYPE to all tracing annotations
  tracing/src/main/java/io/micronaut/tracing/annotation/ContinueSpan.java
  tracing/src/main/java/io/micronaut/tracing/annotation/NewSpan.java
  tracing/src/main/java/io/micronaut/tracing/annotation/SpanTag.java
Labels: type: improvement

#6187 Propagate Reactor context to Kotlin coroutines if `kotlinx-coroutines-reactor` is present
  gradle/libs.versions.toml
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  http/build.gradle
  http/src/main/kotlin/io/micronaut/http/bind/binders/ContinuationArgumentBinder.kt
  src/main/docs/guide/languageSupport/kotlin/context.adoc
  src/main/docs/guide/toc.yml
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/reactor/ReactorContextPropagationSpec.kt
Labels: type: enhancement, lang: kotlin

#6217 Bean introspection with method dispatch and static metadata
  inject/src/main/java/io/micronaut/context/AbstractExecutableMethodsDefinition.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanFieldWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanMethodWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  inject/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
Labels: type: improvement

#6219 Respect configured property inclusion in BeanIntrospectionPropertyWriter
  runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  runtime/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: bug

#6222 Bump to Oracle Cloud 2.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6215 Document VSCode Tooling Options
  src/main/docs/guide/quickStart/ideSetup/vsCodeSetup.adoc
Labels: type: docs

#6227 Improve Bean Introspection compilation
  core/src/main/java/io/micronaut/core/beans/AbstractBeanIntrospection.java
  core/src/main/java/io/micronaut/core/beans/BeanIntrospection.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractAnnotationMetadataWriter.java
  inject/src/main/java/io/micronaut/inject/writer/StringSwitchWriter.java
Labels: type: improvement

#6223 Store repeatable annotations info and avoid reflection call
  core/src/main/java/io/micronaut/core/annotation/AnnotationMetadata.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationMetadataDelegate.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataHierarchy.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataSupport.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
Labels: type: enhancement

#6237 Bump micronaut-security to 3.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6253 Use argument context to determine conversion type even for scalar values
  jackson-databind/src/test/groovy/io/micronaut/jackson/databind/convert/JsonNodeToObjectConverterSpec.groovy
  json-core/src/main/java/io/micronaut/json/convert/JsonConverterRegistrar.java
Labels: type: improvement

#6251 Correct bootstrap env detection
  inject-groovy-test/src/main/groovy/io/micronaut/ast/transform/test/AbstractBeanDefinitionSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractKotlinCompilerSpec.groovy
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  runtime/src/test/groovy/io/micronaut/bootstrap/CustomPropertySourceLocatorSpec.groovy
Labels: type: improvement

#6250 Support for receiver type & throws clause in MethodElement API
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyMethodElement.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/ClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/ElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/MethodElement.java
Labels: type: enhancement
