Repository micronaut-projects/micronaut-core, pull requests merged in 2021-03, with the labels that each got.

#5033 Bump micronaut-maven-plugin to 1.1.7
  gradle.properties
Labels: type: dependency-upgrade

#5043 Bump micronaut-data to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5044 Bump micronaut-r2dbc to 1.1.0
  gradle.properties
Labels: type: dependency-upgrade

#5045 build: add picocli-gen to bom
  build.gradle
Labels: relates-to: build

#5047 Serializing JSON with records should respect JsonIgnore
  inject-java-test/build.gradle
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  runtime/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: priority: high, type: bug

#5057 Bump micronaut-elasticsearch to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#5063 Bump micronaut-aws to 2.4.0
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#4885 Making the parent HTTP Request available in handlers of the DefaultHttpClient
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/RxNettyHttpClientRegistry.java
  tracing/src/main/java/io/micronaut/tracing/brave/sender/HttpClientSender.java
  tracing/src/main/java/io/micronaut/tracing/brave/sender/HttpClientSenderFactory.java
Labels: type: improvement

#5066 Bump micronaut-kafka to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#5067 refactor: use Micronaut Nullable
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ParentArrayEachPropsCtor.java
  test-suite/src/test/java/io/micronaut/docs/server/binding/MovieTicketBean.java
Labels: type: improvement

#5069 Bump micronaut-discovery-client to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5074 Bump micronaut-rabbitmq to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5077 Bump micronaut-data to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5112 Bump micronaut-security to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5113 Bump micronaut-security to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5092 javadoc: @deprecated ExceptionHandlers constructor
  http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/DuplicateRouteHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/UnsatisfiedRouteHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/ContentLengthExceededHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/ConversionErrorHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/HttpStatusHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/JsonExceptionHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/URISyntaxHandler.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/UnsatisfiedArgumentHandler.java
  validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java
  validation/src/main/java/io/micronaut/validation/exceptions/ValidationExceptionHandler.java
Labels: type: improvement

#5117 Dependency upgrades
  build.gradle
  gradle.properties
  gradle/geb.gradle
  http-client/build.gradle
  http-server-netty/build.gradle
  inject-groovy/build.gradle
  inject-java/build.gradle
  inject/build.gradle
  management/build.gradle
  runtime/build.gradle
Labels: type: dependency-upgrade

#5139 Bump micronaut-nats to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#5142 Bump micronaut-aws to 2.4.1
  gradle.properties
Labels: type: dependency-upgrade

#5146 Bump micronaut-aws to 2.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5162 Bump micronaut-jackson-xml to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5163 Bump micronaut-redis to 4.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5168 Bump micronaut-liquibase to 3.1.0
  gradle.properties
Labels: type: dependency-upgrade

#5171 Bump micronaut-flyway to 3.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5178 javadoc: micronaut.config-client.enabled
  runtime/src/main/java/io/micronaut/discovery/config/ConfigurationClient.java
Labels: type: docs

#5182 Bump micronaut-test to 2.3.3
  gradle.properties
Labels: type: dependency-upgrade

#5188 Bump micronaut-security to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#5193 Bump micronaut-aws to 2.4.2
  gradle.properties
Labels: type: dependency-upgrade
