Repository micronaut-projects/micronaut-core, pull requests merged in 2021-06, with the labels that each got.

#5519 Bump micronaut-aws to 2.6.1
  gradle.properties
Labels: type: dependency-upgrade

#5517 fix: escape closing curly brace
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
Labels: type: bug

#5515 Bump micronaut-test to 2.3.6
  gradle.properties
Labels: type: dependency-upgrade

#5502 Bump micronaut-kubernetes to 2.3.3
  gradle.properties
Labels: type: dependency-upgrade

#5518 Bump micronaut-aws to 2.7.1
  gradle.properties
Labels: type: dependency-upgrade

#5562 Bump micronaut-data to 2.4.4
  gradle.properties
Labels: type: dependency-upgrade

#5563 Bump micronaut-grpc to 2.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5199 feat: Excel Media Types
  http/src/main/java/io/micronaut/http/MediaType.java
Labels: type: improvement

#5582 Bump micronaut-redis to 4.0.2
  gradle.properties
Labels: type: dependency-upgrade

#5587 test: groovy.test.NotYetImplemented
  function-web/src/test/groovy/io/micronaut/function/web/JavaLambdaFunctionSpec.groovy
Labels: type: improvement

#5589 Bump micronaut-kubernetes to 2.3.4
  gradle.properties
Labels: type: dependency-upgrade

#4073 Trigger exception error route before triggering status error route
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/CustomErrorUnsatisfiedRouteSpec.groovy
  src/main/docs/guide/appendix/breaks.adoc
Labels: status: next major version

#5593 build: remove deprecations from bom
  build.gradle
Labels: relates-to: build

#5595 replace reactivex @NonNull annotation with Micronaut's @NonNull
  http-client/src/test/groovy/io/micronaut/http/client/StreamRequestSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/threading/ThreadSelectionSpec.groovy
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
Labels: type: improvement

#5601 checkstyle: no import if only used in javadoc
  runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java
Labels: type: improvement

#5598 Bump micronaut-test to 2.3.7
  gradle.properties
Labels: type: dependency-upgrade

#5624 extract websocket upgrade method
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
Labels: type: improvement

#5612 Reworks the CustomScope interface to support disposing dependent instances.
  context/src/main/java/io/micronaut/runtime/context/scope/ThreadLocalCustomScope.java
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScope.java
  inject-groovy/src/test/resources/logback.xml
  inject-java/src/test/groovy/io/micronaut/inject/dependent/BeanB.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/BeanC.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/BeanD.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/BeanE.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/DestroyDependentBeansSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/dependent/InterfaceA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/ScopedBeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/SingletonBeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/TestAnn.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/TestData.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/TestInterceptor.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/DSecondFactoryMethodReplacement.java
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionRegistry.java
  inject/src/main/java/io/micronaut/context/BeanRegistration.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/scope/AbstractConcurrentCustomScope.java
  inject/src/main/java/io/micronaut/context/scope/BeanCreationContext.java
  inject/src/main/java/io/micronaut/context/scope/CreatedBean.java
  inject/src/main/java/io/micronaut/context/scope/CustomScope.java
  inject/src/main/java/io/micronaut/inject/DisposableBeanDefinition.java
  inject/src/main/java/io/micronaut/inject/qualifiers/ExactTypeArgumentNameQualifier.java
  runtime/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java
  session/src/test/resources/logback.xml
  test-suite-javax-inject/src/test/resources/logback.xml
  test-suite/src/test/java/io/micronaut/docs/client/versioning/HelloClient.java
Labels: type: enhancement

#5633 Bump micronaut-security to 2.4.3
  gradle.properties
Labels: type: dependency-upgrade

#5637 Bump micronaut-security to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5638 Bump micronaut-oracle-cloud to 1.3.6
  gradle.properties
Labels: type: dependency-upgrade

#5651 Fix dead link in graal.adoc
  src/main/docs/guide/languageSupport/graal.adoc
Labels: type: docs

#5661 Bump micronaut-problem-json to 2.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5677 Bump micronaut-nats to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade
