Repository micronaut-projects/micronaut-core, pull requests merged in 2021-01, with the labels that each got.

#4772 Bump micronaut-data to 2.2.2
  gradle.properties
Labels: type: dependency-upgrade

#4778 Bump micronaut-sql to 3.3.5
  gradle.properties
Labels: type: dependency-upgrade

#4783 Bump micronaut-maven-plugin to 1.1.3
  gradle.properties
Labels: type: dependency-upgrade

#4784 Bump micronaut-data to 2.2.3
  gradle.properties
Labels: type: dependency-upgrade

#4787 Bump micronaut-jaxrs to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4788 Bump micronaut-r2dbc to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#4795 Bump micronaut-picocli to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4798 Bump micronaut-test to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#4802 Bump micronaut-flyway to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4803 Bump micronaut-views to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4804 Bump micronaut-discovery-client to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#4809 Upgrade Netty to 4.1.58
  gradle.properties
Labels: type: dependency-upgrade

#4812 Bump micronaut-aws to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4810 Support for copy-constructors on immutable introspections
  core/src/main/java/io/micronaut/core/beans/AbstractBeanProperty.java
  core/src/main/java/io/micronaut/core/beans/BeanProperty.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
Labels: type: enhancement

#4800 Bump micronaut-rabbitmq to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#4813 Support for executable methods on introspections
  core/src/main/java/io/micronaut/core/beans/AbstractBeanIntrospection.java
  core/src/main/java/io/micronaut/core/beans/AbstractBeanMethod.java
  core/src/main/java/io/micronaut/core/beans/AbstractBeanProperty.java
  core/src/main/java/io/micronaut/core/beans/BeanIntrospection.java
  core/src/main/java/io/micronaut/core/beans/BeanMethod.java
  core/src/main/java/io/micronaut/core/type/Executable.java
  core/src/main/java/io/micronaut/core/type/ReturnType.java
  inject-groovy-test/src/main/groovy/io/micronaut/AbstractBeanDefinitionSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyFieldElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyMethodElement.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/ClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/DefaultElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/ElementQuery.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractExecutableBeanMethod.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanMethodWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement

#4828 Bump micronaut-sql to 3.4.0
  gradle.properties
Labels: type: dependency-upgrade

#4833 Bump micronaut-maven-plugin to 1.1.4
  gradle.properties
Labels: type: dependency-upgrade

#4840 Bump micronaut-cache to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4839 Bump micronaut-kubernetes to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4627 fix: inject interface not impl version listener
  http-server-netty/src/test/groovy/io/micronaut/web/router/version/RouteVersionFilterReplacementSpec.groovy
  router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
  router/src/main/java/io/micronaut/web/router/version/VersionAwareRouterListener.java
  router/src/main/java/io/micronaut/web/router/version/VersionRouteMatchFilter.java
Labels: type: improvement

#4832 Bump micronaut-security to 2.2.2
  gradle.properties
Labels: type: dependency-upgrade

#4841 Bump micronaut-r2dbc to 1.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4838 Bump micronaut-discovery-client to 2.2.2
  gradle.properties
Labels: type: dependency-upgrade

#4845 Bump micronaut-data to 2.2.4
  gradle.properties
Labels: type: dependency-upgrade

#4843 Bump micronaut-security to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4846 Bump micronaut-micrometer to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#4859 Bump micronaut-openapi to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade
