Repository micronaut-projects/micronaut-core, pull requests merged in 2021-12, with the labels that each got.

#6591 Bump micronaut-test to 3.0.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6589 Use the correct argument when getting a scoped bean
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/AbstractBean.java
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/AnotherConcurrentScopeImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/BeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/BeanB.java
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/CustomScopeSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#6600 remove netty from annotation processor path. Fixes #6599
  http-validation/build.gradle
Labels: type: bug

#6598 Upgrade to build plugins 5.0.x
  bom/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.bom-checker.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/pom/PomChecker.groovy
  buildSrc/src/main/groovy/io/micronaut/build/internal/pom/VersionCatalogConverter.groovy
  settings.gradle
Labels: relates-to: build

#6559 Bump micronaut-security to 3.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6602 Some build tweaks
  aop/build.gradle
  benchmarks/build.gradle
  build.gradle
  core/build.gradle
  gradle/geb.gradle
  http-client-core/build.gradle
  http-client/build.gradle
  http-server-netty/build.gradle
  http/build.gradle
  inject-groovy-test/build.gradle
  inject-groovy/build.gradle
  inject-java-test/build.gradle
  inject-java/build.gradle
  inject-kotlin-test/build.gradle
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
  tracing/build.gradle
  websocket/build.gradle
Labels: relates-to: build

#6604 Bump micronaut-flyway to 5.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6605 Bump micronaut-grpc to 3.1.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6597 Support HTTP 1.1 pipelining
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/HttpPipeliningSpec.groovy
Labels: type: improvement

#6610 Bump micronaut-spring to 4.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6616 Initialize netty classes at runtime
  http-netty/src/main/java/io/micronaut/http/netty/graal/HttpNettyFeature.java
  http-netty/src/main/resources/META-INF/native-image/io.micronaut/micronaut-http-netty/native-image.properties
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpResponseFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ServerAttributeKeys.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/CookiesElement.java
Labels: type: bug, priority: high

#6612 Bump micronaut-data to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6628 improve performance of isWebSocketUpgrade
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
Labels: type: improvement

#6622 Upgrade Netty to 4.1.71
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6629 Bump micronaut-views to 3.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6644 Fix interceptor bindings not applied from stereotype annotations
  aop/src/main/java/io/micronaut/aop/internal/intercepted/InterceptedMethodUtil.java
  inject-java/src/test/groovy/io/micronaut/aop/compile/AroundCompileSpec.groovy
Labels: type: bug

#6635 Introduce an internal interface for finalizing context configuration
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/InitializableBeanContext.java
Labels: type: improvement

#6645 Bump micronaut-elasticsearch to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6651 Bump micronaut-grpc to 3.1.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6653 Fix advice not applying when only on constructor
  inject-java/src/test/groovy/io/micronaut/aop/compile/AroundConstructCompileSpec.groovy
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
Labels: type: bug

#6649 Ignore accessors with explicit `JsonIgnore`
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: bug

#6658 Bump micronaut-views to 3.0.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6669 Fix bug with resolving bindings from AnnotationMetadataHierarchy
  core/src/main/java/io/micronaut/core/annotation/AnnotationMetadata.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataHierarchy.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/qualifiers/InterceptorBindingQualifier.java
Labels: type: bug

#6671 build: log4j2 update to 2.17.0 from 2.16.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6603 [core] Update common files for branch 3.2.x
  .github/workflows/central-sync.yml
  .github/workflows/corretto.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .gitignore
  config/checkstyle/.rsync-filter
  core/src/test/groovy/io/micronaut/core/bind/ExecutableBinderSpec.groovy
  core/src/test/groovy/io/micronaut/core/convert/DefaultConversionServiceSpec.groovy
  core/src/test/groovy/io/micronaut/core/io/WritableSpec.groovy
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/redirect/HttpToHttpsRedirectSpec.groovy
  http-server/src/test/groovy/io/micronaut/http/server/util/locale/LocaleResolutionSpec.groovy
  inject-kotlin-test/src/test/groovy/io/micronaut/annotation/processing/test/KotlinCompilerTest.groovy
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/EnvironmentOrderSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/EnvironmentPropertySourceSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/yaml/YamlPropertySourceLoaderSpec.groovy
  jackson-core/src/test/groovy/io/micronaut/jackson/core/env/JsonPropertySourceLoaderSpec.groovy
  settings.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/docs/aop/lifecycle/LifeCycleAdviseSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/bind/ShoppingCartControllerSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/secondary/SecondaryServerTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/writable/WritableSpec.groovy
Labels: relates-to: build

#6660 build: updates logback from 1.2.3 to 1.2.8
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6675 Bump micronaut-data to 3.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6679 Bump micronaut-liquibase to 5.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6680 Bump micronaut-flyway to 5.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
