Repository micronaut-projects/micronaut-core, pull requests merged in 2021-11, with the labels that each got.

#6461 Bump micronaut-aws to 3.0.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6425 Support public-only fields and methods for introspections
  core/src/main/java/io/micronaut/core/annotation/Introspected.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
Labels: type: improvement

#6435 Bump micronaut-kubernetes to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6455 Only retrieve annotation defaults when they are not already present
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
Labels: type: improvement

#6462 Fix minor typo in error message
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
Labels: type: improvement

#6460 Consider `@JsonView` annotation for request body deserialization
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewController.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy
  http/src/main/java/io/micronaut/http/bind/binders/ParameterAnnotationBinder.java
  jackson-databind/src/main/java/io/micronaut/jackson/databind/JacksonDatabindMapper.java
  json-core/src/main/java/io/micronaut/json/convert/JsonConverterRegistrar.java
Labels: type: improvement

#6474 Rename `Customizer` to `Configurer`
  inject-groovy/src/functionalTest/groovy/io/micronaut/context/ApplicationContextConfigurerSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/ServiceDescriptionProcessor.java
  inject/src/main/java/io/micronaut/context/ApplicationContextConfigurer.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/visitor/ContextConfigurerVisitor.java
  test-suite/src/functionalTest/groovy/io/micronaut/context/ApplicationContextConfigurerSpec.groovy
Labels: type: improvement

#6451 Add missing properties when deserializing type with partial reflective access
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
Labels: type: bug

#6478 Bump micronaut-openapi to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6484 Do not replace creator properties from introspection
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: bug

#6489 Copy setter annotations for bean properties
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstAnnotationUtils.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: improvement

#6491 Bump micronaut-flyway to 5.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6498 Bump micronaut-liquibase to 5.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6497 Upgrade to Micronaut Build 4.2.6
  build.gradle
  buildSrc/build.gradle
  settings.gradle
Labels: relates-to: build

#6504 Bump micronaut-elasticsearch to 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6505 Bump micronaut-redis to 5.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6490 Bump micronaut-grpc to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6507 Fix AbstractTypeElementSpec on Java 17
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/JavaFileObjectClassLoader.java
  inject-java-test/src/main/java/io/micronaut/annotation/processing/test/JavaParser.java
Labels: type: bug

#6506 Fix support for secondary servers with custom SSL config
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DelegateNettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServerFactory.java
  src/main/docs/guide/httpServer/serverConfiguration/secondaryServers.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/secondary/SecondaryServerTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/secondary/SecondaryServerTest.kt
  test-suite/src/test/java/io/micronaut/docs/http/server/secondary/SecondaryNettyServer.java
  test-suite/src/test/java/io/micronaut/docs/http/server/secondary/SecondaryServerTest.java
Labels: type: bug

#6511 Mark attribute multipart parts for release
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
Labels: type: bug

#6512 Replace usages of identityHashCode to prevent collisions
  http-server-netty/src/main/java/io/micronaut/http/server/netty/IdentityWrapper.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
Labels: type: improvement

#6513 Fix stackoverflow with array generics
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/generics/GenericFactorySpec.groovy
Labels: type: bug

#6487 Support WebSocket permessage-deflate extension
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-netty/src/main/java/io/micronaut/http/netty/websocket/WebSocketMessageEncoder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/HttpRequestCertificateHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/BinaryWebSocketSpec.groovy
Labels: type: improvement

#6517 Introduce handshakeTimeout option to SslConfiguration
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/SslSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http/src/main/java/io/micronaut/http/ssl/SslConfiguration.java
Labels: type: improvement

#6510 Add support for GenericPlaceholder at runtime
  core/src/main/java/io/micronaut/core/type/Argument.java
  core/src/main/java/io/micronaut/core/type/DefaultGenericPlaceholder.java
  core/src/main/java/io/micronaut/core/type/GenericPlaceholder.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionGenericsSpec.groovy
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
Labels: type: enhancement

#6494 Move to URI for HTTP client API to support ws/wss schemes
  http-client-core/src/main/java/io/micronaut/http/client/DefaultLoadBalancerResolver.java
  http-client-core/src/main/java/io/micronaut/http/client/LoadBalancer.java
  http-client-core/src/main/java/io/micronaut/http/client/loadbalance/FixedLoadBalancer.java
  http-client-core/src/main/java/io/micronaut/http/client/loadbalance/LoadBalancerConverters.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyHttpClientFactory.java
  http-client/src/test/groovy/io/micronaut/http/client/services/ManualHttpServiceDefinitionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/SimpleTextWebSocketSpec.groovy
  src/main/docs/guide/appendix/breaks.adoc
  test-suite/src/test/groovy/io/micronaut/docs/http/client/proxy/ProxyRequestSpec.groovy
  websocket/src/main/java/io/micronaut/websocket/WebSocketClient.java
  websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java
Labels: type: improvement

#6527 Bump micronaut-grpc to 3.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6525 Allow specifying additional modules in `@JacksonFeatures`
  http-client/src/test/groovy/io/micronaut/http/client/ClientScopeSpec.groovy
  jackson-databind/src/main/java/io/micronaut/jackson/annotation/JacksonFeatures.java
  jackson-databind/src/main/java/io/micronaut/jackson/codec/JacksonFeatures.java
  jackson-databind/src/main/java/io/micronaut/jackson/databind/JacksonDatabindMapper.java
Labels: type: improvement

#6540 Preserve order for TreeGenerator JSON objects
  jackson-core/src/main/java/io/micronaut/jackson/core/tree/TreeGenerator.java
  jackson-core/src/test/groovy/io/micronaut/jackson/core/tree/TreeGeneratorSpec.groovy
Labels: type: bug

#6369 HTTP2 server push API
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ServerPushSpec.groovy
  http/src/main/java/io/micronaut/http/PushCapableHttpRequest.java
  http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
Labels: type: improvement

#6539 Complete all downstream subscribers in RoutingInBoundHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/ConcurrentFormTransferSpec.groovy
Labels: type: bug

#6542 Upgrade to Micronaut Data 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6531 Support NaN and Infinity for JsonNodeTreeCodec
  jackson-core/src/main/java/io/micronaut/jackson/core/tree/JsonNodeTreeCodec.java
  jackson-core/src/test/groovy/io/micronaut/jackson/core/tree/JsonNodeTreeCodecSpec.groovy
  json-core/src/main/java/io/micronaut/json/JsonStreamConfig.java
Labels: type: bug

#6548 Add a way to access Kotlin coroutine context from an interceptor
  aop/src/main/java/io/micronaut/aop/InterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java
  aop/src/main/java/io/micronaut/aop/kotlin/KotlinInterceptedMethod.java
  aop/src/main/kotlin/io/micronaut/aop/util/DelegatingContextContinuation.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/MyContext.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/MyContextInterceptorAnn.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendInterceptor.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendService.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendServiceInterceptorSpec.kt
Labels: type: enhancement

#6549 Support @JsonFormat
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: improvement

#6529 Make JsonNode converters more robust for different target types
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  jackson-databind/src/test/groovy/io/micronaut/jackson/convert/JsonConverterRegistrarSpec.groovy
  json-core/src/main/java/io/micronaut/json/convert/JsonConverterRegistrar.java
Labels: type: bug

#6410 Enrich object encoding with more generic information
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/AbstractHttpContentProcessor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java
  http/src/main/java/io/micronaut/http/codec/MediaTypeCodec.java
  jackson-databind/src/main/java/io/micronaut/jackson/databind/JacksonDatabindMapper.java
  json-core/src/main/java/io/micronaut/json/JsonMapper.java
  json-core/src/main/java/io/micronaut/json/codec/MapperMediaTypeCodec.java
Labels: type: improvement

#6557 Bump micronaut-micrometer to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6561 Bump micronaut-security to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6567 Fix GraalVM warning about CoroutineHelper
  http-server/src/main/resources/META-INF/native-image/io.micronaut/http-server/native-image.properties
Labels: relates-to: graal

#6558 Fix input file normalization for functional tests
  buildSrc/src/main/groovy/io.micronaut.build.internal.bom-checker.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.functional-test.gradle
  gradle.properties
  inject-groovy/build.gradle
  test-suite/build.gradle
Labels: relates-to: build

#6573 Fix race condition in HandlerPublisher
  http-netty/src/main/java/io/micronaut/http/netty/reactive/HandlerPublisher.java
  http-netty/src/test/groovy/io/micronaut/http/netty/reactive/HandlerPublisherSpec.groovy
Labels: type: bug

#6583 Bump micronaut-kubernetes to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6585 Bump micronaut-micrometer to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6572 Add slf4j-simple as a dependency to inject-java and inject-groovy
  inject-groovy/build.gradle
  inject-java/build.gradle
Labels: type: bug

#6586 Bump micronaut-test to 3.0.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6581 Check for static file resolution before returning route not found
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/StaticResourceController.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/StaticResourceResolutionSpec.groovy
Labels: type: bug

#6584 Set up coroutine context for WebSocket handler invocations
  http-client/src/main/java/io/micronaut/http/client/netty/websocket/NettyWebSocketClientHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server/src/main/java/io/micronaut/http/server/CoroutineHelper.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  test-suite-kotlin/src/test/kotlin/io/micronaut/http/server/WebSocketSuspendTest.kt
Labels: type: bug
