Repository micronaut-projects/micronaut-core, pull requests merged in 2021-08, with the labels that each got.

#5912 Fixes field injection that has both Value/Property and Inject for Java
  inject-groovy/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/property/FieldPropertyInject.java
  inject-java/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
Labels: type: bug

#5915 Fix inconsistent behaviour between remappers and transformers
  inject-java/src/test/groovy/io/micronaut/inject/ast/beans/BeanElementVisitorSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/ast/beans/SecondBeanElementVisitor.java
  inject-java/src/test/groovy/io/micronaut/inject/ast/beans/TestBeanElementVisitor.java
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/BeanElementBuilderSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/MonitoredToo.java
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/TestInterceptorBindingRemapper.java
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/TestInterceptorBindingTransformer.java
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/another/AnotherInterceptorBinding.java
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationRemapper
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
Labels: type: bug

#5922 Bump micronaut-rabbitmq to 3.0.0-RC3
  gradle.properties
Labels: type: dependency-upgrade

#5923 Improve support for primitive arrays in annotation metadata
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValueBuilder.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValueResolver.java
  core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java
  core/src/main/java/io/micronaut/core/util/ArrayUtils.java
  core/src/test/groovy/io/micronaut/core/annotation/AnnotationValueBuilderSpec.groovy
  core/src/test/groovy/io/micronaut/core/util/ArrayUtilsSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/AbstractGroovyElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
  inject/build.gradle
  inject/src/main/java/io/micronaut/context/event/ApplicationEventPublisherFactory.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  inject/src/main/java/io/micronaut/inject/ast/Element.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
Labels: type: improvement

#5926 Support adding stereotypes to annotation from a visitor
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AddStereotypesFromVisitorSpec.groovy
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
Labels: type: enhancement

#5919 Bump micronaut-kubernetes to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5929 Bump micronaut-jackson-xml to 2.3.2
  gradle.properties
Labels: type: dependency-upgrade

#5932 Bump micronaut-security to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5931 Bump micronaut-jackson-xml to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5942 Bump micronaut-openapi to 2.6.1
  gradle.properties
Labels: type: dependency-upgrade

#5944 Bump micronaut-openapi to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5940 Bump micronaut-servlet to 3.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5950 Bump micronaut-flyway to 4.1.0
  gradle.properties
Labels: type: dependency-upgrade

#5952 Bump micronaut-liquibase to 4.0.2
  gradle.properties
Labels: type: dependency-upgrade

#5958 Bump micronaut-views to 3.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5959 Bump micronaut-gcp to 4.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5970 doc: fix broken links in docs
  gradle.properties
  src/main/docs/guide/aop/caching.adoc
  src/main/docs/guide/aop/springAop.adoc
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/cli/commands.adoc
  src/main/docs/guide/cloud/clientSideLoadBalancing/netflixRibbon.adoc
  src/main/docs/guide/cloud/cloudConfiguration.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
  src/main/docs/guide/cloud/distributedTracing.adoc
  src/main/docs/guide/httpClient/clientAnnotation/clientAnnotationStreaming.adoc
  src/main/docs/guide/httpClient/clientAnnotation/netflixHystrix.adoc
  src/main/docs/guide/httpServer/customArgumentBinding.adoc
  src/main/docs/guide/httpServer/errorHandling/exceptionHandler/customExceptionHandler.adoc
  src/main/docs/guide/httpServer/localeResolution.adoc
  src/main/docs/guide/httpServer/routing.adoc
  src/main/docs/guide/httpServer/serverEvents.adoc
  src/main/docs/guide/httpServer/websocket/websocketServer.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/qualifiers.adoc
  src/main/docs/guide/management/buildingEndpoints/endpointAnnotation.adoc
  src/main/docs/guide/management/buildingEndpoints/endpointMethod.adoc
  src/main/docs/guide/management/providedEndpoints.adoc
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
  src/main/docs/guide/management/providedEndpoints/loggersEndpoint.adoc
  tracing/src/main/java/io/micronaut/tracing/instrument/package-info.java
Labels: type: docs

#5966 doc: correct mention to renamed class
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
Labels: type: docs

#5968 doc: RxInfoAggregator is ReactiveInfoAggregator
  src/main/docs/guide/management/providedEndpoints/infoEndpoint.adoc
Labels: type: docs

#5989 Bump micronaut-openapi to 2.6.2
  gradle.properties
Labels: type: dependency-upgrade

#5990 Bump micronaut-openapi to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5983 Bump micronaut-groovy to 3.0.0
  gradle.properties
  validation/src/main/java/io/micronaut/validation/exceptions/ValidationExceptionHandler.java
Labels: type: dependency-upgrade

#5996 Bump micronaut-aws to 2.6.2
  gradle.properties
Labels: type: dependency-upgrade

#5999 Bump micronaut-acme to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6000 Bump micronaut-jackson-xml to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6001 Bump micronaut-kotlin to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6002 Bump micronaut-cache to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6003 Bump micronaut-data to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6005 Bump micronaut-jaxrs to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6006 Bump micronaut-problem-json to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6007 Bump micronaut-mqtt to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6008 Bump micronaut-elasticsearch to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6009 Bump micronaut-rss to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6010 Bump micronaut-graphql to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6012 Bump micronaut-rabbitmq to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6013 Bump micronaut-picocli to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6014 Bump micronaut-test to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6015 Bump micronaut-servlet to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6016 Bump micronaut-multitenancy to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6017 Bump micronaut-nats to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6018 Bump micronaut-jmx to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6019 Bump micronaut-views to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6020 Bump micronaut-discovery-client to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6021 Bump micronaut-neo4j to 5.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6022 Bump micronaut-rxjava2 to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6023 Bump micronaut-redis to 5.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6024 Bump micronaut-security to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6025 Bump micronaut-grpc to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6026 Bump micronaut-rxjava3 to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6027 Bump micronaut-reactor to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6028 Bump micronaut-mongodb to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6030 Bump micronaut-sql to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6029 Bump micronaut-r2dbc to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6032 Bump micronaut-spring to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6031 Bump micronaut-micrometer to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6033 Bump micronaut-oracle-cloud to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6034 Bump micronaut-azure to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6035 Bump micronaut-gcp to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6036 Bump micronaut-kafka to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6037 Bump micronaut-aws to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade

#6038 Bump micronaut-kubernetes to 3.0.0
  gradle.properties
Labels: type: dependency-upgrade
