Repository micronaut-projects/micronaut-core, pull requests merged in 2021-10, with the labels that each got.

#6260 Bump micronaut-data to 3.1.0
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#6257 Bump micronaut-kubernetes to 3.1.0
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement

#6230 Expose more generics information in ClassElement API
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyElementFactory.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyGenericPlaceholderElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyMethodElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyWildcardElement.java
  inject-groovy/src/test/groovy/io/micronaut/ast/groovy/visitor/GroovyReconstructionSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaEnumElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaGenericPlaceholderElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaWildcardElement.java
  inject-java/src/test/groovy/io/micronaut/annotation/processing/visitor/JavaClassElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/annotation/processing/visitor/JavaReconstructionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/ClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/GenericPlaceholderElement.java
  inject/src/main/java/io/micronaut/inject/ast/MethodElement.java
  inject/src/main/java/io/micronaut/inject/ast/ParameterElement.java
  inject/src/main/java/io/micronaut/inject/ast/ReflectClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/ReflectGenericPlaceholderElement.java
  inject/src/main/java/io/micronaut/inject/ast/ReflectTypeElement.java
  inject/src/main/java/io/micronaut/inject/ast/ReflectWildcardElement.java
  inject/src/main/java/io/micronaut/inject/ast/TypedElement.java
  inject/src/main/java/io/micronaut/inject/ast/WildcardElement.java
Labels: type: enhancement

#6262 Bump micronaut-jaxrs to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6268 Introduce an index in immutable sorted maps
  core/src/main/java/io/micronaut/core/annotation/ImmutableSortedStringsArrayMap.java
  core/src/test/groovy/io/micronaut/core/annotation/ImmutableSortedStringsArrayMapTest.groovy
Labels: type: improvement

#6258 Adds a getter for cron expression
  context/src/main/java/io/micronaut/scheduling/cron/CronExpression.java
  context/src/test/groovy/io/micronaut/scheduling/cron/CronExpressionTest.groovy
Labels: hacktoberfest-accepted

#6254 Mark some properties on Resource classes with their correct property names
  http/build.gradle
  http/src/main/java/io/micronaut/http/hateoas/AbstractResource.java
  http/src/main/java/io/micronaut/http/hateoas/JsonError.java
  http/src/main/java/io/micronaut/http/hateoas/Resource.java
Labels: type: improvement

#6279 Bump micronaut-openapi to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6276 Bump micronaut-aws to 3.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
