Repository micronaut-projects/micronaut-core, pull requests merged in 2021-02, with the labels that each got.

#4880 Bump micronaut-maven-plugin to 1.1.5
  gradle.properties
Labels: type: dependency-upgrade

#4892 Bump micronaut-discovery-client to 2.2.3
  gradle.properties
Labels: type: dependency-upgrade

#4905 Bump micronaut-discovery-client to 2.2.4
  gradle.properties
Labels: type: dependency-upgrade

#4921 build: set project version to 2.4.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#4923 ci: setup github branch to 2.4.x
  gradle.properties
Labels: relates-to: build

#4932 Bump micronaut-grpc to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4931 Bump micronaut-kotlin to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4944 Bump micronaut-flyway to 3.4.0
  gradle.properties
Labels: type: dependency-upgrade

#4956 test: avoid bean pollution
  runtime/src/test/groovy/io/micronaut/scheduling/ScheduledFixedRateSpec.groovy
Labels: type: improvement

#4970 Bump micronaut-jaxrs to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#4877 [core] Update common files for branch 2.3.x
  .github/dependabot.yml
  .github/workflows/bintray-publish.yml
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  MAINTAINING.md
  config/checkstyle/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: priority: high, relates-to: build

#4954 Use the latest micronaut-build plugins
  bom-check/build.gradle
  bom/build.gradle
  build.gradle
  parent/build.gradle
  runtime/src/test/groovy/io/micronaut/scheduling/MyJavaTask.java
  runtime/src/test/groovy/io/micronaut/scheduling/ScheduledFixedRateSpec.groovy
Labels: priority: high, relates-to: build

#4980 [core] Update common files for branch 2.3.x
  .github/workflows/publish-snapshot.yml
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#4982 Upgrade to GraalVM 21.0.0.2
  gradle.properties
Labels: type: dependency-upgrade

#4955 Bump micronaut-micrometer to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#4996 Bump micronaut-redis to 3.1.1
  gradle.properties
Labels: type: dependency-upgrade

#4992 Bump micronaut-maven-plugin to 1.1.6
  gradle.properties
Labels: type: dependency-upgrade

#4999 Bump micronaut-redis to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5008 Bump micronaut-kubernetes to 2.3.0
  build.gradle
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#5010 Bump micronaut-oracle-cloud to 1.2.1
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade
