Repository micronaut-projects/micronaut-core, pull requests merged in 2021-04, with the labels that each got.

#5212 Bump micronaut-security to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5205 Bump micronaut-aws to 2.6.0
  gradle.properties
Labels: type: dependency-upgrade

#5216 build: bump up Micronaut Kotlin to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5225 Bump micronaut-azure to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#5226 Bump micronaut-liquibase to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#5237 Bump micronaut-security to 2.4.1
  gradle.properties
Labels: type: dependency-upgrade

#5243 Bump micronaut-liquibase to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5228 Bump micronaut-servlet to 2.1.3
  gradle.properties
Labels: type: dependency-upgrade

#5232 Bump micronaut-elasticsearch to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5263 Bump micronaut-oracle-cloud to 1.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5272 Bump micronaut-maven-plugin to 1.1.8
  gradle.properties
Labels: type: dependency-upgrade

#5280 Bump micronaut-oracle-cloud to 1.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5284 Bump micronaut-micrometer to 3.4.0
  gradle.properties
  inject/src/main/java/io/micronaut/inject/annotation/internal/TimedAnnotationMapper.java
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#5289 build: Micronaut servlet from 2.1.3 to 2.1.4
  gradle.properties
Labels: type: dependency-upgrade

#5293 Bump micronaut-security to 2.3.3
  gradle.properties
Labels: type: dependency-upgrade

#5294 Bump micronaut-security to 2.4.2
  gradle.properties
Labels: type: dependency-upgrade

#5296 Bump micronaut-data to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5295 Bump micronaut-kubernetes to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5300 build: add micronaut-problem-json to bom
  build.gradle
  gradle.properties
Labels: relates-to: build

#5302 Bump micronaut-openapi to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5304 Bump micronaut-data to 2.4.1
  gradle.properties
Labels: type: dependency-upgrade

#5308 Bump micronaut-kafka to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5312 Bump micronaut-liquibase to 3.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5313 Bump micronaut-oracle-cloud to 1.3.2
  gradle.properties
Labels: type: dependency-upgrade

#5314 Bump micronaut-grpc to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5322 Bump micronaut-maven-plugin to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5321 Bump micronaut-oracle-cloud to 1.3.3
  gradle.properties
Labels: type: dependency-upgrade

#5326 Bump micronaut-oracle-cloud to 1.3.4
  gradle.properties
Labels: type: dependency-upgrade

#5334 Bump micronaut-rabbitmq to 2.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5338 Bump micronaut-discovery-client to 2.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5347 Bump micronaut-coherence to 1.0.0.M2
  gradle.properties
Labels: type: dependency-upgrade

#5343 Add support for producing beans from fields
  aop/src/main/java/io/micronaut/aop/chain/DefaultInterceptorRegistry.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectVisitor.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/factory/FactoryBeanFieldSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanfield/FactoryBeanFieldSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
  inject/src/main/java/io/micronaut/context/DefaultFieldConstructorInjectionPoint.java
  inject/src/main/java/io/micronaut/context/annotation/Bean.java
  inject/src/main/java/io/micronaut/context/annotation/Requirements.java
  inject/src/main/java/io/micronaut/context/annotation/Requires.java
  inject/src/main/java/io/micronaut/inject/ast/Element.java
  inject/src/main/java/io/micronaut/inject/ast/FieldElement.java
  inject/src/main/java/io/micronaut/inject/ast/ParameterElement.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/factories.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/factories/VehicleMockSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/Engine.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/VehicleMockSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/inject/typed/V8Engine.kt
  test-suite/src/test/java/io/micronaut/docs/factories/VehicleMockSpec.java
Labels: type: enhancement
