Repository micronaut-projects/micronaut-core, pull requests merged in 2021-07, with the labels that each got.

#5686 Bump micronaut-oracle-cloud to 1.4.0
  gradle.properties
Labels: type: dependency-upgrade

#5689 Bump micronaut-data to 2.4.5
  gradle.properties
Labels: type: dependency-upgrade

#5694 Bump micronaut-data to 2.4.6
  gradle.properties
Labels: type: dependency-upgrade

#5695 Bump micronaut-micrometer to 4.0.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#5699 Bump micronaut-kafka to 4.0.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#5700 Bump micronaut-grpc to 3.0.0.RC1
  gradle.properties
Labels: type: dependency-upgrade

#5709 build: bump up to Gradle 7.1.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#5712 Bump micronaut-coherence to 1.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5673 Bean Import support for JSR 330
  core/src/main/java/io/micronaut/core/reflect/InstantiationUtils.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-java-test/build.gradle
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/beanimport/BeanImportSpec.groovy
  inject-java-test/src/test/java/io/micronaut/annotation/processing/test/ValueConfiguration.java
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaFieldElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject/src/main/java/io/micronaut/context/annotation/Import.java
  inject/src/main/java/io/micronaut/context/visitor/BeanImportHandler.java
  inject/src/main/java/io/micronaut/context/visitor/BeanImportVisitor.java
  inject/src/main/java/io/micronaut/context/visitor/package-info.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/MutableAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/ast/DefaultElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/ElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/beans/BeanElementBuilder.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  settings.gradle
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/beanImport.adoc
  src/main/docs/guide/toc.yml
  test-suite-jakarta-inject-bean-import/build.gradle
  test-suite-jakarta-inject-bean-import/src/test/groovy/io/micronaut/jakartainject/tck/beanimport/BeanImportSpec.groovy
  test-suite-jakarta-inject-bean-import/src/test/java/io/micronaut/jakartainject/tck/beanimport/BeanImportTck.java
Labels: type: enhancement

#5725 Bump micronaut-data to 2.4.7
  gradle.properties
Labels: type: dependency-upgrade

#5727 Bump micronaut-cache to 3.0.0.RC1
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#5731 Bump micronaut-micrometer to 3.4.1
  gradle.properties
Labels: type: dependency-upgrade

#5738 Bump micronaut-sql to 4.0.0-RC1
  build.gradle
  gradle.properties
  test-suite/build.gradle
Labels: type: dependency-upgrade

#5740 Bump micronaut-rabbitmq to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5739 Bump micronaut-oracle-cloud to 1.4.1
  gradle.properties
Labels: type: dependency-upgrade

#5746 Bump micronaut-sql to 4.0.0-RC2
  build.gradle
  gradle.properties
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#5747 Bump micronaut-acme to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5745 doc: @EventListener as Inherited in breaks' table
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: docs

#5752 Bump micronaut-multitenancy to 4.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5754 build: add new rxjava2 modules
  build.gradle
  gradle.properties
Labels: relates-to: build

#5761 Bump micronaut-groovy to 3.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5764 Bump micronaut-sql to 4.0.0-RC3
  gradle.properties
Labels: type: dependency-upgrade

#5766 Bump micronaut-r2dbc to 2.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5762 Bump micronaut-nats to 3.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5779 replace deprecated Jackson PropertyNamingStrategy
  runtime/src/main/java/io/micronaut/jackson/JacksonConfiguration.java
  runtime/src/main/java/io/micronaut/jackson/convert/JacksonConverterRegistrar.java
  runtime/src/test/groovy/io/micronaut/jackson/JacksonSetupSpec.groovy
  runtime/src/test/groovy/io/micronaut/jackson/bind/CharSequencePropertyNamingStrategyConverterSpec.groovy
  runtime/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: improvement

#5785 Bump micronaut-jmx to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5788 Bump micronaut-openapi to 2.6.0
  gradle.properties
Labels: type: dependency-upgrade

#5800 Bump micronaut-security to 3.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5799 Bump micronaut-liquibase to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5802 Bump micronaut-views to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5805 Bump micronaut-rxjava2 to 1.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5804 Bump micronaut-reactor to 2.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5803 Bump micronaut-discovery-client to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5808 Bump micronaut-flyway to 4.0.0
  gradle.properties
Labels: type: dependency-upgrade

#5807 Bump micronaut-kotlin to 3.0.0-RC1
  gradle.properties
  inject-java/src/test/java/org/atinject/jakartatck/auto/Convertible.java
  test-suite-javax-inject/src/test/java/org/atinject/javaxtck/auto/Convertible.java
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/Convertible.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/DriversSeat.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/Engine.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/Seat.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/Tck.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/Tire.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/V8Engine.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/accessories/Cupholder.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/jakartatck/auto/accessories/SpareTire.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/javaxtck/auto/Convertible.kt
  test-suite-kotlin/src/test/kotlin/org/atinject/javaxtck/auto/Tck.kt
Labels: type: dependency-upgrade

#5812 Bump micronaut-oracle-cloud to 1.4.2
  gradle.properties
Labels: type: dependency-upgrade

#5813 Bump micronaut-rabbitmq to 3.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5814 Bump micronaut-groovy to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5815 Bump micronaut-mqtt to 2.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5816 Bump micronaut-graphql to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5817 Bump micronaut-problem-json to 2.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5818 Bump micronaut-aws to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5820 Bump micronaut-micrometer to 4.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5819 Bump micronaut-rss to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5825 Bump micronaut-rss to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5826 Bump micronaut-rxjava3 to 2.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5833 Bump micronaut-picocli to 4.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5834 Bump micronaut-spring to 3.1.1
  gradle.properties
Labels: type: dependency-upgrade

#5837 Bump micronaut-servlet to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5840 Bump micronaut-cache to 3.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5836 Bump micronaut-azure to 2.3.0
  gradle.properties
Labels: type: dependency-upgrade

#5841 Bump micronaut-spring to 4.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5843 Bump micronaut-nats to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5844 Bump micronaut-groovy to 3.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5845 Bump micronaut-sql to 4.0.0-RC4
  gradle.properties
Labels: type: dependency-upgrade

#5846 Bump micronaut-spring to 4.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5849 Bump micronaut-azure to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5854 Bump micronaut-maven-plugin to 2.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5853 Bump micronaut-jaxrs to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5857 Bump micronaut-jackson-xml to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5859 Bump micronaut-oracle-cloud to 1.4.3
  gradle.properties
Labels: type: dependency-upgrade

#5858 Bump micronaut-maven-plugin to 3.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5862 Bump micronaut-redis to 5.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5868 Bump micronaut-picocli to 4.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5872 Bump micronaut-test to 3.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5871 Bump micronaut-jms to 2.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5866 Bump micronaut-elasticsearch to 2.3.1
  gradle.properties
Labels: type: dependency-upgrade

#5865 Bump micronaut-oracle-cloud to 2.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5867 Bump micronaut-elasticsearch to 3.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#5880 Bump micronaut-r2dbc to 2.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5879 Bump micronaut-data to 2.5.0
  gradle.properties
Labels: type: dependency-upgrade

#5886 Bump micronaut-discovery-client to 3.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5887 Bump micronaut-mongodb to 4.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade

#5889 Bump micronaut-neo4j to 5.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5890 Bump micronaut-kafka to 4.0.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#5892 Bump micronaut-gcp to 4.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5896 Bump micronaut-flyway to 4.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5897 Bump micronaut-liquibase to 4.0.1
  gradle.properties
Labels: type: dependency-upgrade

#5898 Bump micronaut-data to 3.0.0-RC1
  gradle.properties
Labels: type: dependency-upgrade

#5899 Allow access to PackageElement from ClassElement
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyPackageElement.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaPackageElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/ClassElement.java
  inject/src/main/java/io/micronaut/inject/ast/PackageElement.java
  inject/src/main/java/io/micronaut/inject/ast/SimplePackageElement.java
Labels: type: improvement
