Repository micronaut-projects/micronaut-core, pull requests merged in 2022-09, with the labels that each got.

#7930 Bump micronaut-serialization to 1.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7929 Bump micronaut-multitenancy to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7923 Bump micronaut-aws to 3.7.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7936 Fix buffer leak on response encode error
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  json-core/src/main/java/io/micronaut/json/codec/MapperMediaTypeCodec.java
Labels: type: bug

#7937 Bump micronaut-serialization to 1.3.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7915 Bump micronaut-azure to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7938 build: Micronaut Problem 2.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7941 Bump micronaut-aws to 3.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7942 fix(deps): update dependency org.yaml:snakeyaml to v1.31 (#7940)
  gradle/libs.versions.toml
Labels: type: dependency-upgrade, relates-to: security

#7953 Bump micronaut-tracing to 4.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7950 Bump micronaut-spring to 4.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7954 Bump micronaut-tracing to 4.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7957 Bump micronaut-security to 3.7.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7956 Bump micronaut-security to 3.6.5
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7895 Bump micronaut-micrometer to 4.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7966 Add Object Storage to the BOM and to the what's new section of the docs.
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#7962 fix: kaptKoltin exception with micronaut-inject processor
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
  inject/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataSpec.groovy
Labels: type: bug

#7933 feature: Allow stopping netty without stopping the application context
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/NettyStopSpec.groovy
  inject/src/main/java/io/micronaut/context/ApplicationContextLifeCycle.java
  messaging/src/main/java/io/micronaut/messaging/MessagingApplication.java
Labels: relates-to: CRaC

#7977 Resolve issues with Missing Local Resources Check for the `docs` task
  README.md
  gradle.properties
  src/main/docs/guide/appendix/architecture/aopArch.adoc
  src/main/docs/guide/appendix/architecture/containerArch.adoc
  src/main/docs/guide/appendix/architecture/httpServerArch.adoc
  src/main/docs/guide/appendix/architecture/introspectionArch.adoc
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationVault.adoc
  src/main/docs/guide/config/bootstrap.adoc
  src/main/docs/guide/configurations/dataAccess/mongoSupport.adoc
  src/main/docs/guide/httpClient/clientAnnotation/clientParameters.adoc
  src/main/docs/guide/httpServer/errorHandling/exceptionHandler/builtInExceptionHandlers.adoc
  src/main/docs/guide/httpServer/serverConfiguration/nettyClientPipeline.adoc
  src/main/docs/guide/httpServer/serverConfiguration/secondaryServers.adoc
  src/main/docs/guide/httpServer/websocket/websocketServer.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/qualifiers.adoc
  src/main/docs/guide/languageSupport/graal/graalFAQ.adoc
  src/main/docs/guide/languageSupport/java/ide.adoc
Labels: type: docs

#7963 Allow static executable methods, support executing private fields + methods
  core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
  core/src/main/java/io/micronaut/core/type/Executable.java
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/aop/itfce/InterfaceTypeLevel.java
  inject-java/src/test/groovy/io/micronaut/aop/itfce/InterfaceTypeLevelSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/executable/BookController.java
  inject-java/src/test/groovy/io/micronaut/inject/executable/ExecutableSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanfield/FactoryBeanFieldSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanmethod/FactoryBeanMethodSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/MemberElement.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
Labels: type: enhancement

#7991 Bump micronaut-spring to 4.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7997 build: Add CRaC module to BOM
  gradle/libs.versions.toml
Labels: relates-to: build

#8002 Bump micronaut-jms to 2.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7998 Bump micronaut-groovy to 3.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8006 Bump micronaut-hibernate-validator to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8007 Bump micronaut-hibernate-validator to 3.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8003 Bump micronaut-security to 3.8.0
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7990 Bump micronaut-oracle-cloud to 2.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8005 Make client ssl inner configuration properties bootstrap context compatible
  http/src/main/java/io/micronaut/http/ssl/ClientSslConfiguration.java
Labels: type: improvement

#8008 build: Update BOM to latest releases
  gradle/libs.versions.toml
Labels: relates-to: build

#8009 Bump micronaut-openapi to 4.5.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8015 build: bump up Micronaut AWS to 3.9.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8019 Bump micronaut-aws to 3.9.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8018 Bump micronaut-views to 3.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8024 Bump micronaut-test to 3.6.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8020 fix runtime beans using interfaces or abstract classes
  inject-java/src/test/groovy/io/micronaut/inject/beans/RuntimeBeanDefinitionSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultRuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/RuntimeBeanDefinition.java
Labels: type: bug

#8016 add an option to completely disable default property source loading
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/main/java/io/micronaut/inject/qualifiers/AnnotationMetadataQualifier.java
  inject/src/test/groovy/io/micronaut/context/ApplicationContextBuilderSpec.groovy
  src/main/docs/guide/config/propertySource.adoc
Labels: type: enhancement

#8035 Bump micronaut-gcp to 4.5.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8039 Allow matching `@Produces(ALL)` for ambiguous routes
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ContentNegotiationSpec.groovy
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: bug

#8044 Bump micronaut-data to 3.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8043 Bump micronaut-micrometer to 4.6.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8040 Bump micronaut-tracing to 4.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8036 Bump micronaut-groovy to 3.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8028 Fix incorrect getPropertiesFromGettersAndSetters groovy visitor for interfaces
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
Labels: type: bug

#8046 Bump micronaut-mongodb to 4.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8048 Bump micronaut-gcp to 4.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8050 Bump micronaut-aws to 3.7.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8053 Bump micronaut-test to 3.6.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8055 Bump micronaut-openapi to 4.5.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8054 Stop repackaging Caffeine
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-library.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/japicmp/RemovedPackages.groovy
  core/build.gradle
  core/src/main/java/io/micronaut/core/graal/CacheSubstitutions.java
  session/build.gradle
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: improvement

#8069 Bump micronaut-object-storage to 1.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8060 build: Micronaut Crac to 1.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8088 Bump micronaut-sql to 4.7.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8087 Bump micronaut-sql to 4.6.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6842 One channel per HTTP2 stream
  http-netty/src/main/java/io/micronaut/http/netty/AbstractNettyHttpRequest.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/StreamingInboundHttp2ToHttpAdapter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyServerCustomizer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/FileTypeHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/stream/NettyStreamedCustomizableResponseType.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/AccessLogSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ConcurrentStreamSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy
Labels: type: improvement, status: next major version

#8093 Bump micronaut-sql to 4.6.6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8095 Bump micronaut-sql to 4.7.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8061 Make SnakeYAML and javax.annotation optional
  inject-groovy/build.gradle
  inject-groovy/src/test/groovy/io/micronaut/aop/compile/LifeCycleWithProxySpec.groovy
  inject-java/build.gradle
  inject/build.gradle
  jackson-databind/build.gradle
  runtime/build.gradle
  runtime/src/main/java/io/micronaut/reactive/reactor/instrument/ReactorInstrumentation.java
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/config.adoc
  test-suite-javax-inject/build.gradle
Labels: type: improvement, type: breaking
