Repository micronaut-projects/micronaut-core, pull requests merged in 2022-12, with the labels that each got.

#8447 Eliminate unused proxy targets and simplify resolution
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-groovy/src/test/groovy/io/micronaut/aop/introduction/with_around/IntroductionWithAroundOnConcreteClassSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/aop/introduction/with_around/ProxyAdviceInterceptor.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/with_around/IntroductionWithAroundOnConcreteClassSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/with_around/ProxyAdviceInterceptor.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/ContextScopedInterceptedBean.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/InterceptedBean.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/ParallelBean.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinitionReference.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/ProxyTarget.java
  inject/src/main/java/io/micronaut/inject/BeanDefinitionReference.java
Labels: type: improvement

#8451 Fix bug in introspections when properties are of mixed types
  core-processor/src/main/java/io/micronaut/inject/ast/BeanPropertiesQuery.java
  core-processor/src/main/java/io/micronaut/inject/ast/ClassElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/PrimitiveElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/PropertyElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/processing/ConfigurationReaderBeanElementCreator.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesParseSpec.groovy
Labels: type: bug

#8457 Don't include write only properties in serialization
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/testclasses/HTTPCheck.java
Labels: type: bug

#8459 Fix bug with custom conditions and EachBean definitions
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/EachBeanConditionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/XClient.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/XCondition.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/XConfig.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/XConfigMany.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/condition/XConfigOne.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
Labels: type: bug

#8467 Fix incorrect dependency substitution
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/ext/DefaultMicronautCoreExtension.java
Labels: type: bug, relates-to: build

#8470 Add reactor-test as a managed dependency
  gradle/libs.versions.toml
Labels: relates-to: build

#8281 Remove the session module, and add micronaut-session
  gradle.properties
  gradle/libs.versions.toml
  session/build.gradle
  session/src/main/java/io/micronaut/session/DefaultSessionIdGenerator.java
  session/src/main/java/io/micronaut/session/InMemorySession.java
  session/src/main/java/io/micronaut/session/InMemorySessionStore.java
  session/src/main/java/io/micronaut/session/Session.java
  session/src/main/java/io/micronaut/session/SessionConfiguration.java
  session/src/main/java/io/micronaut/session/SessionIdGenerator.java
  session/src/main/java/io/micronaut/session/SessionSettings.java
  session/src/main/java/io/micronaut/session/SessionStore.java
  session/src/main/java/io/micronaut/session/annotation/SessionValue.java
  session/src/main/java/io/micronaut/session/annotation/package-info.java
  session/src/main/java/io/micronaut/session/binder/OptionalSessionArgumentBinder.java
  session/src/main/java/io/micronaut/session/binder/OptionalSessionValueArgumentBinder.java
  session/src/main/java/io/micronaut/session/binder/SessionArgumentBinder.java
  session/src/main/java/io/micronaut/session/binder/SessionValueArgumentBinder.java
  session/src/main/java/io/micronaut/session/binder/package-info.java
  session/src/main/java/io/micronaut/session/event/AbstractSessionEvent.java
  session/src/main/java/io/micronaut/session/event/SessionCreatedEvent.java
  session/src/main/java/io/micronaut/session/event/SessionDeletedEvent.java
  session/src/main/java/io/micronaut/session/event/SessionDestroyedEvent.java
  session/src/main/java/io/micronaut/session/event/SessionExpiredEvent.java
  session/src/main/java/io/micronaut/session/event/package-info.java
  session/src/main/java/io/micronaut/session/http/CookieHttpSessionIdGenerator.java
  session/src/main/java/io/micronaut/session/http/CookieHttpSessionStrategy.java
  session/src/main/java/io/micronaut/session/http/HeadersHttpSessionIdStrategy.java
  session/src/main/java/io/micronaut/session/http/HttpSessionConfiguration.java
  session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java
  session/src/main/java/io/micronaut/session/http/HttpSessionIdEncoder.java
  session/src/main/java/io/micronaut/session/http/HttpSessionIdResolver.java
  session/src/main/java/io/micronaut/session/http/HttpSessionIdStrategy.java
  session/src/main/java/io/micronaut/session/http/SessionForRequest.java
  session/src/main/java/io/micronaut/session/http/SessionLocaleResolver.java
  session/src/main/java/io/micronaut/session/http/SessionLogElement.java
  session/src/main/java/io/micronaut/session/http/SessionLogElementBuilder.java
  session/src/main/java/io/micronaut/session/http/package-info.java
  session/src/main/java/io/micronaut/session/package-info.java
  session/src/main/java/io/micronaut/session/websocket/SessionWebSocketEventListener.java
  session/src/main/java/io/micronaut/session/websocket/package-info.java
  session/src/main/resources/META-INF/services/io.micronaut.http.server.netty.handler.accesslog.element.LogElementBuilder
  session/src/test/groovy/io/micronaut/session/InMemorySessionStoreSpec.groovy
  session/src/test/groovy/io/micronaut/session/docs/Cart.java
  session/src/test/groovy/io/micronaut/session/docs/ShoppingController.java
  session/src/test/groovy/io/micronaut/session/docs/ShoppingControllerSpec.groovy
  session/src/test/groovy/io/micronaut/session/http/CookieHttpSessionStrategySpec.groovy
  session/src/test/groovy/io/micronaut/session/http/HttpSessionConfigurationSpec.groovy
  session/src/test/groovy/io/micronaut/session/http/SessionBindingSpec.groovy
  session/src/test/groovy/io/micronaut/session/http/SessionCreationSpec.groovy
  session/src/test/groovy/io/micronaut/session/http/SessionLocaleResolverSpec.groovy
  session/src/test/groovy/io/micronaut/session/http/WebSocketSessionSpec.groovy
  session/src/test/resources/logback.xml
  settings.gradle
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/httpServer/sessions.adoc
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
Labels: type: breaking

#8469 Add tests and refine behaviour of registerSingleton
  inject-groovy/src/test/groovy/io/micronaut/inject/constructor/ConstructorFactorySpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/field/FieldArrayFactorySpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/field/FieldFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/constructor/factoryinjection/ConstructorFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/context/RegisterSingletonSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/field/arrayfactoryinjection/FieldArrayFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/field/factoryinjection/FieldFactorySpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultRuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/RuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/SingletonScope.java
  runtime/src/test/groovy/io/micronaut/runtime/executor/ExecutorServiceConfigSpec.groovy
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: improvement

#8473 test: refactor CorsFilterSpec as a black box
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
Labels: type: improvement

#8485 Allow context annotations at build time
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
Labels: relates-to: graal

#8487 log: remove failed from healthStatus logging
  management/src/main/java/io/micronaut/management/health/monitor/HealthMonitorTask.java
Labels: type: improvement

#8484 fix configuration inheritance path calculation
  core-processor/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/configuration/ConfigurationUtils.java
  http-server-netty/build.gradle
  http-server/src/main/java/io/micronaut/http/server/codec/TextStreamCodec.java
  inject-java/build.gradle
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesParseSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/annotation/ConfigurationReader.java
Labels: type: bug

#8488 Fix NonUniqueBeanException when using FunctionInitializer
  function/src/main/java/io/micronaut/function/executor/FunctionInitializer.java
  function/src/test/groovy/io/micronaut/function/executor/FunctionInitializerSpec.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#8481 Bump micronaut-data to 3.9.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8238 Ensure Logback is refreshed before application starts
  management/src/main/java/io/micronaut/management/endpoint/loggers/impl/LogbackLoggingSystem.java
  runtime/src/main/java/io/micronaut/logging/LoggingSystem.java
  runtime/src/main/java/io/micronaut/logging/LoggingSystemException.java
  runtime/src/main/java/io/micronaut/logging/PropertiesLoggingLevelsConfigurer.java
  runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
  runtime/src/main/resources/META-INF/native-image/io.micronaut/micronaut-runtime/reflect-config.json
  runtime/src/test/groovy/io/micronaut/logging/LogbackLogLevelConfigurerSpec.groovy
  runtime/src/test/resources/logback-env-test.xml
Labels: type: improvement

#8497 Update Test Resources to 1.2.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8091 ci: use temurin, provenance, Gradle 7.6 build scan step
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#8495 Bump micronaut-openapi to 4.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8482 Update upgrade documentation
  src/main/docs/guide/introduction/upgrading.adoc
Labels: type: docs

#8501 Bump micronaut-maven-plugin to 3.5.2
  gradle.properties
Labels: type: dependency-upgrade

#8507 Bump micronaut-data to 3.9.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8505 Bump micronaut-aws to 3.10.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8502 build: bump native-maven-plugin to 0.9.19
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8512 Bump micronaut-security to 3.9.0
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8514 Bump micronaut-reactor to 2.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8509 build: bump up Reactor to 3.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8423 Update deployingApp.adoc to add jar version
  src/main/docs/guide/quickStart/deployingApp.adoc
Labels: type: docs

#8506 ci: github token for GraalVM action junit-report to 3.7.0
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#8518 Bump micronaut-azure to 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8519 build: update netty from 4.1.84 to 4.1.86.Final
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8401 Bump micronaut-oracle-cloud to 2.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8129 Bump micronaut-groovy to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8523 Bump micronaut-gcp to 4.7.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8525 Bump micronaut-serialization to 1.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8526 build: Micronaut Problem JSON 2.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8527 Bump micronaut-gcp to 4.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8528 build: update crac, grpc, micrometer and liquibase
  .github/workflows/graalvm.yml
  gradle/libs.versions.toml
  settings.gradle
Labels: type: dependency-upgrade

#8531 Bump micronaut-spring to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8534 Bump micronaut-grpc to 3.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8541 fix: graal error for private @Property
  runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
  runtime/src/main/java/io/micronaut/retry/annotation/CircuitBreaker.java
Labels: type: bug, relates-to: graal

#8542 fix: graal error for private @Property
  management/src/main/java/io/micronaut/management/endpoint/loggers/impl/LogbackLoggingSystem.java
  runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
Labels: type: bug, relates-to: graal

#8543 Bump micronaut-aws to 3.10.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8544 Bump micronaut-aws to 3.10.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8545 Bump micronaut-aws to 3.10.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8546 Bump micronaut-aws to 3.10.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
