Repository micronaut-projects/micronaut-core, pull requests merged in 2022-07, with the labels that each got.

#7616 Bump micronaut-spring to 4.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7632 Bump micronaut-sql to 4.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7646 Bump micronaut-neo4j to 5.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7660 Bump micronaut-rss to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7665 Bump micronaut-kafka to 4.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7610 Clarify that `endpoints.all.path` configuration property needs to end with a '/' (it fails otherwise).
  management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java
  src/main/docs/guide/management/buildingEndpoints/endpointConfiguration.adoc
Labels: type: docs

#7670 Bump micronaut-sql to 4.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7668 Bump micronaut-oracle-cloud to 2.1.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7690 Temporarially stop running japiCmp
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-library.gradle
Labels: relates-to: build

#7696 Bump micronaut-maven-plugin to 3.4.0-RC2
  gradle.properties
Labels: type: dependency-upgrade

#7700 Bump micronaut-views to 3.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7611 Add excludeServiceId to client filter definitions
  http-client-core/src/main/java/io/micronaut/http/client/filter/DefaultHttpClientFilterResolver.java
  http-client/src/test/groovy/io/micronaut/http/client/aop/ClientFilterSpec.groovy
  http/src/main/java/io/micronaut/http/annotation/Filter.java
Labels: type: enhancement

#7709 build: Update MicroStream version to v1.0.0
  gradle/libs.versions.toml
Labels: relates-to: build

#7707 Bump micronaut-openapi to 4.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7714 Bump micronaut-sql to 4.6.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7713 Bump micronaut-serialization to 1.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7688 Fix IOUtils support for weird file names
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/test/groovy/io/micronaut/core/io/IOUtilsSpec.groovy
Labels: type: bug

#7678 ci: github actions test graalvm latest and test
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#7733 Bump micronaut-maven-plugin to 3.4.0-RC3
  gradle.properties
Labels: type: dependency-upgrade

#7734 [core] Update common files for branch 3.5.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#7731 Bump micronaut-security to 3.6.2
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7729 Add managed-spring dependency and springboot version back for 3.4 compat
  gradle/libs.versions.toml
Labels: relates-to: build

#7743 [core] Update common files for branch 3.5.x
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#7741 Bump micronaut-coherence to 3.5.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7634 build: Add OpenAPI BOM
  gradle/libs.versions.toml
Labels: relates-to: build

#7747 Bump micronaut-aws to 3.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7662 Add javadoc / groovydoc support to read any element documentation
  config/accepted-api-changes.json
  inject-groovy/build.gradle
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/AbstractGroovyElement.java
  inject-groovy/src/test/groovy/io/micronaut/ast/groovy/visitor/GroovyDocumentationSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/DocumentationSpec.groovy
Labels: type: improvement

#7750 Fix producing beans from methods that return interfaces
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/BeanElementBuilderFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beanbuilder/TestBeanProducer.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
Labels: type: bug

#7752 Bump micronaut-maven-plugin to 3.4.0
  gradle.properties
Labels: type: dependency-upgrade

#7753 Bump micronaut-kafka to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7754 build: Micronaut GCP to 4.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7645 Bump micronaut-neo4j to 5.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7643 Bump micronaut-reactor to 2.2.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7659 Bump micronaut-rss to 3.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7221 Bump micronaut-openapi to 4.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7755 build: Micronaut GCP to 4.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7751 Fix request scope leak
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/RequestCertificateSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#7756 Bump micronaut-sql to 4.6.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7759 fix: fix request scope leak
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/RequestCertificateSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#7762 build: bump up managed-micronaut-data to 3.6.0
  gradle/libs.versions.toml
Labels: dependency-upgrade

#7760 build: bump up managed-micronaut-aws to 3.6.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7761 Bump micronaut-cassandra to 5.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7764 build: managed-micronaut-reactor to 2.3.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7766 build: managed-micronaut-rxjava2 to 1.2.2
  gradle/libs.versions.toml
Labels: dependency-upgrade

#7768 build: managed-micronaut-micrometer to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7609 Save service id alongside http client exceptions
  http-client-core/src/main/java/io/micronaut/http/client/HttpClient.java
  http-client-core/src/main/java/io/micronaut/http/client/exceptions/HttpClientException.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/test/groovy/io/micronaut/http/client/ClientIntroductionAdviceSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/MaxResponseSizeSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/ServerErrorSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/bind/ClientBindSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/sse/ServerSentEventSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/ErrorResponseSpec.groovy
Labels: type: improvement

#7770 Bump micronaut-openapi to 4.4.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7771 build: managed-micronaut-data = "3.7.0"
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
