Repository micronaut-projects/micronaut-core, pull requests merged in 2022-05, with the labels that each got.

#7271 [core] Update common files for branch 3.4.x
  .github/renovate.json
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  MAINTAINING.md
Labels: relates-to: build

#7299 [core] Update common files for branch 3.4.x
  .github/dependabot.yml
Labels: relates-to: build

#7303 [core] Update common files for branch 3.4.x
  .github/release-drafter.yml
Labels: relates-to: build

#7243 Bump micronaut-views to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7241 Bump micronaut-flyway to 5.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7310 Bump micronaut-cache to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7311 Bump micronaut-cache to 3.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7198 Bump micronaut-coherence to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7250 Bump micronaut-aws to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7277 Bump micronaut-liquibase to 5.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7338 Downgrade Failsafe Maven Plugin to 2.22.2
  parent/build.gradle
Labels: priority: high

#7305 Fix proxy with qualifiers and refactor qualifiers code
  inject-groovy/src/test/groovy/io/micronaut/aop/scope/qualified/QualifiedScopeProxySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanfield/FactoryBeanFieldSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanmethod/FactoryBeanMethodSpec.groovy
  inject/src/main/java/io/micronaut/inject/qualifiers/AnnotationMetadataQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/AnnotationQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/AnnotationStereotypeQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/NameQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/NamedAnnotationStereotypeQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/QualifierUtils.java
Labels: type: improvement

#7315 Repeatable annotations should be included when cloning annotation metadata
  inject-java/src/test/groovy/io/micronaut/aop/introduction/repeatable/IntroducedWithRepeatableAnnotationSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/repeatable/MyRepoVisitor.java
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/MutableAnnotationMetadata.java
Labels: type: bug

#7267 Bump micronaut-coherence to 3.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7345 Remove mongo dependency
  gradle/libs.versions.toml
  inject-java/build.gradle
Labels: relates-to: build

#7352 ci: mikepenz/action-junit-report@v3.0.3 no dependencyUpdates
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#7353 Fix service loading on GraalVM 22.1
  core/src/main/java/io/micronaut/core/io/service/SoftServiceLoader.java
Labels: relates-to: graal

#7255 fix: apply injection point qualifier on BeanProvider's get call
  inject-java/src/test/groovy/io/micronaut/inject/provider/BeanProviderSpec.groovy
  inject/src/main/java/io/micronaut/inject/provider/BeanProviderDefinition.java
Labels: type: bug

#7359 Bump micronaut-mongodb to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7364 Bump micronaut-sql to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7351 Bump micronaut-test to 3.2.0
  aop/src/main/java/io/micronaut/aop/kotlin/KotlinInterceptedMethod.java
  core/src/main/java/io/micronaut/core/graal/ServiceLoaderInitialization.java
  gradle/libs.versions.toml
  http-client/src/test/groovy/io/micronaut/http/client/SslSpec.groovy
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/HttpPipeliningSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/MaxRequestSizeSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/AccessLogSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/H2cSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ServerPushSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/Http2StaticResourceCacheSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ssl/SslServerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/BroadcasterSpec.groovy
  http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
  inject-java/src/test/groovy/io/micronaut/inject/lifecycle/proxybeanwithpredestroy/CustomScopeScope.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/visitor/ContextConfigurerVisitor.java
  inject/src/main/java/io/micronaut/inject/annotation/MutableAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/ast/SimpleClassElement.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/client/bind/annotation/MetadataClientArgumentBinder.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/client/bind/method/NameAuthorizationBinder.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/client/bind/method/NameAuthorizationBinder.kt
  test-suite/src/test/java/io/micronaut/docs/http/client/bind/annotation/MetadataClientArgumentBinder.java
  test-suite/src/test/java/io/micronaut/docs/http/client/bind/method/NameAuthorizationBinder.java
  test-suite/src/test/java/io/micronaut/docs/ioc/beans/Manufacturer.java
Labels: type: dependency-upgrade

#7363 Bump micronaut-oracle-cloud to 2.1.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7366 Bump micronaut-sql to 4.2.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7272 Refactor DefaultHttpClient
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/ForwardingSubscriber.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyFuturePublisher.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyPromiseSubscriber.java
  http-client/src/main/java/io/micronaut/http/client/netty/SimpleChannelInboundHandlerInstrumented.java
Labels: type: improvement

#7394 Bump micronaut-data to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7397 ci: GitHub actions files sync
  .github/release.yml
  .github/renovate.json
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#7391 Recognize `jakarta.persistence` entities as introspected classes
  inject/src/main/java/io/micronaut/inject/beans/visitor/jakarta/persistence/JakartaEntityIntrospectedAnnotationMapper.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/jakarta/persistence/JakartaMappedSuperClassIntrospectionMapper.java
  inject/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
Labels: type: enhancement

#7398 Bump micronaut-jaxrs to 3.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7399 Initialize reflection config at build time
  core/src/main/java/io/micronaut/core/graal/ServiceLoaderInitialization.java
Labels: relates-to: graal

#7400 Use the BOM for jaxrs
  gradle/libs.versions.toml
Labels: relates-to: build

#7408 build: micronaut data to 3.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7411 build: Switch to using versions from boms, instead of custom versions
  gradle/libs.versions.toml
  http-server-netty/build.gradle
  inject-java/build.gradle
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/DestroyFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/nullreturn/NullReturnFactorySpec.groovy
  management/build.gradle
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
Labels: relates-to: build

#7410 ci: GitHub actions release.yml
  .github/release.yml
Labels: relates-to: build

#7412 Bump micronaut-serialization to 1.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7414 Bump micronaut-grpc to 3.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7417 build: bump up acme to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7413 Bump micronaut-picocli to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7416 build: micronaut mqtt 2.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7418 Bump micronaut-picocli to 4.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7405 `@Any` factories should be able to react to the qualifier used for the bean
  inject-java/src/test/groovy/io/micronaut/inject/any/qualifier/AnyQualifierSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/any/qualifier/MyAnyFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/any/qualifier/MyCustomBean.java
  inject-java/src/test/groovy/io/micronaut/inject/any/qualifier/MyCustomBean2.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/SingletonScope.java
Labels: type: improvement

#7278 Intercept suspend functions correctly
  aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java
  aop/src/main/kotlin/io/micronaut/aop/util/KotlinInterceptedMethodHelper.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/annotation/processing/SuspendFunctionInterceptorSpec.kt
Labels: type: enhancement, type: improvement

#7300 More powerful listener config for HTTP server, domain socket support
  config/accepted-api-changes.json
  gradle/libs.versions.toml
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EpollEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NioEventLoopGroupFactory.java
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/ListenerConfigurationSpec.groovy
  src/main/docs/guide/httpServer/serverConfiguration/listener.adoc
  src/main/docs/guide/toc.yml
Labels: type: improvement

#7265 feature: Support validation groups with `@Validated`
  src/main/docs/guide/httpServer/datavalidation/validationGroups.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/datavalidation/groups/Email.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/datavalidation/groups/EmailController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/datavalidation/groups/EmailControllerSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/datavalidation/groups/FinalValidation.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/datavalidation/groups/Email.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/datavalidation/groups/EmailController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/datavalidation/groups/EmailControllerSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/datavalidation/groups/FinalValidation.kt
  test-suite/src/test/java/io/micronaut/docs/datavalidation/groups/Email.java
  test-suite/src/test/java/io/micronaut/docs/datavalidation/groups/EmailController.java
  test-suite/src/test/java/io/micronaut/docs/datavalidation/groups/EmailControllerSpec.java
  test-suite/src/test/java/io/micronaut/docs/datavalidation/groups/FinalValidation.java
  validation/src/main/java/io/micronaut/validation/Validated.java
  validation/src/main/java/io/micronaut/validation/ValidatingInterceptor.java
  validation/src/test/groovy/io/micronaut/validation/validator/pojo/PojoBodyParameterSpec.groovy
Labels: type: enhancement

#7419 build: Micronaut AWS 3.5.0
  gradle/libs.versions.toml
Labels: relates-to: build

#7274 fix: @Replaces with qualifier doesn't work (fix #7261)
  config/accepted-api-changes.json
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/E2Replacement.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/E3.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G1Qualifier.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G1QualifierReplacement.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G2Qualifier.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G2QualifierReplacement.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/G3Qualifier.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/ReplacesSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/qualifier/One.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/qualifier/Three.java
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/qualifier/Two.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/annotation/Replaces.java
  test-suite/src/test/java/io/micronaut/docs/replaces/ReplacesTest.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/One.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/Two.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceClientReplaceQualifiers.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceReplaceQualifiers.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceReplaceQualifiersImplOne.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceReplaceQualifiersImplOneReplacement.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceReplaceQualifiersImplTwo.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/annotations/beans/SomeInterfaceReplaceQualifiersImplTwoReplacement.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceClientReplaceNamed.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceReplaceNamed.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceReplaceNamedImplOne.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceReplaceNamedImplOneReplacement.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceReplaceNamedImplTwo.java
  test-suite/src/test/java/io/micronaut/docs/replaces/qualifiers/named/beans/SomeInterfaceReplaceNamedImplTwoReplacement.java
Labels: type: improvement

#7420 Extract the picocli version from the pico bom
  parent/build.gradle
Labels: relates-to: build

#7423 Switch to string based dependencies for version lookup
  buildSrc/src/main/groovy/io/micronaut/build/internal/WriteMicronautVersionInfoTask.java
  parent/build.gradle
Labels: relates-to: build

#7426 build: Add microstream bom to catalog
  gradle/libs.versions.toml
Labels: relates-to: build

#7473 Bump micronaut-security to 3.5.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7475 Bump micronaut-micrometer to 4.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7476 Bump micronaut-openapi to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7479 ci: graal 22.1.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#7481 Correctly inject proxy for refreshable beans with qualifiers
  inject-groovy/src/test/groovy/io/micronaut/aop/scope/refreshable_qualified/RefreshableQualifiedScopeProxySpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#7486 Fix resolving `@Parameter`s in factories
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_and_named_parameterizedfactory/BFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_and_named_parameterizedfactory/MyAssocBean.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_and_named_parameterizedfactory/MyBean.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_and_named_parameterizedfactory/MyBeanUser.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_and_named_parameterizedfactory/ParametrizedFactoryOfPrimaryAndNamedSpec.groovy
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
Labels: type: improvement

#7485 Bump micronaut-maven-plugin to 3.3.0
  gradle.properties
Labels: type: dependency-upgrade

#7488 Fix bean delegates with `@Primary`
  inject-groovy/src/test/groovy/io/micronaut/aop/scope/refreshable_primary/RefreshablePrimaryScopeProxySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyAssocBean.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyBean.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyBeanUser.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyBeanUser2.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyConf.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/MyFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/factory/primary_parameterizedfactory/ParametrizedFactoryOfPrimarySpec.groovy
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/inject/qualifiers/CompositeQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/PrimaryQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
Labels: type: bug

#7501 Bump micronaut-test to 3.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7526 Fix native image service calculation for classes not within a JAR
  core/src/main/java/io/micronaut/core/graal/ServiceLoaderInitialization.java
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/main/java/io/micronaut/core/io/service/SoftServiceLoader.java
Labels: type: bug, relates-to: graal

#7527 Bump micronaut-openapi to 4.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
