Repository micronaut-projects/micronaut-core, pull requests merged in 2022-02, with the labels that each got.

#6849 Bump micronaut-maven-plugin to 3.1.1
  gradle.properties
Labels: type: dependency-upgrade

#6852 Bump micronaut-servlet to 3.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6861 Bump micronaut-azure to 3.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6868 build: use micronaut reactor bom
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: relates-to: build

#6866 build: use micronaut rxjava3 bom
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: relates-to: build

#6865 build: use micronaut rxjava2 bom
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: relates-to: build

#6879 Release streaming HTTP data when request is invalid
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/decoders/HttpRequestDecoder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/BufferLeakDetection.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
Labels: type: bug

#6880 docs: Fix javadoc links to non-core projects
  src/main/docs/guide/aop/caching.adoc
  src/main/docs/guide/aop/springAop.adoc
  src/main/docs/guide/cloud/clientSideLoadBalancing/netflixRibbon.adoc
  src/main/docs/guide/cloud/cloudConfiguration.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
  src/main/docs/guide/httpClient/clientAnnotation/netflixHystrix.adoc
  src/main/docs/guide/httpClient/clientFilter.adoc
  src/main/docs/guide/httpClient/lowLevelHttpClient.adoc
  src/main/docs/guide/httpClient/lowLevelHttpClient/clientStreaming.adoc
Labels: type: docs

#6884 Bump micronaut-email to 1.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6882 Update broken links in the guide
  build.gradle
  gradle.properties
  src/main/docs/guide/aop/caching.adoc
  src/main/docs/guide/aop/introductionAdvice.adoc
  src/main/docs/guide/cli/commands.adoc
  src/main/docs/guide/cli/features.adoc
  src/main/docs/guide/cloud/clientSideLoadBalancing/netflixRibbon.adoc
  src/main/docs/guide/configurations/dataAccess.adoc
  src/main/docs/guide/configurations/dataAccess/hibernateSupport.adoc
  src/main/docs/guide/configurations/dataAccess/liquibaseSupport.adoc
  src/main/docs/guide/configurations/dataAccess/mongoSupport.adoc
  src/main/docs/guide/configurations/dataAccess/sqlSupport.adoc
  src/main/docs/guide/configurations/reactiveConfigs/reactor.adoc
  src/main/docs/guide/httpClient/clientFilter.adoc
  src/main/docs/guide/httpClient/clientSample.adoc
  src/main/docs/guide/httpServer/http2Server.adoc
  src/main/docs/guide/httpServer/jsonBinding.adoc
  src/main/docs/guide/httpServer/serverConfiguration/accessLogger.adoc
  src/main/docs/guide/httpServer/serverConfiguration/threadPools.adoc
  src/main/docs/guide/httpServer/sse.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/beans.adoc
  src/main/docs/guide/ioc/types.adoc
  src/main/docs/guide/languageSupport/graal/graalFAQ.adoc
  src/main/docs/guide/languageSupport/groovy.adoc
  src/main/docs/guide/languageSupport/java/ide.adoc
  src/main/docs/guide/logging.adoc
  src/main/docs/guide/logging/logback.adoc
  src/main/docs/guide/management/providedEndpoints/infoEndpoint.adoc
  src/main/docs/guide/management/providedEndpoints/metricsEndpoint.adoc
  src/main/docs/guide/quickStart/buildCLI.adoc
  src/main/docs/guide/quickStart/ideSetup/eclipseSetup.adoc
Labels: type: docs

#6901 build: use micronaut kotlin bom
  gradle/libs.versions.toml
Labels: relates-to: build

#6897 Bump micronaut-views to 3.1.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6898 Bump micronaut-cache to 3.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6887 Bump micronaut-tracing to 4.0.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6908 Bump micronaut-jackson-xml to 3.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6870 feat: adds LocalizedMessageSource
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/util/HttpLocalizedMessageSourceSpec.groovy
  http-server-netty/src/test/resources/i18n/messages.properties
  http-server-netty/src/test/resources/i18n/messages_es.properties
  http-server/build.gradle
  http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
  http-server/src/test/groovy/io/micronaut/http/server/util/locale/HttpLocalizedMessageSourceIllegalStateExceptionSpec.groovy
  http/build.gradle
  inject/src/main/java/io/micronaut/context/AbstractLocalizedMessageSource.java
  inject/src/main/java/io/micronaut/context/LocalizedMessageSource.java
  inject/src/main/java/io/micronaut/context/MessageSource.java
  inject/src/main/java/io/micronaut/context/MessageSourceUtils.java
  inject/src/test/groovy/io/micronaut/context/MessageSourceUtilsSpec.groovy
  src/main/docs/guide/i18n/bundle.adoc
  src/main/docs/guide/i18n/localizedMessageSource.adoc
  src/main/docs/guide/ioc/beanValidation.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/i18n/I18nSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/i18n/MessageSourceFactory.groovy
  test-suite-groovy/src/test/resources/io/micronaut/docs/i18n/messages_en.properties
  test-suite-groovy/src/test/resources/io/micronaut/docs/i18n/messages_es.properties
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/i18n/I18nSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/i18n/MessageSourceFactory.kt
  test-suite-kotlin/src/test/resources/io/micronaut/docs/i18n/messages_en.properties
  test-suite-kotlin/src/test/resources/io/micronaut/docs/i18n/messages_es.properties
  test-suite/src/test/java/io/micronaut/docs/i18n/I18nSpec.java
  test-suite/src/test/java/io/micronaut/docs/i18n/MessageSourceFactory.java
  test-suite/src/test/resources/io/micronaut/docs/i18n/messages_en.properties
  test-suite/src/test/resources/io/micronaut/docs/i18n/messages_es.properties
Labels: type: enhancement

#6924 Set an identifier on collections of BeanRegistrations
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/test/groovy/io/micronaut/context/BeanRegistrationCollectionSpec.groovy
Labels: type: bug

#6941 Do not wait for request data after decode failure
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
Labels: type: bug

#6964 Bump micronaut-serialization to 1.0.0-RC2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6961 Bump micronaut-email to 1.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6926 Bump micronaut-flyway to 5.1.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
