Repository micronaut-projects/micronaut-core, pull requests merged in 2022-10, with the labels that each got.

#8128 Bump micronaut-email to 1.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8125 Lazily create the singleton stream-pipeline attribute to fix native image
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
Labels: relates-to: graal

#8141 Bump micronaut-data to 3.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8142 Bump micronaut-test to 3.7.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8161 Bump micronaut-views to 3.7.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8154 Use v6.0.1 of the internal build tools
  .github/workflows/central-sync.yml
  .github/workflows/corretto.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
  inject-java-test/src/main/java/io/micronaut/annotation/processing/test/JavaParser.java
  settings.gradle
Labels: relates-to: build

#8178 fix: PropertySourcePropertyResolver.getAllProperties behaviour when StringConvention.RAW
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
  inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy
Labels: type: bug

#8189 Fix the Hateoas/Groovy/Serde error in a binary compatible way
  gradle/libs.versions.toml
  http-server/build.gradle
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessor.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessorReplacement.java
  test-suite-groovy/build.gradle
Labels: type: bug, lang: groovy

#8123 Support http status 103 and 425
  http/src/main/java/io/micronaut/http/HttpStatus.java
Labels: hacktoberfest-accepted

#8201 fix: spelling mistake
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#8197 Reuse enclosed elements querying for Java and Groovy. Added a way to query methods and fields together.
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyEnumConstantElement.java
  inject-groovy/src/test/groovy/io/micronaut/ast/groovy/visitor/GroovyDocumentationSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaConstructorElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaEnumConstantElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaFieldElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject/src/main/java/io/micronaut/inject/ast/ConstructorElement.java
  inject/src/main/java/io/micronaut/inject/ast/ElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/EnumConstantElement.java
  inject/src/main/java/io/micronaut/inject/ast/FieldElement.java
  inject/src/main/java/io/micronaut/inject/ast/MemberElement.java
  inject/src/main/java/io/micronaut/inject/ast/MethodElement.java
  inject/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java
  inject/src/main/java/io/micronaut/inject/ast/utils/EnclosedElementsQuery.java
  inject/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  inject/src/main/java/io/micronaut/inject/processing/FactoryBeanElementCreator.java
  test-suite/src/test/groovy/io/micronaut/inject/SharedInjectionSpec.groovy
Labels: type: improvement

#8216 Correct record constructor search algorithm. Fixes #8187
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
Labels: type: bug

#8236 Bump micronaut-kafka to 4.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8232 build: update to SnakeYAML 1.33
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8231 build: update to SnakeYAML 1.33
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8233 build: netty to 4.1.84.Final
  gradle/libs.versions.toml
  http-netty/src/main/java/io/micronaut/http/netty/AbstractNettyHttpRequest.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
Labels: type: dependency-upgrade

#8243 Require asm as an api dependency so it's pulled in transitively downstream
  core-processor/build.gradle
Labels: relates-to: build

#8244 EntityIntrospectedAnnotationMapper class has moved
  src/main/docs/guide/ioc/annotationMetadata.adoc
Labels: type: docs, relates-to: build

#8239 Update valueAnnotation.adoc
  src/main/docs/guide/config/valueAnnotation.adoc
Labels: type: docs

#8245 Bump micronaut-security to 3.7.2
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8248 Bump micronaut-security to 3.8.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8249 Bump micronaut-servlet to 3.3.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
