Repository micronaut-projects/micronaut-core, pull requests merged in 2022-03, with the labels that each got.

#6983 Bump micronaut-gcp to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6986 Add recommendation regarding secrets to docs
  src/main/docs/guide/config/propertySource.adoc
Labels: type: docs

#6992 bug: Don't strip newlines proxying ServerSentEvents
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/sse/ServerSentEventProxyingSpec.groovy
Labels: type: bug

#6990 Bump micronaut-security to 3.4.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6998 Bump micronaut-aws to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7005 Bump micronaut-multitenancy to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6906 Bump micronaut-cache to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6987 Add GCP BOM to 3.4.x
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/serverlessFunctions/gcpFunction.adoc
Labels: relates-to: build

#7008 build: bump up micronaut test to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7012 Bump micronaut-reactor to 2.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7019 test: add query enum tests
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
Labels: type: improvement

#7017 Allow querying enum constants as fields
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaGenericPlaceholderElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject/src/main/java/io/micronaut/inject/ast/DefaultElementQuery.java
  inject/src/main/java/io/micronaut/inject/ast/ElementQuery.java
Labels: type: improvement

#7018 Bump micronaut-azure to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6835 [core] Update common files for branch 3.3.x
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  .gitignore
  MAINTAINING.md
  aop/src/main/java/io/micronaut/aop/internal/InterceptorBeanMapper.java
  config/checkstyle/checkstyle.xml
  config/checkstyle/custom-suppressions.xml
  config/checkstyle/suppressions.xml
  core/src/main/java/io/micronaut/core/io/service/SoftServiceLoader.java
  core/src/main/java/io/micronaut/core/reflect/ClassUtils.java
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  http-client-core/src/main/java/io/micronaut/http/client/bind/binders/AttributeClientRequestBinder.java
  http-client-core/src/main/java/io/micronaut/http/client/bind/binders/HeaderClientRequestBinder.java
  http-client-core/src/main/java/io/micronaut/http/client/bind/binders/VersionClientRequestBinder.java
  http-client/src/main/java/io/micronaut/http/client/netty/websocket/NettyWebSocketClientHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/DefaultHttp2Content.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/JsonSubscriber.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/NotImplementedElementBuilder.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/ErrorContext.java
  http/src/main/java/io/micronaut/http/filter/FilterPatternStyle.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject/src/main/java/io/micronaut/context/event/NoOpApplicationEventPublisher.java
  inject/src/main/java/io/micronaut/inject/annotation/internal/JakartaRemapper.java
  inject/src/main/java/io/micronaut/inject/ast/PrimitiveElement.java
  inject/src/main/java/io/micronaut/inject/ast/beans/BeanElementBuilder.java
  inject/src/main/java/io/micronaut/inject/visitor/BeanElementVisitor.java
  jackson-databind/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java
  jackson-databind/src/main/java/io/micronaut/jackson/codec/JsonMediaTypeCodec.java
  jackson-databind/src/main/java/io/micronaut/jackson/codec/JsonStreamMediaTypeCodec.java
  jackson-databind/src/main/java/io/micronaut/jackson/env/JsonPropertySourceLoader.java
  jackson-databind/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java
  management/src/main/java/io/micronaut/management/endpoint/env/EnvironmentEndpoint.java
  runtime/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java
  test-suite-helper/src/main/java/io/micronaut/testsuitehelper/TestGeneratingAnnotationProcessor.java
Labels: relates-to: build

#7021 Add mqtt 2.1.0 bom to core build
  gradle/libs.versions.toml
Labels: relates-to: build

#7023 Upgrade to build plugins 5.2.3
  bom/build.gradle
  buildSrc/build.gradle
  settings.gradle
Labels: type: dependency-upgrade

#7049 Dependencies upgrade
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7054 Add 5.2.0 redis bom to 3.4 build
  gradle/libs.versions.toml
Labels: relates-to: build

#7057 build: update to gradle 7.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#7050 Bump micronaut-toml to 1.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7059 Bump micronaut-sql to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7061 build: r2dbc to 2.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7060 Bump micronaut-servlet to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6173 Using @ConfigurationProperties methods in @Requires annotation
  aop/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectVisitor.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/requires/RequiresBeanPropertiesSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/requires/RequiresBeanPropertiesSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/RequiresCondition.java
  inject/src/main/java/io/micronaut/context/annotation/Requires.java
  inject/src/main/java/io/micronaut/context/exceptions/MessageUtils.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  src/main/docs/guide/config/configurationProperties.adoc
  src/main/docs/guide/ioc/conditionalBeans.adoc
Labels: type: enhancement

#7062 Bump micronaut-groovy to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7065 Bump micronaut-oracle-cloud to 2.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7053 buld: remove managed-lettuce
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7074 Bump micronaut-serialization to 1.0.0-RC3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7075 Bump micronaut-sql to 4.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7076 build: bump micronaut-mongodb to 4.1.0 and use BOM
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6850 Allow deserializing _embedded values of HATEOAS resources
  http/build.gradle
  http/src/main/java/io/micronaut/http/hateoas/AbstractResource.java
  http/src/main/java/io/micronaut/http/hateoas/GenericResource.java
  http/src/main/java/io/micronaut/http/hateoas/Resource.java
  http/src/test/groovy/io/micronaut/http/hateoas/GenericResourceSpec.groovy
  test-suite/src/test/groovy/io/micronaut/http/hateoas/JsonErrorEmbeddedSpec.groovy
Labels: type: improvement

#7080 Bump micronaut-kubernetes to 3.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7089 doc: change scope from runtime to runtimeOnly
  src/main/docs/guide/configurations/dataAccess/sqlSupport.adoc
  src/main/docs/guide/httpServer/serverConfiguration.adoc
  src/main/docs/guide/ioc/introspection.adoc
Labels: type: docs

#7091 Bump micronaut-acme to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7090 Bump micronaut-tracing to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7096 Update to jackson 2.13
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7095 Bump micronaut-serialization to 1.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7100 Bump micronaut-email to 1.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7103 Bump micronaut-maven-plugin to 3.2.0
  gradle.properties
Labels: type: dependency-upgrade

#7106 doc: update What's new section for 3.4.0
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#7108 Bump micronaut-kotlin to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7109 Improve Maven plugin's what's new section for 3.4.x
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#7115 Bump micronaut-kotlin to 3.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7114 Bump micronaut-kafka to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7119 Bump micronaut-sql to 4.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7124 doc: Change what's new section. Links to Data stable and 3.3.0
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#7125 doc: whats new beanProperty in @Requires
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#7118 ci: check_retries: true
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#7128 ci: cache@v3
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#7131 Bump micronaut-aot to 1.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7136 ci: release TARGET_REPOSITORY
  .github/workflows/release.yml
Labels: relates-to: build

#7123 Add Kafka BOM to Micronaut 3.5.0
  gradle/libs.versions.toml
Labels: relates-to: build

#7048 Refactor the Gradle build
  .gitignore
  aop/build.gradle
  benchmarks/build.gradle
  bom/build.gradle
  buffer-netty/build.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-library.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-quality.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-test-library.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/ext/DefaultMicronautCoreExtension.java
  buildSrc/src/main/groovy/io/micronaut/build/internal/ext/MicronautCoreExtension.java
  buildSrc/src/main/groovy/io/micronaut/build/internal/io.micronaut.build.internal.convention-core-library.gradle
  context/build.gradle
  core-reactive/build.gradle
  core/build.gradle
  function-client/build.gradle
  function-web/build.gradle
  function/build.gradle
  graal/build.gradle
  http-client-core/build.gradle
  http-client/build.gradle
  http-netty/build.gradle
  http-server-netty/build.gradle
  http-server/build.gradle
  http-validation/build.gradle
  http/build.gradle
  inject-groovy-test/build.gradle
  inject-groovy/build.gradle
  inject-java-test/build.gradle
  inject-java/build.gradle
  inject-kotlin-test/build.gradle
  inject-test-utils/build.gradle
  inject/build.gradle
  jackson-core/build.gradle
  jackson-databind/build.gradle
  json-core/build.gradle
  management/build.gradle
  messaging/build.gradle
  router/build.gradle
  runtime-osx/build.gradle
  runtime/build.gradle
  session/build.gradle
  settings.gradle
  test-suite-groovy/build.gradle
  test-suite-helper/build.gradle
  test-suite-jakarta-inject-bean-import/build.gradle
  test-suite-javax-inject/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
  test-utils/build.gradle
  validation/build.gradle
  websocket/build.gradle
Labels: relates-to: build

#7137 Bump micronaut-servlet to 3.2.2
  bom/build.gradle
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7162 build: Update to use Grpc BOM
  gradle/libs.versions.toml
Labels: relates-to: build

#7159 Bump micronaut-maven-plugin to 3.2.1
  gradle.properties
Labels: type: dependency-upgrade

#7155 Bump micronaut-aot to 1.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7160 Bump micronaut-serialization to 1.0.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
