Repository micronaut-projects/micronaut-core, pull requests merged in 2022-01, with the labels that each got.

#6707 Fix double release of form attributes
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormDataHttpContentProcessor.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/FormDataDiskSpec.groovy
Labels: type: bug

#6696 Fix ignoreBodyRead for large requests
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/MaxRequestSizeSpec.groovy
Labels: type: bug

#6688 Bump micronaut-views to 3.1.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6704 Bump micronaut-security to 3.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6694 Introduce a static optimizations loader
  core/src/main/java/io/micronaut/core/optim/StaticOptimizations.java
  core/src/test/groovy/io/micronaut/core/optim/StaticOptimizationsTest.groovy
  core/src/test/resources/META-INF/services/io.micronaut.core.optim.StaticOptimizations$Loader
Labels: type: improvement

#6668 Constant property sources shouldn't all be loaded
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/env/ConstantPropertySourceSpec.groovy
Labels: type: bug

#6721 Fix bug that makes it impossible to annotate inner types
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/ElementAnnotateSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
  inject/src/main/java/io/micronaut/inject/ast/Element.java
Labels: type: bug

#6676 Bump micronaut-sql to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6674 Bump micronaut-picocli to 4.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6673 Bump micronaut-kafka to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6718 Do not insert `@RequestAttribute`s as path params
  http-client-core/src/main/java/io/micronaut/http/client/bind/DefaultHttpClientBinderRegistry.java
  http-client/src/test/groovy/io/micronaut/http/client/aop/RequestAttributeSpec.groovy
Labels: type: bug

#6727 Fix imported introspection metadata not able to resolve type level annotations
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
Labels: type: bug

#6729 Bump Micronaut Test to 3.0.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6722 Delay response for `Mono` bodies of `HttpResponse` return values
  http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/BookController.java
  http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/ExceptionHandlerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/ReactiveMultiException.java
  http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/ReactiveMultiExceptionHandler.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: bug

#6736 Bump micronaut-liquibase to 5.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6738 Bump micronaut-flyway to 5.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6735 Bump micronaut-security to 3.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6743 build: log4j to 2.17.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6745 Do not apply filters when RouteExecutor decides not to handle an error
  gradle/libs.versions.toml
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ImmediateCloseSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: bug

#6752 Fix HTTP/2 304 responses for files don't associate the correct stream ID
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/FileTypeHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/stream/NettyStreamedCustomizableResponseType.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/Http2StaticResourceCacheSpec.groovy
Labels: type: bug

#6758 Bump micronaut-serialization to 1.0.0-M4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6764 Fix binding mixed attributes to body parameters
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  test-suite/src/test/groovy/io/micronaut/upload/MixedUploadSpec.groovy
  test-suite/src/test/groovy/io/micronaut/upload/UploadController.java
Labels: type: bug

#6771 Handle void return type from Function clients
  function-client/src/main/java/io/micronaut/function/client/http/HttpFunctionExecutor.java
  test-suite/src/test/groovy/io/micronaut/function/web/NullReturningConsumerFunctionSpec.groovy
Labels: type: bug

#6759 Release FileUpload, not the wrapped buffer, in NettyCompletedFileUpload
  http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/NettyCompletedFileUpload.java
Labels: type: bug

#6770 Fix record serialization for native image
  jackson-databind/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java
  jackson-databind/src/main/java/io/micronaut/jackson/ResilientBeanDeserializerFactory.java
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleRecordSpec.groovy
Labels: type: bug

#6765 Bump micronaut-security to 3.2.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6761 Delegate name resolution to proxy in DefaultHttpClient
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
Labels: type: bug

#6773 Bump micronaut-elasticsearch to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6670 Support for interceptor binding with annotation members
  aop/src/main/java/io/micronaut/aop/InterceptorBinding.java
  aop/src/main/java/io/micronaut/aop/chain/AbstractInterceptorChain.java
  aop/src/main/java/io/micronaut/aop/chain/ConstructorInterceptorChain.java
  aop/src/main/java/io/micronaut/aop/chain/DefaultInterceptorRegistry.java
  aop/src/main/java/io/micronaut/aop/chain/MethodInterceptorChain.java
  aop/src/main/java/io/micronaut/aop/internal/InterceptorBeanMapper.java
  aop/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  http-client/src/test/groovy/io/micronaut/http/client/SslSelfSignedSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyBeanDefinitionBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaBeanDefinitionBuilder.java
  inject-java/src/test/groovy/io/micronaut/aop/compile/AroundCompileSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/compile/AroundConstructCompileSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
  inject/src/main/java/io/micronaut/context/AbstractExecutableMethodsDefinition.java
  inject/src/main/java/io/micronaut/context/BeanRegistration.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject/src/main/java/io/micronaut/inject/qualifiers/InterceptorBindingQualifier.java
  inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
  inject/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
Labels: type: enhancement

#6661 Add the ability to configure Netty's default allocator
  buffer-netty/build.gradle
  buffer-netty/src/main/java/io/micronaut/buffer/netty/ByteBufAllocatorConfiguration.java
  buffer-netty/src/main/java/io/micronaut/buffer/netty/DefaultByteBufAllocatorConfiguration.java
  build.gradle
  http-netty/build.gradle
  http-netty/src/test/groovy/io/micronaut/http/netty/allocator/DefaultAllocatorSpec.groovy
Labels: type: enhancement

#6792 Bump micronaut-flyway to 5.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6793 Bump micronaut-liquibase to 5.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6789 Updated VSCode instructions
  src/main/docs/guide/quickStart/ideSetup/vsCodeSetup.adoc
Labels: type: docs

#6790 Fix introspection on beans with covariant return types
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
Labels: type: bug

#6794 Document options for customising JsonFactory
  src/main/docs/guide/httpServer/jsonBinding.adoc
Labels: type: docs

#6788 Bump micronaut-sql to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6800 Fix missing immutableConfig docs
  test-suite-groovy/src/test/groovy/io/micronaut/docs/config/immutable/Engine.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/immutable/Engine.kt
  test-suite/src/test/java/io/micronaut/docs/config/immutable/Engine.java
Labels: type: docs

#6801 Bump micronaut-openapi to 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6802 Bump micronaut-cache to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6775 Bump micronaut-serialization to 1.0.0-M5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6812 Bump micronaut-kotlin to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6816 Bump micronaut-serialization to 1.0.0-M6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6818 Bump micronaut-kubernetes to 3.3.0
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#6813 Add unsupported config option for logging HTTP data to pcap file
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/PcapLoggingSpec.groovy
Labels: type: improvement

#6821 Add capturedException on Retry in order to be able to retry also on Throwable
  runtime/src/main/java/io/micronaut/retry/RetryState.java
  runtime/src/main/java/io/micronaut/retry/annotation/Retryable.java
  runtime/src/main/java/io/micronaut/retry/intercept/AnnotationRetryStateBuilder.java
  runtime/src/main/java/io/micronaut/retry/intercept/CircuitBreakerRetry.java
  runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java
  runtime/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java
  runtime/src/test/groovy/io/micronaut/retry/intercept/SimpleRetryInstanceSpec.groovy
  runtime/src/test/groovy/io/micronaut/retry/intercept/SimpleRetrySpec.groovy
  src/main/docs/guide/aop/retry.adoc
Labels: type: improvement

#6823 Fix the docs for legacyMasking
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: docs

#6618 Bump micronaut-aws to 3.1.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6587 Add JsonMapper-based readMetadataUrl method to ComputeInstanceMetadataResolverUtils
  runtime/src/main/java/io/micronaut/discovery/cloud/ComputeInstanceMetadataResolverUtils.java
Labels: type: improvement

#6830 Bump micronaut-aws to 3.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#6832 Bump micronaut-flyway to 5.1.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
