Repository micronaut-projects/micronaut-core, pull requests merged in 2022-11, with the labels that each got.

#8265 Mark HateoasErrorResponseProcessorReplacement as Secondary
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessorReplacement.java
  test-suite-groovy/src/test/groovy/io/micronaut/http/server/exceptions/response/ErrorResponseProcessorSpec.groovy
Labels: type: bug

#8230 build: update GraalVM to 22.3.0
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade, relates-to: graal

#8180 Virtual thread support
  context/src/main/java/io/micronaut/scheduling/LoomSupport.java
  context/src/main/java/io/micronaut/scheduling/TaskExecutors.java
  context/src/main/java/io/micronaut/scheduling/executor/DefaultExecutorSelector.java
  context/src/main/java/io/micronaut/scheduling/executor/ExecutorConfiguration.java
  context/src/main/java/io/micronaut/scheduling/executor/ExecutorFactory.java
  context/src/main/java/io/micronaut/scheduling/executor/ExecutorType.java
  context/src/main/java/io/micronaut/scheduling/executor/IOExecutorServiceConfig.java
  context/src/main/java/io/micronaut/scheduling/executor/ThreadSelection.java
  context/src/main/java/io/micronaut/scheduling/executor/UserExecutorConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBinderRegistrar.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java
  management/src/main/java/io/micronaut/management/health/indicator/AbstractHealthIndicator.java
  management/src/main/java/io/micronaut/management/health/indicator/jdbc/JdbcIndicator.java
  runtime/src/test/groovy/io/micronaut/runtime/executor/ExecutorServiceConfigSpec.groovy
Labels: type: enhancement

#8279 Bump micronaut-serialization to 1.3.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8277 Bump micronaut-aws to 3.9.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8285 Fix: Req attrs has routeMatch for WebSocketServer
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/websocket/WebsocketRouteMatchSpec.groovy
Labels: type: regression

#8222 wrap original exception when the circuit breaker is opened
  runtime/src/main/java/io/micronaut/retry/annotation/CircuitBreaker.java
  runtime/src/main/java/io/micronaut/retry/intercept/CircuitBreakerRetry.java
  runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java
  runtime/src/test/groovy/io/micronaut/retry/intercept/CircuitBreakerRetrySpec.groovy
  runtime/src/test/groovy/io/micronaut/retry/intercept/CircuitBreakerSpec.groovy
Labels: type: improvement

#8307 Add support for Jakarta nulllable annotations.
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/JakartaNonnullTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/JakartaNullableTransformer.java
  core-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
  inject-java/src/test/groovy/io/micronaut/annotation/NonNullabilityAnnotationsSpec.groovy
  inject-java/src/test/groovy/io/micronaut/annotation/NullabilityAnnotationsSpec.groovy
Labels: type: improvement

#8311 remove javax.annotation.Nullable usage
  core/build.gradle
  core/src/main/java/io/micronaut/core/annotation/NonNull.java
  core/src/main/java/io/micronaut/core/annotation/Nullable.java
  core/src/main/java/io/micronaut/core/beans/BeanIntrospection.java
  core/src/main/java/io/micronaut/core/beans/BeanIntrospector.java
  core/src/main/java/io/micronaut/core/beans/BeanProperty.java
  core/src/main/java/io/micronaut/core/io/Readable.java
  core/src/main/java/io/micronaut/core/util/clhm/ConcurrentLinkedHashMap.java
  core/src/main/java/io/micronaut/core/util/clhm/EntryWeigher.java
  core/src/main/java/io/micronaut/core/util/clhm/EvictionListener.java
  core/src/main/java/io/micronaut/core/util/clhm/LinkedDeque.java
  retry/src/test/groovy/io/micronaut/retry/intercept/CircuitBreakerSpec.groovy
Labels: type: improvement

#8312 Remove use of shadow plugin
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-library.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/io.micronaut.build.internal.convention-core-library.gradle
Labels: type: bug

#8317 Bump micronaut-security to 3.8.2
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8068 Disable Cloud environment deduction by default. Fixes #7758
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/ApplicationContextBuilderSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/cloud/cloudConfiguration.adoc
  src/main/docs/guide/config/environments.adoc
Labels: type: improvement, type: breaking

#8306 Improve support for configuration property nesting
  context/src/main/java/io/micronaut/runtime/context/env/ConfigurationAdvice.java
  context/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java
  core-processor/build.gradle
  core-processor/src/main/java/io/micronaut/context/visitor/ConfigurationReaderVisitor.java
  core-processor/src/main/java/io/micronaut/inject/configuration/ConfigurationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/processing/ConfigurationReaderBeanElementCreator.java
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/itfce/InterfaceNestingSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/records/RecordNestingSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationMetadataSpec.groovy
Labels: type: improvement

#8316 Improve the error message for missing beans when EachBean is used
  inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/nested/A.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/nested/B.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/nested/C.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/exceptions/NoSuchBeanException.java
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: improvement

#8305 Implement support for injection of maps
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java/src/test/groovy/io/micronaut/inject/constructor/mapinjection/A.java
  inject-java/src/test/groovy/io/micronaut/inject/constructor/mapinjection/AImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/constructor/mapinjection/AnotherImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/constructor/mapinjection/B.java
  inject-java/src/test/groovy/io/micronaut/inject/constructor/mapinjection/ConstructorMapInjectionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/A.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/AImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/Animal.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/AnotherImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/B.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/Cat.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/Dog.java
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/FieldMapInjectionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/field/mapinjection/MapFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/method/mapinjection/A.java
  inject-java/src/test/groovy/io/micronaut/inject/method/mapinjection/AImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/method/mapinjection/AnotherImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/method/mapinjection/B.java
  inject-java/src/test/groovy/io/micronaut/inject/method/mapinjection/SetterMapInjectionSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/BeanLocator.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/exceptions/NonUniqueBeanException.java
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/ioc/types.adoc
Labels: type: enhancement

#8327 Stop conversion of Properties keys and values
  core/src/main/java/io/micronaut/core/convert/DefaultMutableConversionService.java
  core/src/test/groovy/io/micronaut/core/convert/DefaultConversionServiceSpec.groovy
Labels: type: bug

#8299 Rework BOM as core BOM
  bom/build.gradle
  buffer-netty/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/ext/DefaultMicronautCoreExtension.java
  context/build.gradle
  core-bom/README.md
  core-bom/build.gradle
  core/build.gradle
  gradle/libs.versions.toml
  http-client/build.gradle
  http-netty/build.gradle
  http-server-netty/build.gradle
  inject-groovy-test/build.gradle
  inject-groovy/build.gradle
  inject-java-test/build.gradle
  inject-java/build.gradle
  inject-kotlin-test/build.gradle
  inject-test-utils/build.gradle
  inject/build.gradle
  jackson-databind/build.gradle
  management/build.gradle
  parent/build.gradle
  runtime/build.gradle
  settings.gradle
  test-suite-geb/build.gradle
  test-suite-groovy/build.gradle
  test-suite-javax-inject/build.gradle
  test-suite-kotlin/build.gradle
  test-suite/build.gradle
  test-utils/build.gradle
  validation/build.gradle
Labels: type: breaking

#8280 Add a test module to verify simple native execution
  buildSrc/build.gradle
  settings.gradle
  test-suite-graal/build.gradle
  test-suite-graal/gradle.properties
  test-suite-graal/src/main/java/io/micronaut/test/graal/HomeController.java
  test-suite-graal/src/test/java/io/micronaut/test/graal/HomeControllerTest.java
Labels: relates-to: graal

#8339 Fix TLS hostname verification
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/test/groovy/io/micronaut/http/client/SslSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/RequestCertificateSpec.groovy
  http-server-netty/src/test/resources/KeyStore.pkcs12
  http-server-netty/src/test/resources/TrustStore.jks
Labels: type: bug

#8336 Mask headers that match know credentials
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/DefaultClientHeaderMaskTest.groovy
Labels: type: improvement

#8348 doc: Documents Nullability annotations
  src/main/docs/guide/ioc/nullabilityAnnotations.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#8349 Bump micronaut-security to 3.8.3
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8350 Groovy properties shouldn't become executable methods
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  inject-groovy/src/test/groovy/io/micronaut/aop/introduction/with_around/IntroductionWithAroundOnConcreteClassSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/executable/ExecutableBeanSpec.groovy
Labels: type: bug

#8345 Bump micronaut-kafka to 4.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8356 Bump Micronaut Azure to 3.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8359 upgrade Jackson to 2.14.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8367 Still emit response if return type is Void
  http-client-core/src/main/java/io/micronaut/http/client/HttpClient.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/aop/ClientFilterSpec.groovy
Labels: type: bug

#8389 Bump Micronaut Oracle Cloud to 2.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8398 Remove NoInjectBeanDefinition and improve/refactor RuntimeBeanDefinition
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultRuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/NoInjectionBeanDefinition.java
  inject/src/main/java/io/micronaut/context/RuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/SingletonScope.java
Labels: type: improvement

#8415 Add Hibernate validator BOM
  .github/workflows/graalvm.yml
  gradle/libs.versions.toml
Labels: relates-to: build

#8399 Bump GraalVM Native Build Tools to 0.9.18
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8432 Bump micronaut-liquibase to 5.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8430 build: Bump micronaut-email to 1.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8429 build: Bump micronaut-jackson-xml to 3.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8431 Bump micronaut-test to 3.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8433 Bump micronaut-redis to 5.3.2
  .github/workflows/graalvm.yml
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8322 Add JMX BOM
  gradle/libs.versions.toml
Labels: relates-to: build

#8321 Add Rabbit BOM
  gradle/libs.versions.toml
Labels: status: awaiting third-party, relates-to: build

#8442 Bump micronaut-maven-plugin to 3.5.1
  gradle.properties
Labels: type: dependency-upgrade

#8424 Support arbitrary nesting of EachProperty/ConfigurationProperties beans
  aop/src/main/java/io/micronaut/aop/internal/InterceptorRegistryBean.java
  context/src/main/java/io/micronaut/runtime/context/env/ConfigurationAdvice.java
  context/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java
  core-processor/src/main/java/io/micronaut/context/visitor/ConfigurationReaderVisitor.java
  core-processor/src/main/java/io/micronaut/inject/ast/ClassElement.java
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core/src/main/java/io/micronaut/core/type/DefaultArgument.java
  core/src/main/java/io/micronaut/core/type/TypeInformation.java
  core/src/main/java/io/micronaut/core/value/MapPropertyResolver.java
  core/src/main/java/io/micronaut/core/value/PropertyResolver.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/BeanDefinitionAnnotationMetadataSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ImmutableConfigurationPropertiesSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ConfigurationPropertiesInheritanceSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/nesting/EachPropertyNestingSpec.groovy
  inject/build.gradle
  inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultConditionContext.java
  inject/src/main/java/io/micronaut/context/DefaultMethodConstructorInjectionPoint.java
  inject/src/main/java/io/micronaut/context/DefaultMethodInjectionPoint.java
  inject/src/main/java/io/micronaut/context/DisabledBean.java
  inject/src/main/java/io/micronaut/context/RuntimeBeanDefinition.java
  inject/src/main/java/io/micronaut/context/SingletonScope.java
  inject/src/main/java/io/micronaut/context/env/ConfigurationPath.java
  inject/src/main/java/io/micronaut/context/env/DefaultConfigurationPath.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
  inject/src/main/java/io/micronaut/context/event/ApplicationEventPublisherFactory.java
  inject/src/main/java/io/micronaut/context/exceptions/MessageUtils.java
  inject/src/main/java/io/micronaut/inject/BeanDefinition.java
  inject/src/main/java/io/micronaut/inject/BeanType.java
  inject/src/main/java/io/micronaut/inject/DelegatingBeanDefinition.java
  inject/src/main/java/io/micronaut/inject/QualifiedBeanType.java
  inject/src/main/java/io/micronaut/inject/provider/AbstractProviderDefinition.java
  inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
  inject/src/test/groovy/io/micronaut/context/ConfigurationPathSpec.groovy
  inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy
Labels: type: enhancement
