Repository micronaut-projects/micronaut-core, pull requests merged in 2022-04, with the labels that each got.

#7172 Bump micronaut-maven-plugin to 3.2.2
  gradle.properties
Labels: type: dependency-upgrade

#7187 update Gradle native image command and directory
  src/main/docs/guide/languageSupport/graal/graalServices.adoc
Labels: type: docs

#7194 Fix links
  src/main/docs/guide/config/propertySource.adoc
Labels: type: docs

#7203 Bump micronaut-micrometer to 4.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7185 Bump micronaut-maven-plugin to 3.2.3
  gradle.properties
Labels: type: dependency-upgrade

#7181 build: bump micronaut-aot to 1.0.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7184 Bump micronaut-email to 1.2.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7211 fix: handle @ConfigurationProperties nested in @EachProperty properly
  context/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertyInterfaceSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/InterfaceAggregatorConfig.java
Labels: type: bug

#7214 Bump micronaut-aws to 3.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7227 Correct docs to reflect removal of `io.micronaut.spring/tx/annotation/Transactional`
  src/main/docs/guide/aop/springAop.adoc
Labels: type: docs

#7242 doc: move blocking Operation to its own file
  src/main/docs/guide/httpServer/serverConfiguration/threadPools.adoc
  src/main/docs/guide/httpServer/serverConfiguration/threadPools/blockingOperations.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#7240 doc: default value for thread selection
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
Labels: type: docs

#7247 Correct Kotlin coroutine interceptions
  aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/CustomRepository.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/InterceptorSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/MyRepository.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/MyRepositoryInterceptorImpl.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/MyService.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/Transaction1.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/Transaction1Interceptor.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/Transaction2.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/Transaction2Interceptor.kt
Labels: type: bug, lang: kotlin

#7262 Correct dependent beans destruction
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScope.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/DestroyDependentBeansSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/dependent/PrototypeBeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/SingletonBeanANoCallback.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/DestroyFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean1.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean1Factory.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean2.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean2Factory.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean3.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/MyBean3Factory.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/PreDestroyMyBean1Factory.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/PreDestroyMyBean2.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/factory/PreDestroyMyBean3.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherBeanB.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherBeanC.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherBeanD.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherBeanE.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherInterfaceA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/AnotherSingletonBeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/PreDestroyAnotherBeanA.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/PreDestroyAnotherBeanB.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/PreDestroyAnotherBeanC.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/PreDestroyAnotherBeanD.java
  inject-java/src/test/groovy/io/micronaut/inject/dependent/listeners/PreDestroyAnotherBeanE.java
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionRegistry.java
  inject/src/main/java/io/micronaut/context/BeanDisposingRegistration.java
  inject/src/main/java/io/micronaut/context/BeanRegistration.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/SingletonScope.java
  inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  src/main/docs/guide/ioc/factories.adoc
  src/main/docs/guide/ioc/lifecycle.adoc
Labels: type: improvement

#7246 Ignore unrecoverable ClosedChannelException errors
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
Labels: type: bug

#7260 fix: validation group inheritance, group validation
  validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
  validation/src/test/groovy/io/micronaut/validation/validator/ValidatorGroupsSpec.groovy
Labels: type: improvement

#7282 Bump micronaut-gcp to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7284 build: bump up problem from 2.2.2 to 2.2.3
  gradle/libs.versions.toml
Labels: relates-to: build

#7286 Bump micronaut-sql to 4.3.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#7281 build: AOT to 1.1.0
  gradle/libs.versions.toml
Labels: relates-to: build

#7228 doc: @Blocking
  src/main/docs/guide/httpServer/serverConfiguration/threadPools/atBlocking.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
