Repository micronaut-projects/micronaut-core, pull requests merged in 2023-02, with the labels that each got.

#8694 Bump micronaut-aws to 3.13.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8692 Bump micronaut-tracing to 4.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8702 build: add back managed-micronaut-discovery
  gradle/libs.versions.toml
  settings.gradle
Labels: relates-to: build

#8700 build: micronau-tracing 4.5.0
  bom/build.gradle
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8704 Tweak uri to account for WebLogic/Windows URIs
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/test/groovy/io/micronaut/core/io/IOUtilsSpec.groovy
Labels: type: bug

#8711 Bump micronaut-data to 3.9.6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8724 Bump micronaut-openapi to 4.8.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8728 Bump micronaut-test to 3.8.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8734 doc: Highlight virtual threads support
  src/main/docs/guide/httpServer/serverConfiguration/threadPools/blockingOperations.adoc
  src/main/docs/guide/httpServer/serverConfiguration/threadPools/virtualThreads.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/taskexecutors/HelloWorldController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/taskexecutors/TaskExecutorsBlockingSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/taskexecutors/HelloWorldController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/taskexecutors/TaskExecutorsBlockingTest.kt
  test-suite/src/test/java/io/micronaut/docs/taskexecutors/HelloWorldController.java
  test-suite/src/test/java/io/micronaut/docs/taskexecutors/TaskExecutorsBlockingTest.java
Labels: type: docs

#8732 doc: use asciidoc inner link
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationAwsParameterStore.adoc
Labels: type: docs

#8736 Fix NPE producing anntotion metadata for KSP
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  gradle/libs.versions.toml
  inject-kotlin-test/build.gradle
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/KotlinCompiler.java
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/AbstractKotlinCompilation.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/DefaultPropertyDelegate.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/HostEnvironment.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/JavacUtils.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/KotlinCompilation.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/Ksp.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/MainComponentRegistrar.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/SourceFile.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/StreamUtils.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/SynchronizedToolProvider.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/Utils.kt
  inject-kotlin-test/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar
  inject-kotlin/build.gradle
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/beans/BeanDefinitionProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/KotlinReconstructionSpec.groovy
Labels: type: bug

#8722 Run coretto on version named branches
  .github/workflows/corretto.yml
Labels: relates-to: build

#8748 Fix support for executable methods on introspections that require reflection
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/Auditable.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionGenericsSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractExecutableMethodsDefinition.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
Labels: type: bug

#8751 Allow user to explicity turn off the localhost drive-by CORS check
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsSimpleRequestTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/SimpleRequestWithCorsNotEnabledTest.java
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
Labels: type: improvement

#8747 doc: change copy of EachProperty
  src/main/docs/guide/config/eachProperty.adoc
Labels: type: docs

#8754 doc: reorder HTTP Clients implementations
  src/main/docs/guide/httpClient.adoc
  src/main/docs/guide/httpClient/httpClientImplementations.adoc
  src/main/docs/guide/httpClient/httpClientImplementations/javanetClient.adoc
  src/main/docs/guide/httpClient/httpClientImplementations/nettyHttpClient.adoc
  src/main/docs/guide/httpClient/javanetClient.adoc
  src/main/docs/guide/httpClient/javanetClient/unsupportedFeatures.adoc
  src/main/docs/guide/httpClient/lowLevelOrHighLevel.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#8750 Bump micronaut-kafka to 4.5.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8763 Stop using EnvUtil logback programmatic config
  runtime/src/main/java/io/micronaut/logging/impl/LogbackUtils.java
Labels: type: bug

#8769 Bump micronaut-oracle-cloud to 2.3.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8721 Replace deprecated output method for Github actions
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: type: deprecated

#8771 Optimize HttpRequestCertificateHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/HttpRequestCertificateHandler.java
Labels: type: improvement

#8770 Bump micronaut-openapi to 4.8.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8778 fix primitive import with test
  inject-java-test/src/test/groovy/io/micronaut/inject/beanimport/BeanImportSpec.groovy
  inject/src/main/java/io/micronaut/inject/processing/JavaModelUtils.java
Labels: type: bug

#8774 build: Netty 4.1.87.Final
  gradle/libs.versions.toml
  src/main/docs/guide/httpServer/http2Server.adoc
Labels: status: awaiting third-party, type: dependency-upgrade

#8784 build: Apache groovy 4.0.9
  gradle/libs.versions.toml
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/LoadedVisitor.groovy
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: dependency-upgrade

#8788 doc: links to session module
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#8793 Fix GraalVM native image support
  http-netty/src/main/resources/META-INF/native-image/io.micronaut/micronaut-http-netty/native-image.properties
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
Labels: type: bug

#8795 Refactor: Remove unnecessary use of reactive APIs in routes endpoint
  management/src/main/java/io/micronaut/management/endpoint/routes/RouteDataCollector.java
  management/src/main/java/io/micronaut/management/endpoint/routes/RoutesEndpoint.java
  management/src/main/java/io/micronaut/management/endpoint/routes/impl/DefaultRouteDataCollector.java
  management/src/test/groovy/io/micronaut/management/endpoint/routes/RoutesEndpointSpec.groovy
Labels: type: improvement

#8818 test: ExceptionHandler and @ResponseFilter and @RequestFilter
  http-server-tck/src/main/java/io/micronaut/http/server/tck/AssertionUtils.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/HttpServerFilterExceptionHandlerTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterExceptionHandlerTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/ResponseFilterExceptionHandlerTest.java
Labels: type: improvement

#8816 doc: close asciidoc table
  src/main/docs/guide/httpServer/filters.adoc
Labels: type: docs

#8745 Configuration asciidoc macro migration
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
  src/main/docs/guide/httpClient/lowLevelHttpClient/clientConfiguration.adoc
  src/main/docs/guide/httpServer/serverConfiguration/accessLogger.adoc
Labels: type: docs

#8826 fix validation of write-only config properties
  core/src/main/java/io/micronaut/core/io/service/SoftServiceLoader.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/writeonly/WriteOnlyConfigProperties.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/writeonly/WriteOnlyConfigPropertiesSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
Labels: type: bug

#8834 Bump micronaut-aws to 3.14.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8827 Bump micronaut-aws to 3.10.8
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8838 Bump micronaut-aws to 3.10.9
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8839 Bump micronaut-test to 3.9.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8841 Remove more GraalVM build-time init flags
  context/src/main/resources/META-INF/native-image/io.micronaut/micronaut-context/native-image.properties
  jackson-core/src/main/resources/META-INF/native-image/io.micronaut/micronaut-jackson-core/native-image.properties
Labels: type: improvement

#8842 Fix broken MethodElement.overrides implementation
  core-processor/src/main/java/io/micronaut/inject/ast/MethodElement.java
  core-processor/src/main/java/io/micronaut/inject/processing/IntroductionInterfaceBeanElementCreator.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
Labels: type: bug

#8845 Bump micronaut-security to 3.9.3
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8843 cleanup unnecessary GraalVM flags
  aop/src/main/resources/META-INF/native-image/io.micronaut/micronaut-aop/native-image.properties
  core-reactive/src/main/resources/META-INF/native-image/io.micronaut/micronaut-core-reactive/native-image.properties
  http-server/src/main/resources/META-INF/native-image/io.micronaut/micronaut-http-server/native-image.properties
  http/src/main/resources/META-INF/native-image/io.micronaut.http/micronaut-http/native-image.properties
  management/src/main/resources/META-INF/native-image/io.micronaut.management/micronaut-management/native-image.properties
  validation/src/main/resources/META-INF/native-image/io.micronaut.validation/micronaut-validation/native-image.properties
Labels: type: improvement, relates-to: graal

#8846 Add note about using logback 1.3.x+
  src/main/docs/guide/logging/logback.adoc
Labels: type: docs

#8851 Bump micronaut-azure to 3.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8850 Update simple retry doc to mention a linear progression of 1s
  src/main/docs/guide/aop/retry.adoc
Labels: type: docs

#8792 Include disabled bean info in beans endpoint
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionRegistry.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DisabledBean.java
  management/src/main/java/io/micronaut/management/endpoint/beans/BeanDefinitionDataCollector.java
  management/src/main/java/io/micronaut/management/endpoint/beans/BeansEndpoint.java
  management/src/main/java/io/micronaut/management/endpoint/beans/impl/DefaultBeanDefinitionData.java
  management/src/main/java/io/micronaut/management/endpoint/beans/impl/DefaultBeanDefinitionDataCollector.java
  management/src/test/groovy/io/micronaut/management/endpoint/beans/BeansEndpointSpec.groovy
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: enhancement
