Repository micronaut-projects/micronaut-core, pull requests merged in 2023-03, with the labels that each got.

#8857 Bump micronaut-test to 3.9.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8854 Bump micronaut-micrometer to 4.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8856 Bump micronaut-serialization to 1.5.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8836 fix: allow to disable disable `ServiceReadyHealthIndicator` via configuration
  management/src/main/java/io/micronaut/management/endpoint/health/HealthEndpoint.java
  management/src/main/java/io/micronaut/management/health/indicator/service/ServiceReadyHealthIndicator.java
  management/src/test/groovy/io/micronaut/management/health/indicator/discovery/DiscoveryClientHealthIndicatorConfigurationSpec.groovy
  management/src/test/groovy/io/micronaut/management/health/indicator/service/ServiceReadyHealthIndicatorSpec.groovy
Labels: type: improvement

#8867 Bump micronaut-aws to 3.14.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8864 fix IncompatibleClassChangeError in ConfigurationProperties
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesParseSpec.groovy
Labels: type: bug

#8865 Run the HTTP TCK against Netty natively
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ConsumesTest.java
  settings.gradle
  test-suite-graal/gradle.properties
  test-suite-graal/src/main/java/io/micronaut/test/graal/HomeController.java
  test-suite-graal/src/test/java/io/micronaut/test/graal/HomeControllerTest.java
  test-suite-http-server-tck-netty/build.gradle
  test-suite-http-server-tck-netty/build.gradle.kts
  test-suite-http-server-tck-netty/src/test/resources/logback.xml
Labels: relates-to: graal

#8869 Remove jackson databind as a transtive of GraalVM module
  graal/build.gradle
Labels: type: improvement

#8875 Bump micronaut-gcp to 4.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8873 Bump micronaut-sql to 4.7.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8874 Bump micronaut-aot to 1.1.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8868 Bump micronaut-sql to 4.6.7
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8877 docs: fix Route Compile-Time validation
  src/main/docs/guide/httpServer/routing.adoc
Labels: type: docs

#8878 Bump micronaut-kafka to 4.5.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8737 Remove docs for HTTP sessions and provide link to `micronaut-session` docs
  gradle.properties
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/httpServer/sessions.adoc
Labels: type: docs

#8883 Bump micronaut-sql to 4.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8886 Bump micronaut-gcp to 4.9.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8887 build: Micronaut Flyway 5.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8888 Bump micronaut-liquibase to 5.7.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8892 Bump micronaut-aws to 3.15.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8894 Bump micronaut-reactor to 2.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8895 Bump micronaut-serialization to 1.5.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8689 [core] Update common files for branch 4.0.x
  .editorconfig
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#8899 Allow to introspect classes by names
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core/src/main/java/io/micronaut/core/annotation/Introspected.java
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/annotation/AnnotateTypeArgSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: improvement

#8904 Allow Tag annotation at build time for the TCK
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ErrorHandlerTest.java
  http-tck/src/main/java/io/micronaut/http/tck/BodyAssertion.java
  http-tck/src/main/resources/META-INF/native-image/io.micronaut.http.tck/micronaut-http-tck/native-image.properties
Labels: relates-to: graal

#8905 BREAKING: update dependency org.yaml:snakeyaml to v2
  gradle/libs.versions.toml
  inject/src/main/java/io/micronaut/context/env/yaml/CustomSafeConstructor.java
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: dependency-upgrade, type: breaking

#8906 remove parallelism from default methods in AnnotationScanner
  core/src/main/java/io/micronaut/core/io/scan/AnnotationScanner.java
Labels: type: improvement

#8559 HTTP/3 support
  gradle/libs.versions.toml
  http-client-core/src/main/java/io/micronaut/http/client/HttpVersionSelection.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/AbstractJdkHttpClient.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/H2CSpec.groovy
  http-client/build.gradle
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-netty/src/main/java/io/micronaut/http/netty/AbstractNettyHttpRequest.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EpollEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyChannelType.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NioEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/reactive/HandlerSubscriber.java
  http-netty/src/main/java/io/micronaut/http/netty/stream/HttpStreamsHandler.java
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/QuicTokenHandlerImpl.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/CertificateProvidedSslBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/SelfSignedSslBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/ServerSslBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/QuicTokenHandlerImplSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http3Spec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/Http2StaticResourceCacheSpec.groovy
  src/main/docs/guide/httpClient/clientHttp3.adoc
  src/main/docs/guide/httpClient/httpClientImplementations/jdkHttpClient.adoc
  src/main/docs/guide/httpServer/http3Server.adoc
  src/main/docs/guide/toc.yml
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/http/client/http2/Http2RequestSpec.groovy
  test-suite/src/test/groovy/io/micronaut/http/client/http2/Http3RequestSpec.groovy
Labels: type: enhancement

#8915 [core] Update common files for branch 4.0.x
  .github/renovate.json
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#8922 Bump micronaut-test to 3.9.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8921 Bump micronaut-openapi to 4.8.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8920 Bump micronaut-micrometer to 4.8.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8926 [core] Update common files for branch 4.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#8914 build: remove dependency to validation dependency from core
  .github/workflows/gradle.yml
  http-server-tck/build.gradle.kts
  http-tck/build.gradle.kts
  test-suite-http-server-tck-jdk/build.gradle.kts
Labels: relates-to: build

#8580 Add support for annotation-based CORS configuration (8558)
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CrossOriginUtilSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/CorsAssertion.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/CorsUtils.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/HeadersTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsDisabledByDefaultTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsSimpleRequestTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CrossOriginTest.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConverter.java
  http-server/src/main/java/io/micronaut/http/server/cors/CrossOrigin.java
  http-server/src/main/java/io/micronaut/http/server/cors/CrossOriginUtil.java
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/annotationBasedCors.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowCredentials.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedHeaders.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedMethods.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedOrigins.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsExposedHeaders.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsMaxAge.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/cors/CorsController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/cors/CorsControllerSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/cors/CorsController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/cors/CorsControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/http/server/cors/CorsController.java
  test-suite/src/test/java/io/micronaut/docs/http/server/cors/CorsControllerTest.java
Labels: type: enhancement

#8952 doc: delete what’s new and breaks prior to 4.0.0
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#8786 doc: Add KSP section and mention it in what's new
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/languageSupport/kotlin.adoc
  src/main/docs/guide/languageSupport/kotlin/controller.adoc
  src/main/docs/guide/languageSupport/kotlin/kapt.adoc
  src/main/docs/guide/languageSupport/kotlin/kaptOrKsp.adoc
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#8960 doc: introduction mention server & client runtimes
  gradle.properties
  src/main/docs/guide/introduction.adoc
Labels: type: docs

#8961 doc: retry dependency in Advice & HTTP client
  src/main/docs/guide/aop/retry.adoc
  src/main/docs/guide/httpClient/clientAnnotation/clientRetry.adoc
Labels: type: docs

#8962 fix: WebSocketMessageEncoder @Requires classes
  http-netty/src/main/java/io/micronaut/http/netty/websocket/WebSocketMessageEncoder.java
Labels: type: bug

#8980 Bump Jib Maven Plugin version
  parent/build.gradle
Labels: type: dependency-upgrade

#8971 tck: static resource test
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/staticresources/StaticResourceTest.java
  http-server-tck/src/main/resources/assets/hello.txt
Labels: type: improvement

#9012 Bump micronaut-maven-plugin to 3.5.3
  gradle.properties
Labels: type: dependency-upgrade

#9009 Logback configuration defined via JAVA_TOOL_OPTIONS is ignored
  runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
  runtime/src/main/java/io/micronaut/logging/impl/LogbackUtils.java
  settings.gradle
  test-suite-logback-external-configuration/build.gradle.kts
  test-suite-logback-external-configuration/src/external/external-logback.xml
  test-suite-logback-external-configuration/src/test/groovy/io/micronaut/logback/ExternalConfigurationSpec.groovy
  test-suite-logback-external-configuration/src/test/resources/logback.xml
Labels: type: bug

#9021 Bump micronaut-security to 3.9.4
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9019 build: netty 4.1.90-Final
  gradle/libs.versions.toml
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/HttpResponseSpec.groovy
Labels: type: dependency-upgrade

#9020 Bump micronaut-openapi to 4.8.6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9023 Bump micronaut-views to 3.8.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9025 Enhance TCK server headers test
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/HeadersTest.java
Labels: relates-to: build

#9026 Bump micronaut-data to 3.9.7
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9032 Use `Map.of` instead of custom implementation
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/FullHttpStackBenchmark.java
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
Labels: type: improvement

#9033 ci: fold release-notes & sonar in gradle workflow
  .github/workflows/corretto.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#8992 Update CRaC to 1.2.1 for Micronaut 3.9.0
  gradle/libs.versions.toml
Labels: relates-to: build

#9037 Bump micronaut-kubernetes to 3.4.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9040 Bump micronaut-liquibase to 5.6.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
