Repository micronaut-projects/micronaut-core, pull requests merged in 2023-06, with the labels that each got.

#9367 [core] Update common files for branch 4.0.x
  .github/renovate.json
Labels: relates-to: build

#9368 Bump micronaut-aws to 3.17.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9372 KSP: Correct kotlin type identity object
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinNativeElement.kt
Labels: type: bug

#9373 Improve scheduled exception handling
  context/src/main/java/io/micronaut/scheduling/processor/ScheduledMethodProcessor.java
Labels: type: improvement

#9380 missingBeans for EndpointsFilter
  management/src/main/java/io/micronaut/management/endpoint/EndpointSensitivityHandler.java
  management/src/main/java/io/micronaut/management/endpoint/EndpointsFilter.java
  management/src/test/groovy/io/micronaut/management/endpoint/EndpointSensitivityHandlerSpec.groovy
Labels: type: improvement

#8072 Properties annotated with JPA transient should not be excluded from introspections by default
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/EntityIntrospectedAnnotationMapper.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/persistence/JakartaEntityIntrospectedAnnotationMapper.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/TestEntityAnnotationMapper.java
Labels: status: under consideration, type: breaking

#9395 [core] Update common files for branch 4.0.x
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#9370 Bump micronaut-maven-plugin to 3.5.4
  gradle.properties
Labels: type: dependency-upgrade

#9399 Fix multiple iterable beans not resulting in `NonUniqueBeanException`
  inject-java/src/test/groovy/io/micronaut/inject/foreach/multi/Bar.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/multi/EachBeanConflictSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/multi/Foo.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/multi/MyBean.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/multi/MyService.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
Labels: type: bug

#9405 Wait for request body if necessary in filter
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FilterBodySpec.groovy
  http/src/main/java/io/micronaut/http/FullHttpRequest.java
  http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java
  http/src/main/java/io/micronaut/http/filter/FilterRunner.java
Labels: type: improvement

#9407 Allow nullability annotations on generic arguments
  core/src/main/java/io/micronaut/core/annotation/NonNull.java
  core/src/main/java/io/micronaut/core/annotation/Nullable.java
  inject-java/src/test/groovy/io/micronaut/annotation/NullabilityFutureAnnotationsSpec.groovy
Labels: type: improvement

#9408 Generate Java 17 bytecode
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  inject-groovy/src/test/groovy/io/micronaut/aop/factory/AdviceDefinedOnInterfaceFactorySpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/factory/AdviceDefinedOnInterfaceFactorySpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/factory/AdviceDefinedOnInterfaceFactorySpec.groovy
Labels: type: improvement

#9410 Add breaking change note about the removal of `OncePerRequestHttpServerFilter`
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: docs

#9413 Fix SSL context leak
  http-client/build.gradle
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
Labels: type: bug

#9415 Support time zone in time format for access log
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/DateTimeElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/element/AccessLogFormatParserSpec.groovy
Labels: type: improvement

#9444 ci: sla to 1.7.0
  .github/workflows/release.yml
Labels: relates-to: build

#9440 Filter documentation improvements
  http-validation/src/main/java/io/micronaut/validation/routes/FilterVisitor.java
  http/src/main/java/io/micronaut/http/annotation/RequestFilter.java
  http/src/main/java/io/micronaut/http/annotation/ResponseFilter.java
  http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java
  http/src/main/java/io/micronaut/http/filter/FilterRunner.java
  src/main/docs/guide/httpServer/filters/filtermethods.adoc
  src/main/docs/guide/httpServer/filters/filtermethods/order.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/resources/img/filter-order.svg
Labels: type: docs

#9451 Check for optional type in response adaptor
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/HttpResponseAdapter.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/RawStringHandlingSpec.groovy
  test-suite-http-server-tck-jdk/src/test/java/io/micronaut/http/server/tck/netty/tests/JdkHttpServerTestSuite.java
Labels: type: bug

#9449 Fix connection leak with read timeout during acquisition
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/test/groovy/io/micronaut/http/client/PoolTimeoutSpec.groovy
Labels: type: bug

#9457 Use unsafe setters for Jackson
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
Labels: type: improvement

#9453 remove generic from JsonMapper::writeValueAsString
  json-core/src/main/java/io/micronaut/json/JsonMapper.java
Labels: type: bug

#9459 Introduce `UnsafeBeanInstantiationIntrospection`
  core/src/main/java/io/micronaut/core/beans/AbstractBeanIntrospection.java
  core/src/main/java/io/micronaut/core/beans/UnsafeBeanInstantiationIntrospection.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
Labels: type: improvement

#9458 Jackson instantiate callback
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/constraintshandler/ControllerConstraintHandlerTest.java
  jackson-databind/build.gradle
  jackson-databind/src/main/java/io/micronaut/jackson/JacksonDeserializationPreInstantiateCallback.java
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/main/java/io/micronaut/jackson/validation/ValidationJacksonDeserializationPreInstantiateCallback.java
Labels: type: improvement

#9473 Introduce `PropagatedContext.empty`
  core/src/main/java/io/micronaut/core/beans/UnsafeBeanInstantiationIntrospection.java
  core/src/main/java/io/micronaut/core/propagation/PropagatedContext.java
  core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
  core/src/test/groovy/io/micronaut/core/propagation/PropagatedContextSpec.groovy
Labels: type: improvement

#9479 Method binding with no @Body TCK tests, updated docs and docs examples.
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
  src/main/docs/guide/httpServer/binding.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/Point.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/PointController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/PointControllerSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/Point.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/PointController.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/PointControllerTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/Point.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/PointController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/PointControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/server/binding/Point.java
  test-suite/src/test/java/io/micronaut/docs/server/binding/PointController.java
  test-suite/src/test/java/io/micronaut/docs/server/binding/PointControllerTest.java
Labels: type: docs

#9489 Bump micronaut-security to 3.11.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9497 Update what's new docs with GraalVM 23 and HTTP/3
  src/main/docs/guide/introduction/whatsNew.adoc
Labels: type: docs

#9509 Change annotation-based CORS to match configuration-based defaults
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CrossOriginUtilSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsSimpleRequestTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CrossOriginTest.java
  http-server/src/main/java/io/micronaut/http/server/cors/CrossOriginUtil.java
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/annotationBasedCors.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedOrigins.adoc
Labels: type: breaking

#9496 Bump micronaut-security to 3.1.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9498 Bump micronaut-security to 3.2.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9507 Bump micronaut-security to 3.3.2
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9516 Bump micronaut-security to 3.5.3
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9519 Bump micronaut-security to 3.6.6
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9523 Bump micronaut-security to 3.8.4
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9524 Bump micronaut-security to 3.9.6
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
