Repository micronaut-projects/micronaut-core, pull requests merged in 2023-01, with the labels that each got.

#8563 Remove usage of Utils classes from GraalReflectionConfigurer
  core/src/main/java/io/micronaut/core/graal/GraalReflectionConfigurer.java
Labels: type: bug

#8562 Bump micronaut-aws to 3.11.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8549 Bump micronaut-data to 3.9.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8565 add isWithin(..) check to each property handling
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
Labels: type: improvement

#8578 Pick a more specific setter if child configuration properties
  core-processor/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesParseSpec.groovy
Labels: type: bug

#8575 Move to Geb 7 for Groovy 4 support
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-geb-base.gradle
  gradle/libs.versions.toml
  test-suite-geb/build.gradle
  test-suite-geb/src/test/groovy/io/micronaut/upload/browser/UploadBrowserSpec.groovy
  test-suite-geb/src/test/resources/logback.xml
  test-suite/build.gradle
Labels: relates-to: build

#8579 Set kotlinOptions.jvmTarget to 17 for 4.0.0
  http/build.gradle
  src/main/docs/guide/languageSupport/kotlin/kotlinretainparamnames.adoc
  test-suite-kotlin/build.gradle
Labels: relates-to: build

#8571 build: enable binary compatiblity
  http-server-tck/build.gradle.kts
Labels: relates-to: build

#8587 test: pass request parameter to chain.proceed
  http-client/src/test/groovy/io/micronaut/http/client/ResponseAndStreamSpec.groovy
Labels: type: improvement

#8591 Bump micronaut-servlet to 3.3.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8594 Bump micronaut-data to 3.9.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8590 HTTP Server TCK Body assertion
  http-server-tck/src/main/java/io/micronaut/http/server/tck/AssertionUtils.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/BodyAssertion.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/HttpResponseAssertion.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
Labels: type: improvement

#8582 fix: 403 for cors simple requests & CorsFilter off
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterEnabledSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsOriginConverterEnabledSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/NettyCorsSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsDisabledByDefaultTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/SimpleRequestWithCorsNotEnabledTest.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
  http-server/src/main/java/io/micronaut/http/server/cors/package-info.java
Labels: type: bug, relates-to: security

#8606 Bump micronaut-aws to 3.12.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8598 Add logger.config to loggingConfiguration.adoc
  src/main/docs/guide/logging/loggingConfiguration.adoc
Labels: type: docs

#8577 Add documentation for virtual thread support
  src/main/docs/guide/httpServer/serverConfiguration/threadPools/blockingOperations.adoc
Labels: type: docs

#8553 Support Range requests when returning SystemFiles
  http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy
Labels: type: improvement

#8628 Bump micronaut-security to 3.9.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8629 Bump micronaut-views to 3.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8615 Bump micronaut-spring to 4.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8612 Disable prediction and distribution for test-suite-kotlin
  test-suite-kotlin/build.gradle
Labels: relates-to: build

#8640 Bump micronaut-servlet to 3.3.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8637 extract CORS docs to sections
  src/main/docs/guide/httpServer/serverConfiguration/cors.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowCredentials.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedHeaders.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedMethods.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedOrigins.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsConfiguration.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsExposedHeaders.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsMaxAge.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsMultipleHeaderValues.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#8658 Bump micronaut-oracle-cloud to 2.3.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8597 [core] Update common files for branch 4.0.x
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#8671 ci: sync as in project template
  .github/workflows/corretto.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#8646 Handle WebLogic classloader URIs
  core/src/main/java/io/micronaut/core/exceptions/UncheckedIOException.java
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/main/java/io/micronaut/core/util/IOExceptionBiFunction.java
  core/src/test/groovy/io/micronaut/core/io/IOUtilsSpec.groovy
Labels: type: bug

#8642 Fix Cors for alternate local addresses
  .github/workflows/graalvm.yml
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/RequestSupplier.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/TestScenario.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsSimpleRequestTest.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
Labels: type: bug

#8672 build: micronau-tracing 4.5.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8656 Bump micronaut-openapi to 4.8.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8681 Bump micronaut-micrometer to 4.7.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8682 Bump micronaut-azure to 3.7.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8683 Bump micronaut-azure to 3.8.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8685 Fix build by re-adding the managed-micrometer version
  gradle/libs.versions.toml
Labels: relates-to: build

#8684 Add docs on self-signed cert setup
  src/main/docs/guide/httpServer/serverConfiguration/https.adoc
Labels: type: docs
