Repository micronaut-projects/micronaut-core, pull requests merged in 2023-10, with the labels that each got.

#9921 ci: use Oracle GraalVM distribution
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#9941 test: TCK form url encoded with inmutable map
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/HttpRequestFactory.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/FormUrlEncodedTest.java
Labels: type: bug

#9942 Add alias annotations before the stereotypes
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/ast/PropertyElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedToBeanPropertiesTransformer.java
  core-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
  inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesBuilderSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/InheritedConfigurationReaderPrefixSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/PropertyElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/annotation/JavaAnnotationMetadataBuilderSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/annotation/MyStereotypeWithDefaultValue.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesBuilderSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/InheritedConfigurationReaderPrefixSpec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/PropertyElementSpec.groovy
  inject/src/main/java/io/micronaut/context/annotation/ConfigurationBuilder.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataSupport.java
  test-suite-kotlin-ksp/build.gradle
Labels: type: bug

#9951 regression: support JSON Patch
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
  json-core/src/main/java/io/micronaut/json/codec/JsonMediaTypeCodec.java
  test-suite/src/test/java/io/micronaut/docs/jsonpatch/JsonPatchTest.java
Labels: type: regression

#9953 tck: test assert either multi headers or comma separated headers
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/HeadersTest.java
Labels: type: improvement

#9911 Clarify how to return text-plain responses for answers others than Strings
  src/main/docs/guide/httpServer/jsonBinding.adoc
  src/main/docs/guide/httpServer/plainTextResponses.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/response/textplain/Person.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/response/textplain/TextPlainController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/response/textplain/TextPlainControllerTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/response/textplain/Person.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/response/textplain/TextPlainController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/http/server/response/textplain/TextPlainControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/http/server/response/textplain/Person.java
  test-suite/src/test/java/io/micronaut/docs/http/server/response/textplain/TextPlainController.java
  test-suite/src/test/java/io/micronaut/docs/http/server/response/textplain/TextPlainControllerTest.java
Labels: type: docs

#9952 Make `SimpleRetry` delay grow exponentially
  retry/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java
  retry/src/test/groovy/io/micronaut/retry/intercept/SimpleRetryInstanceSpec.groovy
Labels: type: bug

#9959 [core] Update common files for branch 4.1.x
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#9960 Support generating source files
  core-processor/src/main/java/io/micronaut/inject/visitor/VisitorContext.java
  core-processor/src/main/java/io/micronaut/inject/writer/ClassWriterOutputVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/GeneratedFile.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationProcessingOutputVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinOutputVisitor.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
Labels: type: improvement

#9962 [core] Update common files for branch 4.2.x
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#9895 Facilitate troubleshooting with trace logging for health check results when `endpoints.health.details-visible` is unavailable.
  management/build.gradle
  management/src/main/java/io/micronaut/management/health/aggregator/DefaultHealthAggregator.java
  management/src/main/java/io/micronaut/management/health/monitor/HealthMonitorTask.java
  management/src/test/groovy/io/micronaut/management/health/aggregator/HealthAggregatorSpec.groovy
  management/src/test/groovy/io/micronaut/management/health/monitor/HealthMonitorTaskSpec.groovy
  management/src/test/resources/logback-test.xml
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
Labels: type: enhancement

#9967 build: aws 4.0.5 and SQL 5.0.3
  gradle/libs.versions.toml
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
Labels: type: dependency-upgrade

#9966 build: Reactor 3.5.11 and Micronaut Reactor 3.0.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9980 Improve usability of @Mapper annotation
  context/src/main/java/io/micronaut/runtime/beans/MapperIntroduction.java
  context/src/main/java/io/micronaut/runtime/beans/MapperMethodProcessor.java
  context/src/test/groovy/io/micronaut/runtime/beans/MapperAnnotationSpec.groovy
  inject/src/main/java/io/micronaut/context/annotation/Mapper.java
Labels: type: improvement

#9990 build: netty 4.1.100.Final
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9977 [core] Update common files for branch 4.2.x
  .editorconfig
  .github/workflows/gradle.yml
Labels: relates-to: build

#10000 Fix JsonSyntaxException: Superfluous data after top-level array in streaming mode
  http-client/src/test/groovy/io/micronaut/http/client/JsonSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/body/JsonCounter.java
Labels: type: bug

#10001 Support GraalVM JDK 21+ --strict-image-heap flag
  core/src/main/java/io/micronaut/core/io/service/ServiceLoaderInitialization.java
  core/src/main/resources/META-INF/native-image/io.micronaut/micronaut-core/native-image.properties
  test-suite-http-server-tck-netty/build.gradle
Labels: type: improvement

#9815 Replace DEFAULT_EVENT_LOOP_THREADS with a lazy getter
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyThreadFactory.java
Labels: type: improvement

#10007 Handle and log HTTP/2 GOAWAY frame
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/EmbeddedTestUtil.groovy
Labels: type: bug

#9999 Add eq/hc for HttpVersionSelection
  http-client-core/src/main/java/io/micronaut/http/client/HttpVersionSelection.java
  http-client-core/src/test/groovy/io/micronaut/http/client/HttpVersionSelectionSpec.groovy
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistrySpec.groovy
Labels: type: bug, priority: high

#10013 Change default connection pool idle timeout from 0 to null
  http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
  http-client/src/test/groovy/io/micronaut/http/client/config/DefaultHttpClientConfigurationSpec.groovy
Labels: type: bug, type: improvement

#10017 Allow onComplete before request in PipeliningServerHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: bug

#10018 fix: do not try to dispatch inside the event loop if channel is inactive
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
Labels: type: bug

#10023 tck: form-url-encoded with field with list
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/forms/FormsSubmissionsWithListsTest.java
Labels: relates-to: build

#10022 Do not try to apply JsonView to failed responses
  http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewController.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy
Labels: type: bug

#10021 Fix logged error when using form fields with blocking filter
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormRouteCompleter.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FilterFormSpec.groovy
Labels: type: bug

#10049 Fix exception when querying primary constructor of private record
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
Labels: type: bug

#10050 Fix client read timeout between earmark and dispatch
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-client/src/test/java/io/micronaut/http/client/netty/DelegateEventLoop.java
Labels: type: bug
