Repository micronaut-projects/micronaut-core, pull requests merged in 2023-05, with the labels that each got.

#9165 Do not avoid processing enum methods
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/test/groovy/io/micronaut/annotation/processing/visitor/JavaVisitorSpec.groovy
Labels: type: improvement

#9200 Micronaut Framework from 2 to 3 to upgrade repo
  src/main/docs/guide/introduction/upgrading.adoc
Labels: type: docs

#9202 Kotlin 1.8.21 KSP update and Coroutines 1.7.0
  gradle/libs.versions.toml
  inject-kotlin/build.gradle
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
  test-suite-kotlin-ksp/build.gradle
Labels: lang: kotlin, type: dependency-upgrade

#9170 Bump micronaut-test to 4.0.0-M3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9215 doc: fix configuration properties
  src/main/docs/guide/httpServer/transfers.adoc
Labels: type: docs

#9201 Support MessageBodyWriter/Reader in the HTTP client
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/JsonStreamSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/ServerRedirectSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/StreamRequestSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/filter/MutateRequestClientFilterSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/FullNettyClientHttpResponseSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/body/ByteBufRawMessageBodyHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/CustomizableNettyJsonHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonStreamHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyTextPlainHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWritableBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/PublisherBodyBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/context/ServerRequestContextSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/threading/ThreadSelectionSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ResponseStatusTest.java
  http/src/main/java/io/micronaut/http/body/ChunkedMessageBodyReader.java
  http/src/main/java/io/micronaut/http/body/ContextlessMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/DefaultMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/DynamicMessageBodyWriter.java
  http/src/main/java/io/micronaut/http/body/RawMessageBodyHandler.java
  http/src/main/java/io/micronaut/http/body/RawMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/TextPlainHandler.java
  http/src/main/java/io/micronaut/http/body/TextStreamBodyWriter.java
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
  src/main/docs/guide/appendix/breaks.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/consumes/ConsumesControllerSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/consumes/ConsumesControllerSpec.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/consumes/ConsumesControllerSpec.kt
  test-suite/src/test/groovy/io/micronaut/docs/http/client/proxy/ProxyRequestSpec.groovy
  test-suite/src/test/java/io/micronaut/docs/function/client/aws/LocalFunctionInvokeSpec.java
  test-suite/src/test/java/io/micronaut/docs/server/consumes/ConsumesControllerSpec.java
Labels: type: enhancement

#9231 Set default netty maxOrder to 3
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupFactory.java
  http-netty/src/test/groovy/io/micronaut/http/netty/channel/EventLoopGroupSpec.groovy
Labels: type: improvement

#9233 Use the bean definition type as the bean type for custom scopes.
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/CustomScopeSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/ImplA.java
  inject-java/src/test/groovy/io/micronaut/inject/scope/custom/InterfaceA.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#9232 Correct Groovy storing annotation defaults in stereotype annotations
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
  inject-groovy/src/test/groovy/io/micronaut/inject/annotation/GroovyMappedStereotypesSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionDifferentPackageSpec.groovy
  inject-groovy/src/test/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  router/src/test/groovy/io/micronaut/ast/groovy/annotation/router/GroovyAnnotationMetadataBuilderSpec.groovy
Labels: type: bug

#9224 Bump micronaut-validation to 4.0.0-M6
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9247 Add nullable annotations transformers
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/AndroidxNullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/JdtNullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/JspecifyNullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/ReactivexNullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/ReactorNullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/Rxjava3NullableTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/SpotbugsNullableTransformer.java
  core-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
Labels: type: improvement

#9254 Bump micronaut-aws to 3.17.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9263 add @BootstrapContextCompatible to json message readers
  http-client/src/test/groovy/io/micronaut/http/client/bootstrap/ClientBootstrapSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
Labels: type: bug

#9262 Bump micronaut-sql to 4.8.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9260 Bump micronaut-kafka to 4.5.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9259 Bump micronaut-serialization to 1.5.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9266 Bump micronaut-gcp to 4.10.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9265 Bump micronaut-azure to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9271 Bump micronaut-picocli to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9196 Bump micronaut-tracing to 4.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9282 [core] Update common files for branch 4.0.x
  .github/workflows/release.yml
Labels: relates-to: build

#9287 Regression Writable in Filter
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWritableBodyWriter.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/bodywritable/HtmlBodyWritableTest.java
  http/src/main/java/io/micronaut/http/body/WritableBodyWriter.java
Labels: type: bug, type: regression

#9273 test: additional types for json codec
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/codec/JsonCodecAdditionalTypeTest.java
  http/src/main/java/io/micronaut/http/body/DefaultMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/DynamicMessageBodyWriter.java
  http/src/main/java/io/micronaut/http/codec/CodecConfiguration.java
  http/src/main/java/io/micronaut/http/codec/MediaTypeCodec.java
  json-core/src/test/groovy/io/micronaut/json/codec/JsonMediaTypeCodecSpec.groovy
  runtime/src/test/groovy/io/micronaut/runtime/http/codec/TextPlainCodecSpec.groovy
  src/main/docs/guide/httpServer/consumesAnnotation.adoc
Labels: type: bug, type: regression

#9246 failing tests for Constraint handler in Micronaut Framework 4
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ManagedBody.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/constraintshandler/ControllerConstraintHandlerTest.java
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: bug

#9302 exclude ControllerConstraintHandlerTest for Server JDK
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
  context-propagation/build.gradle
  context-propagation/src/test/kotlin/io/micronaut/context/propagation/mdc/MdcPropagationSpec.kt
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/TimedAnnotationMapper.java
  core-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  gradle/libs.versions.toml
  inject-java/build.gradle
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/generics/GenericTypeArgumentsSpec.groovy
  src/main/docs/guide/config/evaluatedExpressions.adoc
  test-suite-geb/build.gradle
  test-suite-groovy/build.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/docs/expressions/ExampleJob.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/expressions/ExampleJobSpec.groovy
  test-suite-http-server-tck-jdk/src/test/java/io/micronaut/http/server/tck/netty/tests/JdkHttpServerTestSuite.java
  test-suite-http-server-tck-netty/build.gradle
  test-suite-kotlin-ksp/build.gradle
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/aop/scheduled/ScheduledExample.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendController.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/aop/scheduled/ScheduledExample.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/expressions/ExampleJob.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/expressions/ExampleJobTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt
  test-suite/build.gradle
  test-suite/src/test/java/io/micronaut/docs/aop/around_reactive/TxSpec.java
  test-suite/src/test/java/io/micronaut/docs/expressions/ExampleJob.java
  test-suite/src/test/java/io/micronaut/docs/expressions/ExampleJobTest.java
Labels: type: dependency-upgrade

#9312 refreshAndDiff() should handle array values and property placeholders
  context/src/test/groovy/io/micronaut/runtime/context/scope/refresh/RefreshEventListenerSpec.groovy
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
Labels: type: bug

#9316 Only initialize typeElementVisitors once.
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
Labels: type: bug

#9336 [core] Update common files for branch 4.0.x
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#9304 Preserves original HTTP method while following permanent redirection
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/ServerRedirectSpec.groovy
Labels: type: improvement

#9346 Remove previous context propagation instrumentation
  context/src/main/java/io/micronaut/scheduling/instrument/ExecutorServiceInstrumenter.java
  context/src/main/java/io/micronaut/scheduling/instrument/Instrumentation.java
  context/src/main/java/io/micronaut/scheduling/instrument/InvocationInstrumenter.java
  context/src/main/java/io/micronaut/scheduling/instrument/InvocationInstrumenterFactory.java
  context/src/main/java/io/micronaut/scheduling/instrument/InvocationInstrumenterWrappedCallable.java
  context/src/main/java/io/micronaut/scheduling/instrument/InvocationInstrumenterWrappedRunnable.java
  context/src/main/java/io/micronaut/scheduling/instrument/MultipleInvocationInstrumenter.java
  context/src/main/java/io/micronaut/scheduling/instrument/NoopInstrumentation.java
  context/src/main/java/io/micronaut/scheduling/instrument/ReactiveInvocationInstrumenterFactory.java
  gradle/libs.versions.toml
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/SimpleChannelInboundHandlerInstrumented.java
Labels: type: breaking

#9365 Add missing @Requires on json mapper
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
Labels: type: bug
