Repository micronaut-projects/micronaut-core, pull requests merged in 2023-08, with the labels that each got.

#9635 Issue 6246 - UriBuilder/UriTemplate.PATTERN_FULL_URI: Query Parameters Parsed as Part of Path - simpler approach
  http/src/main/java/io/micronaut/http/uri/DefaultUriBuilder.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
  http/src/test/groovy/io/micronaut/http/uri/UriBuilderSpec.groovy
Labels: type: bug

#9660 Implement workaround for Eclipse JDT compiler
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
Labels: type: bug

#9654 Support Kotlin default parameters
  config/accepted-api-changes.json
  core-processor/src/main/java/io/micronaut/inject/ast/KotlinParameterElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/utils/EnclosedElementsQuery.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/MapperVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinParameterElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/KotlinBeanIntrospectionSpec.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/TestEntity3.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/defaults/DefaultsController.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/defaults/DefaultsControllerSpec.kt
Labels: lang: kotlin, type: improvement

#9665 [core] Update common files for branch 4.0.x
  MAINTAINING.md
Labels: relates-to: build

#9673 don't publish to latest docs unless in the default branch
  .github/workflows/release.yml
Labels: relates-to: build

#9683 Fix kotlin visitor context options
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
Labels: type: bug

#9710 fix: JDK HTTP Client error logging on successful response
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/DefaultJdkHttpClient.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/JdkBlockingHttpClient.java
Labels: type: bug

#9696 Fix SSE Content-Type header
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/sse/ServerSentEventSpec.groovy
  http/src/main/java/io/micronaut/http/body/TextStreamBodyWriter.java
Labels: type: bug

#9715 Use HttpHeadersUtil::trace to mask secrets
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/AbstractJdkHttpClient.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/filter/ClientFilterStereotypeSpec.groovy
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/filter/StaticClientFilterSpec.groovy
  http/src/main/java/io/micronaut/http/util/HttpHeadersUtil.java
Labels: type: improvement

#9692 Fix buffer leak when proxying multipart requests
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormRouteCompleter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ProxyStressTest.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: bug

#9679 [core] Update common files for branch 4.0.x
  .github/workflows/release.yml
Labels: relates-to: build

#9703 Update external Logback config documentation
  src/main/docs/guide/logging/loggingConfiguration.adoc
Labels: type: docs

#9721 Fix O(n²) code size in dispatchOne generation
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/AptClassWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
Labels: type: bug

#9723 invoke applicationContext::close to avoid too many open files in tck
  http-tck/src/main/java/io/micronaut/http/tck/EmbeddedServerUnderTest.java
Labels: type: bug

#9742 Make CopyOnWriteMap.evict more resilient for ConcurrentHashMap
  core/src/main/java/io/micronaut/core/util/CopyOnWriteMap.java
  core/src/test/groovy/io/micronaut/core/util/CopyOnWriteMapSpec.groovy
Labels: type: bug

#9744 Polish `DefaultMutableConversionService`
  core/src/main/java/io/micronaut/core/convert/DefaultMutableConversionService.java
Labels: type: improvement

#9753 KSP: Cache overridee
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyAccessorMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinMethodElement.kt
Labels: type: improvement

#9752 Correct type arguments for introduces beans
  core-processor/src/main/java/io/micronaut/inject/processing/AopIntroductionProxySupportedBeanElementCreator.java
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/intro/AImplementationLong.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/intro/AImplementationString.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/intro/AInterface.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/intro/IntroductionInjectionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/intro/MyIntroductionBean.java
Labels: type: bug

#9745 [core] Update common files for branch 4.1.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#9756 imp: build route with a media type other than JSON
  gradle/libs.versions.toml
  router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
  test-suite/src/test/java/io/micronaut/context/router/RouteBuilderMediaTypeTest.java
Labels: type: improvement

#9766 Performance improvement and cleanup of `PropertySourcePropertyResolver`
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
Labels: type: improvement

#9774 Implement enum constant in kotlin element factory
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinElementAnnotationMetadataFactory.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinElementFactory.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinEnumConstantElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinEnumElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinNativeElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: lang: kotlin

#9779 Changing Jakarta provide to `BeanProvider` as it's lazy
  http/src/main/java/io/micronaut/http/converters/HttpConverterRegistrar.java
Labels: type: improvement

#9786 KSP: Implement annotation defaults retrieval
  inject-java/src/test/groovy/io/micronaut/annotation/MyAnnotation2.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/MyAnnotation2.kt
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/MyAnnotationX.kt
Labels: type: improvement

#9784 Fix processing order of introduced method in Java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/QueryParamClientWebSocket.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/PublicAbstractMethodVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/PublicMethodVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/beans/IntroducedBeanVisitorSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/beans/MyRepoVisitor2.java
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: improvement

#9791 test: tck test for request.getUri() contains query values
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ErrorHandlerTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/RequestUriContainsQueryValueTest.java
Labels: type: improvement

#9785 Fix error handling for delayed subscription in ReactiveClientReader
  http-client/src/main/java/io/micronaut/http/client/netty/ReactiveClientReader.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ReactiveClientReaderSpec.groovy
Labels: type: bug

#9798 [core] Update common files for branch 4.1.x
  .github/workflows/release.yml
Labels: relates-to: build

#9789 if multiple JsonBodyWritter picks the one which is writable
  http/src/main/java/io/micronaut/http/body/DefaultMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/Bar.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/BarController.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/BarMessageBodyWriter.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/Foo.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/FooController.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/FooMessageBodyWriter.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/FooThrowMessageBodyWriter.java
  test-suite/src/test/java/io/micronaut/test/messageBodyWriter/MessageBodyWriterIsWritableTest.java
Labels: type: bug

#9788 Small bean context optimizations
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: improvement

#9803 doc: javadoc improvements
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/AndOperator.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/ComparablesComparisonOperation.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/LtOperator.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/LteOperator.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/NumericComparisonOperation.java
  core-processor/src/main/java/io/micronaut/inject/ast/WildcardElement.java
  core-processor/src/main/java/io/micronaut/inject/visitor/VisitorContext.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationMetadata.java
  core/src/main/java/io/micronaut/core/util/ObjectUtils.java
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/main/java/io/micronaut/http/client/netty/SimpleChannelInboundHandlerInstrumented.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonStreamHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWritableBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/MultiObjectBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterExceptionHandlerTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/ResponseFilterExceptionHandlerTest.java
  http/src/main/java/io/micronaut/http/annotation/ResponseFilter.java
  http/src/main/java/io/micronaut/http/body/MessageBodyHandler.java
  inject/src/main/java/io/micronaut/context/annotation/Parameter.java
  inject/src/main/java/io/micronaut/context/annotation/Requires.java
  inject/src/main/java/io/micronaut/inject/ParametrizedProvider.java
  jackson-databind/src/main/java/io/micronaut/jackson/serialize/MicronautDeserializers.java
  management/src/main/java/io/micronaut/management/endpoint/health/filter/HealthResultFilter.java
Labels: type: docs
