Repository micronaut-projects/micronaut-core, pull requests merged in 2023-12, with the labels that each got.

#10183 [core] Update common files for branch 4.2.x
  .github/workflows/central-sync.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#10188 Update test to 4.1.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#10212 Execute async controller methods without Reactor
  core/src/main/java/io/micronaut/core/execution/CompletableFutureExecutionFlow.java
  core/src/main/java/io/micronaut/core/execution/CompletableFutureExecutionFlowImpl.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stack/InvocationStackSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: improvement

#10226 Fix error with duplicate builder methods
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/BeanIntrospectionBuilderSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/TestBuildMe9.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
Labels: type: bug

#10223 More detailed error messages
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/PropertyCircularDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/PropertyDependencyMissingSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/nesting/EachPropertyNestingSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configurations/RequiresBeanSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/requires/RequiresSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/RequiresCondition.java
Labels: type: improvement

#10213 Update ROADMAP.adoc
  ROADMAP.adoc
Labels: type: docs

#10218 imp: don't send Content-length header for GET requests
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/HttpRequestFactory.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/ClientDisabledCondition.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/ContentLengthHeaderTest.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  test-suite-http-client-tck-jdk/src/test/java/io/micronaut/http/client/tck/jdk/tests/JdkHttpMethodTests.java
  test-suite-http-client-tck-netty/src/test/java/io/micronaut/http/client/tck/netty/tests/NettyHttpMethodTests.java
Labels: type: improvement

#10232 Move URI validation step back to RoutingInBoundHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyRequestLifecycle.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/MalformedUriSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
Labels: type: improvement

#10233 Change to public so that java doc is generated for Configuration Reference link in manual.
  buffer-netty/src/main/java/io/micronaut/buffer/netty/DefaultByteBufAllocatorConfiguration.java
Labels: type: docs

#10138 Replace chunked write API
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWriteContext.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/InputStreamBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/StreamFileBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/SystemFileBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/StreamPressureSpec.groovy
Labels: type: improvement

#10240 KSP: Fix enum class values
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
Labels: type: bug

#10237 Reimplement `EnclosedElementsQuery` to improve performance
  core-processor/src/main/java/io/micronaut/inject/ast/DefaultElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/ast/MethodElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/utils/EnclosedElementsQuery.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/test/groovy/io/micronaut/aop/introduction/IntroductionAdviceWithNewInterfaceSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
Labels: type: improvement

#10155 Implement decompression in PipeliningServerHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/DecompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: improvement

#10246 Compression support in PipeliningServerHandler
  gradle/libs.versions.toml
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpCompressionStrategy.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/SmartHttpContentCompressor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Compressor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/CompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/SmartHttpContentCompressorSpec.groovy
Labels: type: improvement

#10248 Update breaking changes for Micronaut 4
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: docs

#10247 KSP: Workaround for inner anonymous classes
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/extensions.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#10254 Use FastThreadLocal for context propagation if available
  core/build.gradle
  core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
  core/src/main/java/io/micronaut/core/propagation/ThreadContext.java
  gradle/libs.versions.toml
Labels: type: improvement

#10269 Add links to guides for Micronaut Core
  src/main/docs/guide/aop/scheduling.adoc
  src/main/docs/guide/config/configurationProperties.adoc
  src/main/docs/guide/httpClient/lowLevelHttpClient.adoc
  src/main/docs/guide/httpServer/errorHandling/statusHandlers.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors.adoc
  src/main/docs/guide/i18n/localizedMessageSource.adoc
  src/main/docs/guide/ioc/beans.adoc
  src/main/docs/guide/ioc/qualifiers.adoc
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
  src/main/docs/guide/quickStart/creatingServer.adoc
  src/main/docs/guide/quickStart/deployingApp.adoc
  src/main/docs/guide/quickStart/ideSetup/ideaSetup.adoc
Labels: type: docs

#10264 Allow Refreshable scope under test for Env.FUNCTION and ANDROID
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScope.java
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScopeCondition.java
  runtime/src/test/groovy/io/micronaut/runtime/context/scope/RefreshScopeSpec.groovy
Labels: relates-to: functions

#10149 [bug] EL fails when using primitive method arguments in expression
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/access/ContextMethodParameterAccess.java
  inject-java/src/test/groovy/io/micronaut/expressions/MethodArgumentEvaluationContextExpressionsSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/expressions/MethodArgumentEvaluationContextExpressionsSpec.groovy
Labels: type: bug

#10272 KSP: use `overrides` method instead of `findOverridee()`
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyAccessorMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinMethodElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/compile/IntroductionCompileSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/Convertible.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/Engine.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/Tire.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/V8Engine.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/accessories/RoundThing.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/accessories/SpareTire.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/Convertible.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/Engine.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/Tire.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/V8Engine.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/accessories/RoundThing.kt
  test-suite-kotlin-ksp/src/test/kotlin/org/atinject/javaxtck/auto/accessories/SpareTire.kt
Labels: type: improvement

#10273 Fix logged errors reported by fuzzing
  gradle/libs.versions.toml
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FlagAppender.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
  http-server-netty/src/test/resources/logback.xml
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessor.java
  http/build.gradle
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/java/io/micronaut/http/MediaTypeFuzzTest.java
  http/src/test/resources/io/micronaut/http/MediaTypeFuzzTestInputs/crash-22df7f6e72bba86bdb1fdbd4bf92372fd4fa6bbe
Labels: type: bug

#10281 Use Javac's `overrides` to determine if the method is overridden
  core-processor/src/main/java/io/micronaut/inject/ast/ConstructorElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/MemberElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/MethodElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject-java/src/test/java/test/Middle.java
  inject-java/src/test/java/test/another/Base.java
  inject-java/src/test/java/test/another/BeanWithPackagePrivate.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyAccessorMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinConstructorElement.kt
Labels: type: improvement

#10283 Initialize classes at build time that can deadlock graal compiler
  core/src/main/resources/META-INF/native-image/io.micronaut/micronaut-core/native-image.properties
Labels: type: bug

#10284 KSP: Do not store default empty string annotation value
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
Labels: type: bug

#10275 Improve PathVariable Docs
  src/main/docs/guide/httpServer/routing.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/routes/IssuesController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/routes/IssuesControllerTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/routes/IssuesController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/routes/IssuesControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/server/routes/IssuesController.java
  test-suite/src/test/java/io/micronaut/docs/server/routes/IssuesControllerTest.java
Labels: type: docs

#10288 Ensure responseWritten is called on discard
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: bug
