Repository micronaut-projects/micronaut-core, pull requests merged in 2023-09, with the labels that each got.

#9819 docs: fix broken, stale, and deprecated links in user guide
  src/main/docs/guide/aop/introductionAdvice.adoc
  src/main/docs/guide/aop/scheduling.adoc
  src/main/docs/guide/appendix/architecture/annotationArch.adoc
  src/main/docs/guide/appendix/architecture/compilerArch.adoc
  src/main/docs/guide/appendix/architecture/containerArch.adoc
  src/main/docs/guide/appendix/architecture/httpServerArch.adoc
  src/main/docs/guide/appendix/architecture/introspectionArch.adoc
  src/main/docs/guide/appendix/architecture/iocArch.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationSpringCloud.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationVault.adoc
  src/main/docs/guide/config/customTypeConverter.adoc
  src/main/docs/guide/config/propertySource.adoc
  src/main/docs/guide/configurations/dataAccess.adoc
  src/main/docs/guide/contextPropagation/reactorContextPropagation.adoc
  src/main/docs/guide/httpClient/clientAnnotation.adoc
  src/main/docs/guide/httpClient/lowLevelHttpClient/clientBasics.adoc
  src/main/docs/guide/httpServer/formData.adoc
  src/main/docs/guide/httpServer/jsonBinding.adoc
  src/main/docs/guide/httpServer/reactiveServer/reactiveResponses.adoc
  src/main/docs/guide/httpServer/serverConfiguration/cors/corsAllowedOrigins.adoc
  src/main/docs/guide/httpServer/serverIO.adoc
  src/main/docs/guide/httpServer/transfers.adoc
  src/main/docs/guide/httpServer/uploads.adoc
  src/main/docs/guide/httpServer/websocket/websocketClient.adoc
  src/main/docs/guide/httpServer/websocket/websocketServer.adoc
  src/main/docs/guide/i18n/bundle.adoc
  src/main/docs/guide/ioc/annotationMetadata.adoc
  src/main/docs/guide/ioc/introspection.adoc
  src/main/docs/guide/ioc/introspection/makingABeanAvailableForIntrospection.adoc
Labels: type: docs

#9833 KSP: skip `ExecutableVisitor` warning for default parameters
  core-processor/src/main/java/io/micronaut/context/visitor/ExecutableVisitor.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug, lang: kotlin

#9830 [core] Update common files for branch 4.1.x
  .github/workflows/release.yml
Labels: relates-to: build

#9832 KSP: performance improvements
  http-validation/src/main/java/io/micronaut/validation/routes/RouteValidationVisitor.java
  http-validation/src/main/java/io/micronaut/validation/routes/rules/MissingParameterRule.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/KotlinReconstructionSpec.groovy
Labels: type: improvement

#9809 DefaultApplicationContext should close an Environment that it created
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/test/java/io/micronaut/context/DefaultApplicationContextTest.java
Labels: type: improvement

#9849 Reset read timeout on client pool connection acquisition
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/ResettableReadTimeoutHandler.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
Labels: type: bug

#9851 Fix status route resolution
  http-client/src/test/groovy/io/micronaut/http/client/InvalidStatusSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
  router/src/main/java/io/micronaut/web/router/DefaultStatusRouteInfo.java
  router/src/main/java/io/micronaut/web/router/Router.java
  router/src/main/java/io/micronaut/web/router/StatusRoute.java
  router/src/main/java/io/micronaut/web/router/StatusRouteInfo.java
  router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java
Labels: type: bug

#9793 Update kotlin to 1.9.10
  buildSrc/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/AbstractKotlinCompilation.kt
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/Ksp.kt
  inject-kotlin/build.gradle
  settings.gradle
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
  test-suite-kotlin-ksp/build.gradle
  test-suite-kotlin/src/test/kotlin/io/micronaut/core/beans/KotlinBeanIntrospectionSpec.kt
Labels: type: dependency-upgrade

#9834 Correct how maps/sets are initialized with a correct size
  aop/src/main/java/io/micronaut/aop/InvocationContext.java
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/DefaultOriginatingElements.java
  core/src/main/java/io/micronaut/core/reflect/InstantiationUtils.java
  core/src/main/java/io/micronaut/core/type/DefaultArgument.java
  core/src/main/java/io/micronaut/core/type/ReturnType.java
  discovery-core/src/main/java/io/micronaut/discovery/cloud/ComputeInstanceMetadataResolverUtils.java
  function-client/src/main/java/io/micronaut/function/client/DefaultFunctionDiscoveryClient.java
  http-client-core/src/main/java/io/micronaut/http/client/DefaultLoadBalancerResolver.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyHttpParameters.java
  http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
  http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstGenericUtils.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/GenericUtils.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
  inject/src/main/java/io/micronaut/inject/annotation/MutableAnnotationMetadata.java
  json-core/src/main/java/io/micronaut/json/bind/JsonBeanPropertyBinder.java
  management/src/main/java/io/micronaut/management/health/aggregator/DefaultHealthAggregator.java
Labels: type: improvement

#9808 split assignment in multiple lines
  json-core/src/main/java/io/micronaut/json/convert/JsonConverterRegistrar.java
Labels: type: improvement

#9854 fix: remove duplicated ExitCode.OOM_ERROR
  inject-kotlin-test/src/main/kotlin/io/micronaut/annotation/processing/test/support/AbstractKotlinCompilation.kt
Labels: type: improvement

#9856 checkstlye: wrong order
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  jackson-databind/src/main/java/io/micronaut/jackson/databind/JacksonDatabindMapper.java
Labels: type: improvement

#9858 test: GraalVM logging
  settings.gradle
  test-suite-logback-graalvm/build.gradle
  test-suite-logback-graalvm/src/test/java/example/micronaut/LoggingTest.java
  test-suite-logback-graalvm/src/test/resources/logback.xml
Labels: type: improvement

#9859 Fix logging with logger.config and no levels
  context/src/main/java/io/micronaut/logging/PropertiesLoggingLevelsConfigurer.java
  management/src/test/groovy/io/micronaut/management/endpoint/beans/BeansEndpointSpec.groovy
  test-suite-logback-external-configuration/src/test/groovy/io/micronaut/logback/ExternalConfigurationSpec.groovy
Labels: type: bug

#9838 Improve default annotation values
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationDefaultValuesProvider.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/annotation/MyBean.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/TopLevel2.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataSupport.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
Labels: type: improvement

#9875 Add DefaultHttpClient constructor with ssl builder
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
Labels: type: enhancement

#9872 Implement JsonAnyGetter for BeanIntrospectionModule
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  jackson-databind/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy
Labels: type: bug

#9863 [core] Update common files for branch 4.1.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#9891 HTTP Client - detect charset from request or response body media type
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/EncodingTest.java
  http/src/main/java/io/micronaut/http/body/RawMessageBodyHandlerRegistry.java
Labels: type: bug

#9893 fix health monitor task
  management/src/main/java/io/micronaut/management/health/monitor/HealthMonitorTask.java
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthMonitorTaskSpec.groovy
Labels: type: bug

#9904 Minor fix: typo in Factory javadoc
  inject/src/main/java/io/micronaut/context/annotation/Factory.java
Labels: type: docs

#9903 ci: setup-graalvm to v1.1.4
  .github/workflows/gradle.yml
Labels: relates-to: build

#9910 Delegate `isAbstract()` and `isSuspend()` to target executable method
  inject/src/main/java/io/micronaut/inject/DelegatingExecutableMethod.java
  inject/src/test/groovy/io/micronaut/inject/DefaultBeanDefinitionMethodReferenceSpec.groovy
Labels: type: bug

#9918 Cherrypicks Issue 9905 websphere deploy war (#9906)
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/main/java/io/micronaut/core/io/service/ServiceScanner.java
  core/src/test/groovy/io/micronaut/core/io/IOUtilsSpec.groovy
Labels: type: bug

#9923 fix builders with private or protected constructors
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/BeanIntrospectionBuilderSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/TestBuildMe7.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/TestBuildMe8.java
Labels: type: bug

#9926 Fix handling of builders with inheritance
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject-java-test/build.gradle
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/BeanIntrospectionBuilderSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/SubBuilder.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/SuperBuilder.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
Labels: type: bug

#9922 avoid unnecessary calls to ConcurrentLinkedDeque.size()
  http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
Labels: type: improvement
