Repository micronaut-projects/micronaut-core, pull requests merged in 2023-07, with the labels that each got.

#9535 fix: txt/plain possible for BigDecimal
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/textplain/TxtPlainBigDecimalTest.java
  http/src/main/java/io/micronaut/http/body/DynamicMessageBodyWriter.java
Labels: type: bug

#9549 fix IllegalArgumentException: Duplicate key with KSP and introspections with ConfigurationBuilder
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/configproperties/ConfigurationPropertiesSpec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/TeamConfiguration.kt
Labels: type: bug

#9548 Document exception if parent of each bean lacks name qualifier
  inject-java/src/test/groovy/io/micronaut/inject/foreach/EachBeanRequiresQualifierSpec.groovy
  inject/src/main/java/io/micronaut/context/annotation/EachBean.java
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/config/eachBean.adoc
Labels: type: docs

#9541 Document module `io.micronaut:micronaut-jackson-databind`
  src/main/docs/guide/httpServer/jsonBinding.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#9553 KSP: Visit synthetic properties in factories with advice
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/processing/FactoryBeanElementCreator.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyAccessorMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinSimplePropertyElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/compile/AroundCompileSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/compile/IntroductionCompileSpec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/aop/compile/MyClient.kt
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/aop/simple/ArgMutatingInterceptor.kt
Labels: type: bug

#9555 Add propagated context to the reactive controller methods Reactor context
  context-propagation/src/test/groovy/io/micronaut/context/propagation/MDCSpec3.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec1.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec10.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec2.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec3.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec4.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec5.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec6.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec7.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec8.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec9.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: improvement

#9558 Correct constructor copy ASM
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/concopy/ConstructorCopySpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/concopy/Message.java
Labels: type: bug

#9565 Update upgrading title
  src/main/docs/guide/toc.yml
Labels: type: docs

#9567 Fix incorrect links in User Guide
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/serverlessFunctions/awsLambda.adoc
Labels: type: docs

#9454 [core] Update common files for branch 4.0.x
  .github/workflows/release.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#9512 Fix CORS when used with API versioning.
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsVersionSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CrossOriginTest.java
  router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
Labels: type: bug

#9568 Update filterPatterns.adoc
  src/main/docs/guide/httpServer/filters/filterPatterns.adoc
Labels: type: docs

#9586 doc: fix Kotlin Coroutines embedded snippet
  src/main/docs/guide/languageSupport/kotlin/coroutines.adoc
Labels: type: docs

#9554 Context propagation documentation
  core-reactive/src/main/java/io/micronaut/core/async/propagation/ReactorPropagation.java
  http-validation/src/main/java/io/micronaut/validation/routes/FilterVisitor.java
  http/src/main/java/io/micronaut/http/annotation/RequestFilter.java
  http/src/main/java/io/micronaut/http/annotation/ResponseFilter.java
  src/main/docs/guide/appendix/breaks.adoc
  src/main/docs/guide/contextPropagation.adoc
  src/main/docs/guide/contextPropagation/httpFilterContextPropagation.adoc
  src/main/docs/guide/contextPropagation/reactorContextPropagation.adoc
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/languageSupport/kotlin/kotlinContextPropagation.adoc
  src/main/docs/guide/toc.yml
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/beans/User.kt
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcFilter.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcFilterSpec.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcLegacyFilter.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcLegacyFilterSpec.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcPropagationContext.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcService.java
  test-suite/src/test/java/io/micronaut/docs/propagation/MdcServiceSpec.java
Labels: type: docs

#9601 test: test custom createMethod
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/BeanIntrospectionBuilderSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/builder/TestBuildMe4.java
Labels: type: improvement

#9599 doc: Split introspection documentation
  src/main/docs/guide/ioc/introspection/accessKind.adoc
  src/main/docs/guide/ioc/introspection/atCreator.adoc
  src/main/docs/guide/ioc/introspection/atIntrospected.adoc
  src/main/docs/guide/ioc/introspection/beanWrapperApi.adoc
  src/main/docs/guide/ioc/introspection/introspectExistingAnnotations.adoc
  src/main/docs/guide/ioc/introspection/introspectedAccessorsStyle.adoc
  src/main/docs/guide/ioc/introspection/introspectedAnnotationOnAConfigurationClass.adoc
  src/main/docs/guide/ioc/introspection/introspectionBuilders.adoc
  src/main/docs/guide/ioc/introspection/introspectionEnums.adoc
  src/main/docs/guide/ioc/introspection/jacksonAndBeanIntrospection.adoc
  src/main/docs/guide/ioc/introspection/staticAtCreator.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/introspection/Person.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/introspection/PersonSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/introspection/Person.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/introspection/PersonSpec.kt
  test-suite/src/test/java/io/micronaut/docs/ioc/introspection/Person.java
  test-suite/src/test/java/io/micronaut/docs/ioc/introspection/PersonTest.java
Labels: type: docs

#9603 Add @Mapper example to docs
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  src/main/docs/guide/ioc/beanMappers.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/ContactEntity.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/ContactForm.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/ContactMappers.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/SimpleMapperSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactEntity.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactForm.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactMappers.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/SimpleMapperSpec.kt
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/ContactEntity.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/ContactForm.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/ContactMappers.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/SimpleMapperSpec.java
Labels: type: docs

#9624 Fix reentrancy in PipeliningServerHandler#writeSome
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: bug

#9623 Fix introspection docs
  src/main/docs/guide/ioc/introspection.adoc
  src/main/docs/guide/ioc/introspection/introspectExistingAnnotations.adoc
  src/main/docs/guide/ioc/introspection/introspectionBuilders.adoc
  src/main/docs/guide/ioc/introspection/introspectionEnums.adoc
  src/main/docs/guide/ioc/introspection/makingABeanAvailableForIntrospection.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#9590 [core] Update common files for branch 4.0.x
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#9628 Fix correct dependency in code snippet
  src/main/docs/guide/appendix/breaks.adoc
Labels: type: docs

#9598 Allow fallback body conversion
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ImmediateByteBody.java
  http-server-tck/build.gradle.kts
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ErrorHandlerTest.java
  src/main/docs/guide/httpServer/errorHandling/localErrorHandling.adoc
Labels: type: improvement

#9634 move Async validation to processor module
  context/build.gradle
  context/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  core-processor/build.gradle
  core-processor/src/main/java/io/micronaut/validation/visitor/async/AsyncTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/validation/visitor/package-info.java
  core-processor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: improvement

#9631 Allow specifying inheritance handling on core nullable annotations
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/CoreNonNullTransformer.java
  core-processor/src/main/java/io/micronaut/inject/annotation/internal/CoreNullableTransformer.java
  core/src/main/java/io/micronaut/core/annotation/NonNull.java
  core/src/main/java/io/micronaut/core/annotation/Nullable.java
  inject-java-test/src/test/groovy/io/micronaut/inject/annotation/InheritedNullableAnnotationSpec.groovy
Labels: type: enhancement

#9633 fix case where property placeholders and expressions are used in the same annotation
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  inject-java/src/test/groovy/io/micronaut/expressions/EnvironmentAccessExpressionsSpec.groovy
  inject/src/main/java/io/micronaut/inject/annotation/EnvironmentAnnotationValue.java
  inject/src/main/java/io/micronaut/inject/annotation/EvaluatedAnnotationValue.java
Labels: type: bug

#9638 Bump micronaut-gcp to 4.11.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9636 Bump micronaut-aws to 3.18.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9643 Bump micronaut-azure to 4.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9644 Bump micronaut-redis to 5.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9648 build: Netty 4.1.96
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
