Repository micronaut-projects/micronaut-core, pull requests merged in 2023-04, with the labels that each got.

#9050 Bump micronaut-azure to 3.10.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9046 Bump micronaut-kubernetes to 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9058 Bump micronaut-gcp to 4.10.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9055 build: Kotlin 1.8.20
  gradle/libs.versions.toml
  src/main/docs/guide/introduction/whatsNew.adoc
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
Labels: lang: kotlin, type: dependency-upgrade

#9056 build: add Micronaut Chatbots BOM
  gradle/libs.versions.toml
Labels: relates-to: build

#9065 Bump micronaut-aws to 3.16.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9066 Bump micronaut-micrometer to 4.8.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9047 Fix broken link to checkstyle issue img
  CONTRIBUTING.md
Labels: type: docs

#8946 Add ability to disable log in environments
  core/src/main/java/io/micronaut/core/io/scan/ClassPathResourceLoader.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/AccessLogFormatParser.java
  inject/src/main/java/io/micronaut/context/env/AbstractPropertySourceLoader.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
  inject/src/main/java/io/micronaut/context/env/yaml/YamlPropertySourceLoader.java
Labels: type: improvement

#8729 Bump micronaut-jms to 2.2.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9068 Bump micronaut-grpc to 3.6.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9082 Bump micronaut-security to 3.10.1
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9084 Bump micronaut-aws to 3.10.10
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9064 Update to Jackson 2.14.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9088 CRaC 1.2.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9061 Idea(8855)/service health indicator
  management/build.gradle
  management/src/main/java/io/micronaut/management/health/indicator/client/ServiceHttpClientHealthIndicator.java
  management/src/test/groovy/io/micronaut/management/health/indicator/client/ServiceHttpClientHealthIndicatorSpec.groovy
Labels: type: enhancement

#9100 Bump micronaut-aws to 3.17.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#8608 Load ApplicationContextConfigurer with passed classloader instead of the class one
  inject/src/main/java/io/micronaut/context/ApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/test/groovy/io/micronaut/context/ApplicationContextBuilderSpec.groovy
  inject/src/test/resources/test-meta-inf/META-INF/micronaut/io.micronaut.context.ApplicationContextConfigurer/io.micronaut.context.TestContextConfigurer
Labels: type: improvement

#9101 Bump micronaut-elasticsearch to 4.4.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9094 Support for conditional routing
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/FullHttpStackBenchmark.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/access/ElementMethodCall.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/access/EnvironmentAccess.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/conditional/TernaryExpression.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/literal/StringLiteral.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ExpressionTest.java
  http/src/main/java/io/micronaut/http/annotation/CustomHttpMethod.java
  http/src/main/java/io/micronaut/http/annotation/Delete.java
  http/src/main/java/io/micronaut/http/annotation/Get.java
  http/src/main/java/io/micronaut/http/annotation/Head.java
  http/src/main/java/io/micronaut/http/annotation/Options.java
  http/src/main/java/io/micronaut/http/annotation/Patch.java
  http/src/main/java/io/micronaut/http/annotation/Post.java
  http/src/main/java/io/micronaut/http/annotation/Put.java
  http/src/main/java/io/micronaut/http/annotation/RouteCondition.java
  http/src/main/java/io/micronaut/http/annotation/Trace.java
  http/src/main/java/io/micronaut/http/expression/RequestConditionContext.java
  http/src/main/java/io/micronaut/http/filter/FilterRunner.java
  inject-groovy/src/test/groovy/io/micronaut/expressions/ContextMethodCallsExpressionsSpec.groovy
  inject-java/src/test/groovy/io/micronaut/expressions/ContextPropertyAccessExpressionsSpec.groovy
  router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
  src/main/docs/guide/config/evaluatedExpressions.adoc
Labels: type: enhancement

#9118 bug: SslConfiguration::setProtocol
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/BinaryChatClientWebSocket.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/BinaryChatServerWebSocket.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/websocket/BinaryWebSocketSpec.groovy
  http/src/main/java/io/micronaut/http/ssl/SslConfiguration.java
  http/src/test/groovy/io/micronaut/http/ssl/SslConfigurationSpec.groovy
Labels: type: bug

#9123 Allow access to 'this' in expressions / support introspections
  aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java
  context/src/main/java/io/micronaut/scheduling/processor/ScheduledMethodProcessor.java
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/expressions/context/DefaultExpressionCompilationContext.java
  core-processor/src/main/java/io/micronaut/expressions/context/DefaultExpressionCompilationContextFactory.java
  core-processor/src/main/java/io/micronaut/expressions/context/ExpressionCompilationContext.java
  core-processor/src/main/java/io/micronaut/expressions/context/ExpressionCompilationContextFactory.java
  core-processor/src/main/java/io/micronaut/expressions/context/ExtensibleExpressionCompilationContext.java
  core-processor/src/main/java/io/micronaut/expressions/parser/SingleEvaluatedEvaluatedExpressionParser.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/access/ThisAccess.java
  core-processor/src/main/java/io/micronaut/expressions/parser/token/TokenType.java
  core-processor/src/main/java/io/micronaut/expressions/parser/token/Tokenizer.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractAnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanConfigurationWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/EvaluatedExpressionProcessor.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  core/src/main/java/io/micronaut/core/expressions/ExpressionEvaluationContext.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalReflectionMetadataWriter.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  inject-groovy-test/src/main/groovy/io/micronaut/ast/transform/test/AbstractEvaluatedExpressionsSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
  inject-groovy/src/test/groovy/io/micronaut/expressions/ContextPropertyAccessExpressionsSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractEvaluatedExpressionsSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/expressions/ThisExpressionSpec.groovy
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/beans/BeanDefinitionProcessor.kt
  inject/src/main/java/io/micronaut/context/expressions/ConfigurableExpressionEvaluationContext.java
  inject/src/main/java/io/micronaut/context/expressions/DefaultExpressionEvaluationContext.java
  inject/src/main/java/io/micronaut/inject/annotation/EvaluatedAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/EvaluatedAnnotationValue.java
  inject/src/main/java/io/micronaut/inject/annotation/MappingAnnotationMetadataDelegate.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  src/main/docs/guide/config/evaluatedExpressions.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/expressions/ExampleJob.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/expressions/ExampleJobSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/expressions/ExampleJob.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/expressions/ExampleJobTest.kt
  test-suite/src/test/java/io/micronaut/docs/expressions/ExampleJob.java
  test-suite/src/test/java/io/micronaut/docs/expressions/ExampleJobTest.java
Labels: type: improvement

#9116 [core] Update common files for branch 4.0.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#9108 Bump micronaut-maven-plugin to 4.0.0-M1
  gradle.properties
Labels: type: dependency-upgrade

#9126 Fix SingleResult was unintentionally initialized at build time
  core-reactive/src/main/resources/META-INF/native-image/io.micronaut/micronaut-core-reactive/native-image.properties
Labels: type: bug, relates-to: graal

#9111 tck: Write length and first 10 bytes if bytearray assertion fails
  http-tck/src/main/java/io/micronaut/http/tck/BodyAssertion.java
  inject-groovy/src/test/groovy/io/micronaut/expressions/ArrayMethodsExpressionsSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/expressions/ContextPropertyAccessExpressionsSpec.groovy
Labels: type: improvement

#9136 Bump micronaut-test to 4.0.0-M2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9090 io_uring support
  gradle/libs.versions.toml
  http-netty/build.gradle
  http-netty/src/main/java/io/micronaut/http/netty/channel/IoUringAvailabilityCondition.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/IoUringEventLoopGroupFactory.java
  src/main/docs/guide/httpServer/serverConfiguration.adoc
Labels: type: enhancement

#9138 Re-enable PTS and Test Distribution for Kotlin
  test-suite-kotlin/build.gradle
Labels: relates-to: build

#9145 [core] Update common files for branch 4.0.x
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#9156 Bump micronaut-sql to 5.0.0-M4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9163 Support for Comparable types in expressions
  core-processor/src/main/java/io/micronaut/expressions/parser/SingleEvaluatedEvaluatedExpressionParser.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/ExpressionNode.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/access/ContextElementAccess.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/BinaryOperator.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/ComparablesComparisonOperation.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/NumericComparisonOperation.java
  core-processor/src/main/java/io/micronaut/expressions/parser/ast/operator/binary/RelationalOperator.java
  inject-groovy-test/src/main/groovy/io/micronaut/ast/transform/test/AbstractEvaluatedExpressionsSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/expressions/OperatorExpressionsSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractEvaluatedExpressionsSpec.groovy
  inject-java/src/test/groovy/io/micronaut/expressions/OperatorExpressionSpec.groovy
  src/main/docs/guide/config/evaluatedExpressions.adoc
Labels: type: improvement

#9167 Bump micronaut-gcp to 4.10.1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#9129 Fix disable log in environments
  core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
Labels: type: improvement

#9174 Bump micronaut-maven-plugin to 4.0.0-M2
  gradle.properties
Labels: type: dependency-upgrade
