Repository micronaut-projects/micronaut-core, pull requests merged in 2024-03, with the labels that each got.

#10576 KSP: Allow to detect repeatable annotations using reflection
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/AddsRepeatableAnnotationSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/AddsUnseenInnerRepeatableAnnotationSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/AddsUnseenRepeatableAnnotationSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/MyRequirements.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/MyRequirements2.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/MyRequires.java
  inject-kotlin/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#10582 Include space in cookie separator
  http-client/src/main/java/io/micronaut/http/client/netty/NettyClientHttpRequest.java
  http-client/src/test/groovy/io/micronaut/http/client/CookieHeaderSpec.groovy
Labels: type: bug

#10581 Support accessing enum values annotations
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core/src/main/java/io/micronaut/core/beans/EnumBeanIntrospection.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/inject/beans/AbstractEnumBeanIntrospectionAndReference.java
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
Labels: type: improvement

#10584 Allow suppressing internal warnings
  core-processor/src/main/java/io/micronaut/context/visitor/InternalApiTypeElementVisitor.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  core/src/main/java/io/micronaut/core/annotation/Experimental.java
  core/src/main/java/io/micronaut/core/annotation/Internal.java
Labels: type: improvement

#10579 Fix out of order writes with async reactive calls
  http-client/src/main/java/io/micronaut/http/client/netty/ReactiveClientWriter.java
  http-netty/src/main/java/io/micronaut/http/netty/EventLoopFlow.java
  http-netty/src/test/groovy/io/micronaut/http/netty/EventLoopFlowSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormRouteCompleter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
Labels: type: bug

#10590 Retain client response content on parsing failure
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/test/groovy/io/micronaut/http/client/JsonSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/FullNettyClientHttpResponseSpec.groovy
Labels: type: bug

#10597 Don't call out to micronaut-core from micronaut-graal
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
Labels: lang: kotlin, relates-to: graal

#10589 Add prefer-openssl config option
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyTlsUtils.java
  http-server-netty/build.gradle
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ssl/RequestCertificateSpec2.groovy
  http/src/main/java/io/micronaut/http/ssl/SslConfiguration.java
Labels: type: improvement

#10599 Revert "Don't call out to micronaut-core from micronaut-graal"
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
Labels: lang: kotlin, relates-to: graal

#10441 Minor HTTP performance improvements
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultHttpCompressionStrategy.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpCompressionStrategy.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/CompressionSpec.groovy
  jackson-databind/src/main/java/io/micronaut/jackson/databind/JacksonDatabindMapper.java
Labels: type: improvement

#10607 Update listener.adoc
  src/main/docs/guide/httpServer/serverConfiguration/listener.adoc
Labels: type: bug, type: docs

#10610 Manage Kotlin plugins in the catalog
  aop/build.gradle
  buildSrc/build.gradle
  context-propagation/build.gradle
  core-reactive/build.gradle
  gradle/libs.versions.toml
  http/build.gradle
  inject-kotlin-test/build.gradle
  inject-kotlin/build.gradle
  settings.gradle
  test-suite-kotlin-ksp/build.gradle
  test-suite-kotlin/build.gradle
Labels: relates-to: build

#10611 Update title and description
  gradle.properties
Labels: type: docs

#10596 Http2FrameListener-based HTTP/2 server handler implementation
  core-reactive/src/main/java/io/micronaut/core/async/publisher/DelayedSubscriber.java
  core-reactive/src/test/groovy/io/micronaut/core/async/publisher/DelayedSubscriberSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/EmbeddedTestUtil.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpToHttpsRedirectHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyRequestLifecycle.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyServerCustomizer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/BlockingWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/OutboundAccess.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/RequestHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/EmbeddedTestUtil.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/Http2ServerHandlerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/AccessLogSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ServerPushSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/FilterProxyTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/cors/CorsSimpleRequestTest.java
  http-tck/src/main/java/io/micronaut/http/tck/EmbeddedHttp2ServerUnderTestProvider.java
  http-tck/src/main/java/io/micronaut/http/tck/EmbeddedServerUnderTest.java
  http-tck/src/main/java/io/micronaut/http/tck/ServerUnderTest.java
  settings.gradle
  test-suite-http2-server-tck-netty/build.gradle
  test-suite-http2-server-tck-netty/src/test/java/io/micronaut/http/server/tck/netty/tests/NettyHttpServerTestSuite.java
  test-suite-http2-server-tck-netty/src/test/resources/META-INF/services/io.micronaut.http.tck.ServerUnderTestProvider
  test-suite-http2-server-tck-netty/src/test/resources/logback.xml
  test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy
  test-suite/src/test/groovy/io/micronaut/http2/Http2AccessLoggerSpec.groovy
Labels: type: improvement

#10622 specify default value in a constant
  http-netty/src/main/java/io/micronaut/http/netty/configuration/NettyGlobalConfiguration.java
Labels: type: docs

#10629 Fix build adding jacksonDatabind to http2 tck tests
  test-suite-http-server-tck-netty/build.gradle
  test-suite-http2-server-tck-netty/build.gradle
Labels: relates-to: build

#10626 Build HTTP request in declarative client Publisher
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/test/groovy/io/micronaut/http/client/retry/HttpClientJsonRetrySpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/retry/HttpClientRetrySpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/retry/HttpClientRetryWithFallbackSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/retry/HttpClientWithCircuitBreakerSpec.groovy
Labels: type: bug

#10609 Let event loop threads implement reactor NonBlocking
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/HttpProxySpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyThreadFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/configuration/NettyGlobalConfiguration.java
  http-server-netty/src/test/groovy/io/micronaut/http/netty/channel/NettyThreadFactorySpec.groovy
Labels: type: improvement

#10640 Bump micronaut-kafka to 4.5.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#10655 Mark fd-based EpollServerDomainSocketChannel as active
  http-netty/src/main/java/io/micronaut/http/netty/channel/EpollEventLoopGroupFactory.java
Labels: type: bug

#10660 Implement de/compression in Http2ServerHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Compressor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/CompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/DecompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/Http2CompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/Http3CompressionSpec.groovy
Labels: type: improvement

#10659 remove DefaultCookieDecoder
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyLaxClientCookieEncoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyLaxServerCookieDecoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyServerCookieEncoderSpec.groovy
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ClientCookieEncoder
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieDecoder
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieEncoder
  http/src/test/java/io/micronaut/http/cookie/DefaultClientCookieEncoderTest.java
  http/src/test/java/io/micronaut/http/cookie/DefaultServerCookieDecoderTest.java
  http/src/test/java/io/micronaut/http/cookie/DefaultServerCookieEncoderTest.java
Labels: type: bug

#10664 test: Use ApplicationContext.run(EmbeddedServer
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/SslSelfSignedSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/ProxyInterceptFullResponseSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/ReadTimeoutSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/SslSelfSignedSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/SslStaticCertSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/BlockingCrudSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/BlockingFallbackSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/BlockingPojoCrudSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/ClientFilterSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/NullableCrudSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/ParameterSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/aop/PathVariableSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/sse/ServerSentEventProxyingSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/CompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/Http2CompressionSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/upload/browser/UploadBrowserSpec.groovy
  test-suite-http-client-jdk-ssl/src/test/groovy/io/micronaut/http/client/jdk/SslStaticCertSpec.groovy
Labels: type: improvement

#10663 h2c support for new Http2ServerHandler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
Labels: type: improvement
