Repository micronaut-projects/micronaut-core, pull requests merged in 2024-10, with the labels that each got.

#11219 Fixed file name and links
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationGoogleCloudSecretManager.adoc
  src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationPubSub.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#11225 Correct routing check
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: improvement

#11226 Make `MediaType` comparable
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy
Labels: type: improvement

#10118 Remove warning about Logbook bug
  gradle/libs.versions.toml
  src/main/docs/guide/httpServer/serverConfiguration/nettyClientPipeline.adoc
  test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyClientCustomizerSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy
Labels: type: docs

#11239 KSP: Properly update current round resolver in all helper classes
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinNativeElementsHelper.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
Labels: type: bug

#11235 Docs: Adding KSP support
  src/main/docs/guide/appendix/architecture/compilerArch.adoc
Labels: type: docs

#11242 Update propertySource.adoc
  src/main/docs/guide/config/propertySource.adoc
Labels: type: docs

#11245 Fix link to javadoc of HTTP annotation and Micronaut Context Package
  src/main/docs/guide/appendix/architecture/httpServerArch.adoc
  src/main/docs/guide/appendix/architecture/iocArch.adoc
Labels: type: docs

#11243 fix link to javadoc of AST package
  src/main/docs/guide/appendix/architecture/annotationArch.adoc
  src/main/docs/guide/appendix/architecture/compilerArch.adoc
Labels: type: docs

#11216 Add ability to disable normalization for property keys in EachProperty
  core/src/main/java/io/micronaut/core/value/PropertyCatalog.java
  core/src/main/java/io/micronaut/core/value/PropertyResolver.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/eachbeanparameter/EachBeanParameterSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/eachbeanparameter/EachPropertyPropertiesDefault.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/eachbeanparameter/EachPropertyPropertiesGenerated.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/eachbeanparameter/EachPropertyPropertiesNormalized.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/eachbeanparameter/EachPropertyPropertiesRaw.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/annotation/EachProperty.java
  inject/src/main/java/io/micronaut/context/env/ConfigurationPath.java
  inject/src/main/java/io/micronaut/context/env/DefaultConfigurationPath.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
Labels: type: enhancement

#11187 fix(router): get 'uri' mapping default value if no 'uris' found in http annotation
  http-client/src/test/groovy/io/micronaut/http/client/HttpUriMappingSpec.groovy
  router/src/main/java/io/micronaut/web/router/AnnotatedMethodRouteBuilder.java
Labels: type: improvement

#11249 Correct checking for internal/experimental API usage
  core-processor/src/main/java/io/micronaut/context/visitor/InternalApiTypeElementVisitor.java
  inject-java-test/src/main/java/io/micronaut/annotation/processing/test/JavaParser.java
  inject-java/src/test/groovy/io/micronaut/visitors/AbstractInternalClass.java
  inject-java/src/test/groovy/io/micronaut/visitors/AbstractInternalMethodClass.java
  inject-java/src/test/groovy/io/micronaut/visitors/InternalVisitor1Spec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/InternalVisitor2Spec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/InternalVisitor3Spec.groovy
Labels: type: bug

#11240 Update introspection documentation
  src/main/docs/guide/appendix/architecture/introspectionArch.adoc
Labels: type: docs

#11227 RawHttpClient
  http-client-core/src/main/java/io/micronaut/http/client/RawHttpClient.java
  http-client-core/src/main/java/io/micronaut/http/client/RawHttpClientFactory.java
  http-client-core/src/main/java/io/micronaut/http/client/RawHttpClientFactoryResolver.java
  http-client-core/src/main/java/io/micronaut/http/client/RawHttpClientRegistry.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/RawTest.java
  http-client/src/main/java/io/micronaut/http/client/netty/BlockHint.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/Http1ResponseHandler.java
  http-client/src/main/java/io/micronaut/http/client/netty/MutableHttpRequestWrapper.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyHttpClientFactory.java
  http-client/src/main/java/io/micronaut/http/client/netty/RawHttpRequestWrapper.java
  http-client/src/main/resources/META-INF/services/io.micronaut.http.client.RawHttpClientFactory
  http-netty/src/main/java/io/micronaut/http/netty/NettyHttpRequestBuilder.java
  test-suite-http-client-tck-jdk/src/test/java/io/micronaut/http/client/tck/jdk/tests/JdkHttpMethodTests.java
Labels: type: improvement

#11267 Fix controller `@Body Object` parameters
  .github/workflows/gradle.yml
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/body/BodyConversionSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
  http/src/main/java/io/micronaut/http/body/TypedMessageBodyReader.java
Labels: type: bug

#11272 feat: add FilterBodyParser API
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/forms/FormUrlEncodedBodyInRequestFilterTest.java
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/filter/DefaultFilterBodyParser.java
  http-server/src/main/java/io/micronaut/http/server/filter/FilterBodyParser.java
  http-server/src/main/java/io/micronaut/http/server/filter/package-info.java
  http/build.gradle
  http/src/main/java/io/micronaut/http/form/FormConfiguration.java
  http/src/main/java/io/micronaut/http/form/FormConfigurationProperties.java
  http/src/main/java/io/micronaut/http/form/FormUrlEncodedDecoder.java
  http/src/main/java/io/micronaut/http/uri/DefaultFormUrlEncodedDecoder.java
  http/src/main/java/io/micronaut/http/uri/QueryStringDecoder.java
  http/src/test/java/io/micronaut/http/form/FormConfigurationTest.java
  http/src/test/java/io/micronaut/http/form/FormConfigurationViaPropertyTest.java
  http/src/test/java/io/micronaut/http/form/FormUrlEncodedDecoderTest.java
  src/main/docs/guide/httpServer/byteBody.adoc
Labels: type: enhancement

#11271 javadoc: correct constructor
  jackson-databind/src/main/java/io/micronaut/jackson/codec/JsonMediaTypeCodec.java
  jackson-databind/src/main/java/io/micronaut/jackson/codec/JsonStreamMediaTypeCodec.java
Labels: type: docs

#11277 [core] Update common files for branch 4.7.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#11280 Add ByteBody.move
  http-netty/src/main/java/io/micronaut/http/netty/body/AvailableNettyByteBody.java
  http-netty/src/main/java/io/micronaut/http/netty/body/StreamingNettyByteBody.java
  http-netty/src/test/groovy/io/micronaut/http/netty/body/AvailableNettyByteBodySpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/body/StreamingNettyByteBodySpec.groovy
  http/src/main/java/io/micronaut/http/body/ByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/AvailableByteArrayBody.java
  http/src/main/java/io/micronaut/http/body/stream/InputStreamByteBody.java
  http/src/test/groovy/io/micronaut/http/body/stream/AvailableByteArrayBodySpec.groovy
  http/src/test/groovy/io/micronaut/http/body/stream/InputStreamByteBodySpec.groovy
Labels: type: improvement

#11285 doc: proceed with RequestFilter and CompletableFuture
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterCompletableFutureFutureProceedTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterCompletionStageFutureProceedTest.java
  http/src/main/java/io/micronaut/http/annotation/RequestFilter.java
  src/main/docs/guide/httpServer/filters/filtermethods/filtermethodproceed.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#11291 Postpone to next round if annotation class is resolved. Fixes #11287
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationClassValue.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  gradle/libs.versions.toml
  inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  test-suite/build.gradle
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
  test-suite/src/test/java/io/micronaut/test/lombok/RobotEntity.java
Labels: type: bug
