Repository micronaut-projects/micronaut-core, pull requests merged in 2024-06, with the labels that each got.

#10740 [core] Update common files for branch 4.5.x
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#10874 [core] Update common files for branch 4.5.x
  .github/renovate.json
  .github/workflows/release.yml
Labels: relates-to: build

#10877 Delay scheduling until startup
  context/src/main/java/io/micronaut/scheduling/processor/ScheduledMethodProcessor.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: improvement

#10890 Correct clients getting shutdown by request scope
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#10892 Fix race condition in task scheduling
  context/src/main/java/io/micronaut/scheduling/processor/ScheduledMethodProcessor.java
Labels: type: bug

#10887 [core] Update common files for branch 4.5.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#10897 Use a different logger for NettyByteBody
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/NettyByteBody.java
Labels: type: improvement

#10904 Ensuring the deserialization has access to the ServerRequestContext
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/JsonBodyBindingSpec.groovy
Labels: type: bug

#10906 Apply code improvements suggested by IDE
  http/src/main/java/io/micronaut/http/uri/DefaultUriBuilder.java
  http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
Labels: type: improvement

#10908 Map of beans should always use bean definition to extract the name
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/DefaultMyService.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MainService.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MyBarService.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MyFooService.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MyService.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MyServiceConsumer.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/mapof/MyServiceConsumerSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#10927 Add Kotlin+KSP+Jackson nullable tests
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/jackson/JacksonNullableFailOnMissingTest.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/jackson/JacksonNullableTest.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/jackson/NonNullConstructorDto.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/jackson/NullConstructorDto.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/jackson/NullPropertyDto.kt
Labels: type: improvement

#10923 [core] Update common files for branch 4.5.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
