Repository micronaut-projects/micronaut-core, pull requests merged in 2024-01, with the labels that each got.

#10257 Downgrade HTTP client log message
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
Labels: type: improvement

#10324 Do not include malformed URI in error message
  http-server/src/main/java/io/micronaut/http/server/exceptions/URISyntaxHandler.java
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/urisyntax/MalformedUriSpec.groovy
Labels: type: improvement

#10323 Don't log decompression exception
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
Labels: type: bug

#10315 Avoid having `TypeConverter` defined as beans
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsOriginConverterEnabledSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/HttpServerTypeConvertersRegistrar.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConverter.java
  http-server/src/main/resources/META-INF/native-image/io.micronaut/micronaut-http-server/native-image.properties
  http-server/src/main/resources/META-INF/services/io.micronaut.core.convert.TypeConverterRegistrar
  http/src/main/java/io/micronaut/http/HttpTypeConverterRegistrar.java
  http/src/main/java/io/micronaut/http/cookie/SameSiteConverter.java
  http/src/main/resources/META-INF/services/io.micronaut.core.convert.TypeConverterRegistrar
  src/main/docs/guide/config/customTypeConverter.adoc
  src/main/docs/guide/httpServer/binding.adoc
Labels: type: improvement

#10325 Publish service ready / stopped in consistent order
  http-server-netty/src/main/java/io/micronaut/http/server/netty/discovery/NettyServiceDiscovery.java
  test-suite/src/test/groovy/io/micronaut/EventListenerSpec.groovy
Labels: type: bug

#10289 Clarify use of defaultValue element of PathVariable annotation
  src/main/docs/guide/httpServer/routing.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/routes/IssuesController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/routes/IssuesControllerTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/routes/IssuesController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/routes/IssuesControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/server/routes/IssuesController.java
  test-suite/src/test/java/io/micronaut/docs/server/routes/IssuesControllerTest.java
Labels: type: docs

#10319 doc: Kotlin inline value classes No @Introspected
  src/main/docs/guide/ioc/introspection/kotlinAndBeanIntrospection.adoc
  src/main/docs/guide/toc.yml
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/core/beans/UserDataClass.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/core/beans/UserDataClassTest.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/core/beans/UserInlineValueClass.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/core/beans/UserInlineValueClassTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/core/beans/UserDataClass.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/core/beans/UserDataClassTest.kt
Labels: type: docs

#10326 Small RequestHandler refactor
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpToHttpsRedirectHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ByteBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/RequestHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/HttpRequestTest.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpRequestSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
  http-server-netty/src/test/java/io/micronaut/http/server/netty/jackson/JsonContentProcessorBenchmark.java
Labels: type: improvement

#10339 Make NettyJsonHandler implement NettyBodyWriter
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
Labels: type: improvement

#10341 Remove chatbots from 3.10.x micronaut-bom
  bom/build.gradle
  gradle/libs.versions.toml
Labels: relates-to: build

#10340 Remove chatbots from 3.9.x micronaut-bom
  bom/build.gradle
  gradle/libs.versions.toml
Labels: relates-to: build

#10342 AST: Introduce `MethodElement#getOverriddenMethods` to get all the methods overridden by this method
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/ast/MethodElement.java
  core-processor/src/main/java/io/micronaut/inject/utils/NativeElementsHelper.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/GroovyNativeElementHelper.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstClassUtils.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstGenericUtils.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/PublicMethodVisitor.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyBeanDefinitionBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyConstructorElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyMethodElement.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AggregatingTypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/GenericUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaNativeElementsHelper.java
  inject-java/src/main/java/io/micronaut/annotation/processing/LoadedVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/SuperclassAwareTypeVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaBeanDefinitionBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinNativeElementsHelper.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinElementAnnotationMetadataFactory.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyAccessorMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinPropertyElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinConstructorElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinElementFactory.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinPropertyElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinPropertyGetterMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinPropertySetterMethodElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinSimplePropertyElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
Labels: type: improvement

#10349 KSP: Don't create beans from interfaces
  core-processor/src/main/java/io/micronaut/inject/processing/BeanDefinitionCreatorFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
Labels: type: bug

#10351 KSP: Allow to instantiate a bean with all defaults
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/KotlinBeanIntrospectionSpec.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/TestEntity4.kt
Labels: type: improvement

#10332 Allow to reference a method in a class annotation expression
  aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java
  core-processor/src/main/java/io/micronaut/expressions/EvaluatedExpressionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractEvaluatedExpressionsSpec.groovy
  inject-java/src/test/groovy/io/micronaut/expressions/ClassMethodRefExpressionsSpec.groovy
Labels: type: improvement

#10355 KSP: Allow to use a creator
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinEnumElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
Labels: type: bug

#10358 Improve how AOP proxy target is generated
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  inject-java/src/test/groovy/io/micronaut/aop/lazyproxytarget/ArgMutatingInterceptor.java
  inject-java/src/test/groovy/io/micronaut/aop/lazyproxytarget/Mutating.java
  inject-java/src/test/groovy/io/micronaut/aop/lazyproxytarget/ProxyingClass.java
  inject-java/src/test/groovy/io/micronaut/aop/lazyproxytarget/ProxyingMethodLevelAopSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/proxytargethotswap/ArgMutatingInterceptor.java
  inject-java/src/test/groovy/io/micronaut/aop/proxytargethotswap/Mutating.java
  inject-java/src/test/groovy/io/micronaut/aop/proxytargethotswap/ProxyingClass.java
  inject-java/src/test/groovy/io/micronaut/aop/proxytargethotswap/ProxyingMethodLevelAopSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: improvement

#10359 Inject `InterceptorRegistry` into an AOP proxy, avoid multiple get bean calls
  aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java/src/test/groovy/io/micronaut/aop/compile/AnnotatedConstructorArgumentSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/compile/AnnotatedConstructorArgumentSpec.groovy
Labels: type: improvement

#10361 KSP: Fix mapping problems caused by unrecognized annotation container
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/KotlinCompiler.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactEntity.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactForm.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/ContactMappers.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/MappersSpec.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/Product.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/ProductDTO.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/ProductMappers.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/ioc/mappers/SimpleMapperSpec.kt
Labels: type: bug

#10365 KSP: Visit inner-inner classes
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/KotlinCompiler.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/configproperties/nested/ConfigurationLevel3Spec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/nested/ConfigurationLevel1.kt
Labels: type: bug

#10364 extract netty cookie into its own module
  http-cookie-netty/build.gradle.kts
  http-cookie-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookie.java
  http-cookie-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookieFactory.java
  http-cookie-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookies.java
  http-cookie-netty/src/main/java/io/micronaut/http/netty/cookies/package-info.java
  http-cookie-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyCookiesSpec.groovy
  http-netty/build.gradle
  settings.gradle
Labels: type: improvement

#10087 doc: change Grails creator copy
  README.md
Labels: type: docs

#10261 imp: add default methods to BeanDefinition to ease checking whether a method is annotated
  inject/src/main/java/io/micronaut/context/BeanDefinitionRegistry.java
  inject/src/main/java/io/micronaut/inject/BeanDefinition.java
  test-suite-groovy/src/test/groovy/io/micronaut/inject/blockingutils/AuthenticationProvider.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/inject/blockingutils/BlockingUtilsSpec.groovy
Labels: type: improvement

#10360 KSP: Allow to specify extra all-open annotations
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
Labels: type: improvement

#10371 KSP: support defaults on bean constructors
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/config/properties/TestProperties1.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/config/properties/TestProperties2.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/config/properties/TestPropertiesSpec.kt
Labels: type: improvement

#10380 Correct cache key of overridden method lookup
  core-processor/src/main/java/io/micronaut/inject/utils/NativeElementsHelper.java
Labels: type: improvement

#10353 [core] Update common files for branch 4.3.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#10385 Reprocess types with errors `TypeElementVisitorProcessor` and allow to veto elements
  core-processor/src/main/java/io/micronaut/inject/ast/utils/EnclosedElementsQuery.java
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
Labels: type: improvement

#10387 Fail `PostponeToNextRoundException` on error generic element
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java
Labels: type: bug

#10397 Fix getting the name of `FilteringCompositeQualifier`
  inject-java/src/test/groovy/io/micronaut/inject/qualifiers/composite/CompositeQualifierSpec.groovy
  inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
Labels: type: bug

#10398 KSP: Fix default methods with 32+ parameters
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/KotlinBeanIntrospectionSpec.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/TestEntity5.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/TestEntity6.kt
Labels: type: bug

#10402 feat: ServerCookieEncoder and ServerCookieDecoder
  config/accepted-api-changes.json
  http-client/src/main/java/io/micronaut/http/client/netty/NettyClientHttpRequest.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyStreamedHttpResponse.java
  http-cookie-netty/build.gradle.kts
  http-netty/build.gradle
  http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookie.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookieFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookies.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyLaxClientCookieEncoder.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyLaxServerCookieDecoder.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyServerCookieEncoder.java
  http-netty/src/main/java/io/micronaut/http/netty/cookies/package-info.java
  http-netty/src/main/resources/META-INF/services/io.micronaut.http.cookie.ClientCookieEncoder
  http-netty/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieDecoder
  http-netty/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieEncoder
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/ClientCookieEncoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/CookeFactorySpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/CookieComparatorSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyCookiesSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyLaxClientCookieEncoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyServerCookieEncoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/ServerCookieDecoderSpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/ServerCookieEncoderSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/CookieElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/CookiesElement.java
  http/src/main/java/io/micronaut/http/cookie/ClientCookieEncoder.java
  http/src/main/java/io/micronaut/http/cookie/Cookie.java
  http/src/main/java/io/micronaut/http/cookie/CookieComparator.java
  http/src/main/java/io/micronaut/http/cookie/CookieFactory.java
  http/src/main/java/io/micronaut/http/cookie/CookieHttpCookieAdapter.java
  http/src/main/java/io/micronaut/http/cookie/DefaultClientCookieEncoder.java
  http/src/main/java/io/micronaut/http/cookie/DefaultServerCookieDecoder.java
  http/src/main/java/io/micronaut/http/cookie/DefaultServerCookieEncoder.java
  http/src/main/java/io/micronaut/http/cookie/HttpCookieFactory.java
  http/src/main/java/io/micronaut/http/cookie/ServerCookieDecoder.java
  http/src/main/java/io/micronaut/http/cookie/ServerCookieEncoder.java
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ClientCookieEncoder
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.CookieFactory
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieDecoder
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.ServerCookieEncoder
  http/src/test/java/io/micronaut/http/cookie/ClientCookieEncoderTest.java
  http/src/test/java/io/micronaut/http/cookie/CookieComparatorTest.java
  http/src/test/java/io/micronaut/http/cookie/CookieFactoryTest.java
  http/src/test/java/io/micronaut/http/cookie/CookieHttpCookieAdapterTest.java
  http/src/test/java/io/micronaut/http/cookie/DefaultClientCookieEncoderTest.java
  http/src/test/java/io/micronaut/http/cookie/DefaultServerCookieDecoderTest.java
  http/src/test/java/io/micronaut/http/cookie/DefaultServerCookieEncoderTest.java
  http/src/test/java/io/micronaut/http/cookie/ServerCookieDecoderTest.java
  http/src/test/java/io/micronaut/http/cookie/ServerCookieEncoderTest.java
  settings.gradle
Labels: type: enhancement

#10407 Fix boxing a primitive value
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
Labels: type: bug

#10409 KSP: Use correct resolver
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
Labels: type: bug

#10428 Filter out unrecognized type elements
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
Labels: type: bug

#10429 Fix NoSuchBean classcast exception when generating message
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/test/groovy/io/micronaut/context/MultipleMatchingNoSuchBeanSpec.groovy
Labels: type: bug

#10418 document @ExecuteOn only works on Controller and Filter methods
  src/main/docs/guide/httpServer/reactiveServer.adoc
Labels: type: docs

#10432 Fix incorrect detection of imperative route for async/reactive void methods
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec15.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  router/src/main/java/io/micronaut/web/router/DefaultRouteInfo.java
Labels: type: bug
