Repository micronaut-projects/micronaut-core, pull requests merged in 2024-05, with the labels that each got.

#10777 fix: KSP processing for package private properties
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/MySuperclass.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/PackagePrivateSuperclass.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/MySuperclass.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/PackagePrivateSuperclass.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  inject-kotlin/src/test/java/io/micronaut/kotlin/processing/visitor/MySuperclass.java
  inject-kotlin/src/test/java/io/micronaut/kotlin/processing/visitor/PackagePrivateSuperclass.java
Labels: type: bug, lang: kotlin

#10772 Support ExecuteOn annotation with ServerWebSocket
  http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/websocket/WebsocketExecuteOnSpec.groovy
  src/main/docs/guide/httpServer/websocket/websocketServer.adoc
Labels: type: improvement

#10795 build: Use only one jackson version
  gradle/libs.versions.toml
Labels: type: bug

#10760 Update conditionalBeans.adoc to clarify how to depend on a conditional bean
  src/main/docs/guide/ioc/conditionalBeans.adoc
Labels: type: docs

#10792 Add API to access SSL session
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http/src/main/java/io/micronaut/http/HttpRequest.java
  http/src/main/java/io/micronaut/http/HttpRequestWrapper.java
Labels: type: improvement

#10793 Fix file uploads beyond MMAP_SEGMENT_SIZE
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/SslSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/SslSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/MicronautHttpData.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NonReentrantLock.java
  test-suite/src/test/groovy/io/micronaut/upload/DiskUploadSpec.groovy
  test-suite/src/test/groovy/io/micronaut/upload/UploadController.java
Labels: type: bug

#10769 Remove unnecessary noise printed during a normal build.
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
Labels: type: improvement

#10811 fix: Build with GRPC KSP processing fails
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/Message.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  inject-kotlin/src/test/java/io/micronaut/kotlin/processing/visitor/Message.java
Labels: type: bug, lang: kotlin

#10820 Make behaviour of @DefaultImplementation consistent
  core/src/main/java/io/micronaut/core/annotation/Order.java
  core/src/main/java/io/micronaut/core/order/Ordered.java
  inject-java/src/test/groovy/io/micronaut/inject/defaultimpl/DefaultImplementationSpec.groovy
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/annotation/DefaultImplementation.java
  src/main/docs/guide/ioc/replaces.adoc
Labels: type: improvement

#10812 Remove obsolete text in httpServer.adoc
  src/main/docs/guide/httpServer.adoc
Labels: type: docs

#10824 improve BeanProvider API by adding lookup methods
  inject-java/src/test/groovy/io/micronaut/inject/provider/BeanProviderSpec.groovy
  inject/src/main/java/io/micronaut/context/BeanLocator.java
  inject/src/main/java/io/micronaut/context/BeanProvider.java
Labels: type: improvement

#10830 Add support for optional field/method injection
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationUtil.java
  inject-java/src/test/groovy/io/micronaut/inject/autowired/Autowired.java
  inject-java/src/test/groovy/io/micronaut/inject/autowired/AutowiredSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/autowired/AutowiredTransformer.java
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/inject/InjectionPoint.java
  src/main/docs/guide/ioc/beans.adoc
  src/main/docs/guide/ioc/injection.adoc
  src/main/docs/guide/ioc/injection/constructorInjection.adoc
  src/main/docs/guide/ioc/injection/fieldInjection.adoc
  src/main/docs/guide/ioc/injection/methodInjection.adoc
  src/main/docs/guide/ioc/injection/nullableInjection.adoc
  src/main/docs/guide/ioc/injection/optionalInjection.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/ctor/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/field/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/method/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/nullable/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/optional/Vehicle.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/ctor/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/field/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/method/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/nullable/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/optional/Vehicle.kt
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/ctor/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/field/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/method/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/nullable/NullableInjectTest.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/nullable/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/optional/OptionalAutowiredTest.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/optional/Vehicle.java
Labels: type: enhancement

#10831 KSP: Correctly handle Java files compiled by KSP
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractKotlinCompilerSpec.groovy
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/KotlinCompiler.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinNativeElementsHelper.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#10845 Small performance improvements
  core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
  core/src/main/java/io/micronaut/core/util/StringUtils.java
  http/src/main/java/io/micronaut/http/MediaType.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
Labels: type: improvement

#10853 Update SslSpec.groovy
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/SslSpec.groovy
Labels: type: bug

#10850 Interceptor should intercept non-abstract methods for abstract classes
  core-processor/src/main/java/io/micronaut/inject/processing/AbstractBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/processing/AopIntroductionProxySupportedBeanElementCreator.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyAbstractRepoSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepo3.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepo4.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepo5.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepoIntroductionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/Tx.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/TxInterceptor.java
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/aop/introduction/AbstractClass.kt
Labels: type: bug

#10838 javadoc: Order improvements
  core/src/main/java/io/micronaut/core/annotation/Order.java
Labels: type: docs

#10835 doc: Improve injection documentation
  src/main/docs/guide/ioc/beans.adoc
  src/main/docs/guide/ioc/injection.adoc
  src/main/docs/guide/ioc/injection/constructorInjection.adoc
  src/main/docs/guide/ioc/injection/fieldInjection.adoc
  src/main/docs/guide/ioc/injection/methodInjection.adoc
  src/main/docs/guide/ioc/injection/optionalInjection.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/ctor/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/field/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/method/Vehicle.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/injection/nullable/Vehicle.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/ctor/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/field/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/method/Vehicle.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/injection/nullable/Vehicle.kt
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/ctor/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/field/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/method/Vehicle.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/nullable/NullableInjectTest.java
  test-suite/src/test/java/io/micronaut/docs/ioc/injection/nullable/Vehicle.java
Labels: type: docs

#10854 Update Kotlin and KSP
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#10846 Add more media types
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy
Labels: type: improvement

#10856 Remove unnecessary semicolon
  core/src/main/java/io/micronaut/core/util/StringUtils.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java
  http/src/main/java/io/micronaut/http/cookie/SameSite.java
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
Labels: type: improvement

#10858 test: ignore revoked.badssl.com/
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/SslSpec.groovy
Labels: type: improvement

#10860 Merge ConfigurableUriNamingStrategy into HyphenatedUriNamingStrategy
  router/src/main/java/io/micronaut/web/router/naming/ConfigurableUriNamingStrategy.java
  router/src/main/java/io/micronaut/web/router/naming/HyphenatedUriNamingStrategy.java
  router/src/test/groovy/io/micronaut/web/router/ConfigurableUriNamingStrategySpec.groovy
Labels: type: improvement

#10859 Add HEAD_BODY attribute
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/ResponseFilterTest.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  http/src/main/java/io/micronaut/http/HttpAttributes.java
Labels: type: improvement

#10870 Allow customising endpoints context path
  http/src/main/java/io/micronaut/http/annotation/ServerFilter.java
  http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java
  management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java
  management/src/main/java/io/micronaut/management/endpoint/EndpointsFilter.java
  management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
  management/src/test/groovy/io/micronaut/management/endpoint/EndpointsContextPathSpec.groovy
Labels: type: enhancement

#10789 docs: remove obsolete "CI" section.
  README.md
Labels: type: docs
