Repository micronaut-projects/micronaut-core, pull requests merged in 2024-09, with the labels that each got.

#11145 Fix inject remapped beans with type arguments
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/CoreReaders1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/CoreReaders2.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/EachBeanGenericSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/IntegerMyReader1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/IntegerMyReader2.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#11156 [core] Update common files for branch 4.7.x
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#11159 Add ByteArrayByteBufferSpec from servlet
  core/src/main/java/io/micronaut/core/io/buffer/ByteArrayByteBuffer.java
  core/src/test/groovy/io/micronaut/core/io/buffer/ByteArrayByteBufferSpec.groovy
Labels: type: improvement

#11155 Skip classes from introspection generation that are postponed
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/visitor/ElementPostponedToNextRoundException.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationUtils.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject-java/src/test/groovy/io/micronaut/visitors/PostponedVisitorsSpec.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/Wither.java
  inject-java/src/test/groovy/io/micronaut/visitors/WitherVisitor.java
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#11160 Store enum values as strings
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  settings.gradle
  test-suite-annotation-remapper-visitor/build.gradle
  test-suite-annotation-remapper-visitor/src/main/java/example/micronaut/AddAnnotationWithEnumVisitor.java
  test-suite-annotation-remapper-visitor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  test-suite-annotation-remapper/build.gradle
  test-suite-annotation-remapper/src/test/java/example/micronaut/HelloController.java
  test-suite-annotation-remapper/src/test/java/example/micronaut/HelloControllerTest.java
  test-suite-annotation-remapper/src/test/java/example/micronaut/MyRecord.java
  test-suite-annotation-remapper/src/test/resources/logback.xml
Labels: type: bug, relates-to: graal

#11170 Fix JsonView and Optional return type
  http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java
  test-suite/src/test/groovy/io/micronaut/views/JsonViewsTest.java
  test-suite/src/test/groovy/io/micronaut/views/User.java
  test-suite/src/test/groovy/io/micronaut/views/UserController.java
  test-suite/src/test/groovy/io/micronaut/views/Views.java
Labels: type: bug

#11161 Skip error routes when initial processing of malformed request fails
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyRequestLifecycle.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/HeaderTooLongSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/MalformedUriSpec.groovy
Labels: type: bug

#11051 Fix reentrant subscribe in StreamingNettyByteBody
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/StreamingNettyByteBody.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: bug

#11165 [core] Update common files for branch 4.7.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#11142 Add support lost `java.time` classes:
  context/src/main/java/io/micronaut/runtime/converters/time/TimeConverterRegistrar.java
  core/src/main/java/io/micronaut/core/reflect/ClassUtils.java
  gradle.properties
  runtime/src/test/groovy/io/micronaut/runtime/converters/time/TimeConverterRegistrarSpec.groovy
Labels: type: enhancement

#11179 Fix typo
  http-tck/src/main/java/io/micronaut/http/tck/TestScenario.java
  http/src/main/java/io/micronaut/http/annotation/RequestAttribute.java
  http/src/main/java/io/micronaut/http/annotation/RouteCondition.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
  inject/src/test/groovy/io/micronaut/context/i18n/StaticMessageSourceSpec.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/core/beans/UserInlineValueClassTest.kt
Labels: type: docs

#11180 Fix broken links in builtInExceptionHandlers.adoc
  src/main/docs/guide/httpServer/errorHandling/exceptionHandler/builtInExceptionHandlers.adoc
Labels: type: docs

#11158 Refactor DefaultHttpClient to use ByteBody for the request body
  core/src/main/java/io/micronaut/core/io/buffer/ByteArrayBufferFactory.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClientBuilder.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyHttpRequestBuilder.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyBodyAdapter.java
  http-netty/src/main/java/io/micronaut/http/netty/body/StreamingNettyByteBody.java
  http-netty/src/test/groovy/io/micronaut/http/netty/body/NettyBodyAdapterSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/Http2ServerHandlerSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/PipeliningServerHandlerSpec.groovy
Labels: type: improvement

#11177 ByteBody-based response handling for the HTTP client
  http-client-core/src/main/java/io/micronaut/http/client/exceptions/ContentLengthExceededException.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/main/java/io/micronaut/http/client/netty/Http1ResponseHandler.java
  http-client/src/main/java/io/micronaut/http/client/netty/HttpLineBasedFrameDecoder.java
  http-client/src/main/java/io/micronaut/http/client/netty/SseSplitter.java
  http-client/src/test/groovy/io/micronaut/http/client/DataStreamSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/MaxResponseSizeSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/Http1ResponseHandlerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/SseSplitterSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/body/AvailableNettyByteBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy
  http/src/main/java/io/micronaut/http/exceptions/BufferLengthExceededException.java
Labels: type: improvement

#11199 Fix outer injection point of constructor
  inject-java/src/test/groovy/io/micronaut/inject/factory/generics/GenericFactorySpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
Labels: type: bug

#11182 HTTP client refactor
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/ForwardingSubscriber.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyClientByteBodyResponse.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyFuturePublisher.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyPromiseSubscriber.java
  http-client/src/main/java/io/micronaut/http/client/netty/StreamWriter.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyHttpRequestBuilder.java
  http-netty/src/main/java/io/micronaut/http/netty/body/AvailableNettyByteBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http/src/main/java/io/micronaut/http/ByteBodyHttpResponse.java
Labels: type: improvement

#11221 Fix forwarding null when CancellableMonoSink is cancelled
  http-client/src/main/java/io/micronaut/http/client/netty/CancellableMonoSink.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/CancellableMonoSinkSpec.groovy
Labels: type: bug
