Repository micronaut-projects/micronaut-core, pull requests merged in 2024-07, with the labels that each got.

#10935 Cleanup micronaut-router
  router/src/main/java/io/micronaut/web/router/AbstractRouteMatch.java
  router/src/main/java/io/micronaut/web/router/AnnotatedMethodRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/DefaultErrorRouteInfo.java
  router/src/main/java/io/micronaut/web/router/DefaultFilterRoute.java
  router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/DefaultRouteInfo.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
  router/src/main/java/io/micronaut/web/router/DefaultStatusRouteInfo.java
  router/src/main/java/io/micronaut/web/router/DefaultUriRouteMatch.java
  router/src/main/java/io/micronaut/web/router/DefaultUrlRouteInfo.java
  router/src/main/java/io/micronaut/web/router/ErrorRouteMatch.java
  router/src/main/java/io/micronaut/web/router/FilterRoute.java
  router/src/main/java/io/micronaut/web/router/RouteBuilder.java
  router/src/main/java/io/micronaut/web/router/RouteInfo.java
  router/src/main/java/io/micronaut/web/router/RouteMatchUtils.java
  router/src/main/java/io/micronaut/web/router/ServerFilterRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/exceptions/DuplicateRouteException.java
  router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java
  router/src/main/java/io/micronaut/web/router/naming/ConfigurableUriNamingStrategy.java
  router/src/main/java/io/micronaut/web/router/naming/HyphenatedUriNamingStrategy.java
  router/src/main/java/io/micronaut/web/router/resource/StaticResourceConfiguration.java
  router/src/main/java/io/micronaut/web/router/version/ConfigurationDefaultVersionProvider.java
  router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
  router/src/main/java/io/micronaut/web/router/version/VersionAwareRouterListener.java
  router/src/test/groovy/io/micronaut/context/router/AnnotationRouteBuilderSpec.groovy
  router/src/test/groovy/io/micronaut/web/router/DefaultFilterRouteSpec.groovy
Labels: type: improvement

#10936 Properly handle missing classes in metadata + precalculated requirements
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core/src/main/java/io/micronaut/core/util/CollectionUtils.java
  inject-java/src/test/groovy/io/micronaut/inject/configurations/RequiresBeanSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/requires/RequiresSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinitionAndReference.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/RequiresCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesAbsenceOfBeansCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesAbsenceOfClassNamesCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesAbsenceOfClassesCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesConditionUtils.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesConfigurationCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesCurrentNotOsCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesCurrentOsCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesCustomCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesDynamicCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesEnvironmentCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesMissingPropertyCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesNotEnvironmentCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPresenceOfBeansCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPresenceOfClassesCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPresenceOfEntitiesCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPresenceOfResourcesCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPropertyCondition.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesSdkCondition.java
  management/src/test/groovy/io/micronaut/management/endpoint/beans/BeansEndpointSpec.groovy
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/http/missing/MissingBeanSpec.groovy
  test-suite/src/test/groovy/io/micronaut/http/missing/classnotfound/MissingConstructorBeanController.java
  test-suite/src/test/groovy/io/micronaut/http/missing/classnotfound/MissingExecutableMethodBeanController.java
  test-suite/src/test/groovy/io/micronaut/http/missing/classnotfound/MissingFieldBeanController.java
  test-suite/src/test/groovy/io/micronaut/http/missing/classnotfound/MissingMethodInjectBeanController.java
Labels: type: improvement

#10946 Update Micronaut Maven Plugin coordinates
  src/main/docs/guide/cli/reloading/jrebel.adoc
Labels: type: docs

#10947 include all non-accessible methods in reflection data
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  graal/src/test/groovy/io/micronaut/graal/reflect/GraalTypeElementVisitorSpec.groovy
  graal/src/test/groovy/io/micronaut/graal/reflect/other/TestParent.java
Labels: type: bug

#10940 Support unix domain sockets for the access log handler
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogManager.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/AccessLog.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/AccessLogFormatParser.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/ConnectionMetadata.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/ConnectionMetadataImpl.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/LocalHostElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/LocalIpElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/LocalPortElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/LogElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/RemoteHostElement.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/element/RemoteIpElement.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/AccessLogSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/accesslog/element/AccessLogFormatParserSpec.groovy
Labels: type: improvement

#10953 Fix CompletableFuture responses without body
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: bug

#10937 Add config option for DNS resolution modes
  http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/DnsSpec.groovy
Labels: type: improvement

#10956 Fix NPE in `BeanDefinitionProducer`
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#10963 Don't store enum values. Store a class and the enum name instead
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractEnumBeanIntrospectionAndReference.java
Labels: type: improvement

#10950 Reintroduce build time init of compilation time metadata
  build.gradle
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/EvaluatedExpressionProcessor.java
  core/src/main/java/io/micronaut/core/annotation/BuildTimeInit.java
  core/src/main/java/io/micronaut/core/io/service/ServiceLoaderFeature.java
  gradle/libs.versions.toml
  http-client/src/test/groovy/io/micronaut/http/client/BlockingDeadlockSpec.groovy
  http-server/build.gradle
  inject-java/build.gradle
  inject-java/src/test/groovy/io/micronaut/core/io/service/ServiceLoaderFeatureSpec.groovy
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
  settings.gradle
  test-suite-geb/build.gradle
  test-suite-groovy/build.gradle
  test-suite-http-server-tck-netty/build.gradle
  test-suite-http2-server-tck-netty/build.gradle
  test-suite-kotlin-ksp/build.gradle
  test-suite-kotlin/build.gradle
  test-suite-logback-graalvm/build.gradle
  test-suite-netty-ssl-graalvm/build.gradle
  test-suite/build.gradle
Labels: type: enhancement, relates-to: graal

#10967 Add config options for form parsing limits
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormDataHttpContentProcessor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyServerRequestBinderRegistry.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/MultipartBodyArgumentBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/FormLimitSpec.groovy
Labels: type: improvement

#10960 [core] Update common files for branch 4.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#10975 Correct reading HTTP client response body without content type + `ByteBuffer` converters
  buffer-netty/src/main/java/io/micronaut/buffer/netty/NettyByteBuffer.java
  buffer-netty/src/main/java/io/micronaut/buffer/netty/NettyByteBufferConverters.java
  buffer-netty/src/main/java/io/micronaut/buffer/netty/NettyByteBufferFactory.java
  buffer-netty/src/main/resources/META-INF/services/io.micronaut.core.convert.TypeConverterRegistrar
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/test/groovy/io/micronaut/http/client/ResponseBodySpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/NettyConverters.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/NettyConvertersSpi.java
Labels: type: improvement

#10973 Correct cookies in simple request/response
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpResponseSpec.groovy
  http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java
  http/src/main/java/io/micronaut/http/simple/SimpleHttpResponse.java
  http/src/test/groovy/io/micronaut/http/HttpRequestSpec.groovy
Labels: type: bug

#10979 Fix client channel option configuration
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/converters/ConverterRegistrySpec.groovy
Labels: type: bug

#10962 Add a reflection util class to extract generic type and annotations for a class
  context-propagation/src/test/groovy/io/micronaut/context/AnnotationReflectionUtilsSpec.groovy
  inject/src/main/java/io/micronaut/context/AnnotationReflectionUtils.java
Labels: type: improvement

#10918 Type pollution test
  benchmarks/build.gradle
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/FullHttpStackBenchmark.java
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/NettyUtil.java
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/TfbLikeBenchmark.java
  benchmarks/src/typeCheckTest/java/example/TypeThrashingTest.java
  gradle/libs.versions.toml
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  jackson-databind/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: improvement

#10993 Fix enums as each property keys. Fixes #10944
  inject-java/src/test/groovy/io/micronaut/inject/foreach/withenum/EnumConfiguration.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/withenum/EnumEachPropertySpec.groovy
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
Labels: type: bug

#10961 Support binding RouteMatch in server filter methods
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/ContentLengthHeaderTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterTest.java
  http-server/src/main/java/io/micronaut/http/server/binding/RouteMatchArgumentBinder.java
  http-validation/src/main/java/io/micronaut/validation/routes/FilterVisitor.java
  http/src/main/java/io/micronaut/http/annotation/RequestFilter.java
  http/src/main/java/io/micronaut/http/annotation/ResponseFilter.java
  http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java
  http/src/main/java/io/micronaut/http/filter/FilterArgumentBinderPredicate.java
  http/src/main/java/io/micronaut/http/filter/MethodFilter.java
Labels: type: improvement

#10996 [core] Update common files for branch 4.6.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#10983 Improvements to HTTP client timeout handling
  http-client-core/src/main/java/io/micronaut/http/client/DefaultHttpClientConfiguration.java
  http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
  http-client-core/src/main/java/io/micronaut/http/client/ServiceHttpClientConfiguration.java
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/Http2PingSender.java
  http-client/src/main/java/io/micronaut/http/client/netty/ResettableReadTimeoutHandler.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/channel/ChannelPipelineCustomizer.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  management/src/test/groovy/io/micronaut/management/health/indicator/client/ServiceHttpClientHealthIndicatorSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/http/server/stream/StreamControllerSpec.groovy
Labels: type: improvement

#10857 Code cleanup for io.micronaut.http.uri
  http/src/main/java/io/micronaut/http/uri/DefaultUriBuilder.java
  http/src/main/java/io/micronaut/http/uri/QueryStringDecoder.java
  http/src/main/java/io/micronaut/http/uri/UriBuilder.java
  http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
  http/src/main/java/io/micronaut/http/uri/UriMatchVariable.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
  http/src/main/java/io/micronaut/http/uri/UriTemplateExpander.java
  http/src/main/java/io/micronaut/http/uri/UriTemplateMatcher.java
  http/src/main/java/io/micronaut/http/uri/UriTypeMatchTemplate.java
Labels: type: improvement

#11003 Allow for `@EachBean` to delegate the generics to the newly created bean definition
  core/src/main/java/io/micronaut/core/type/Argument.java
  core/src/main/java/io/micronaut/core/type/DefaultArgument.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/CoreReader1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/CoreReader2.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/EachBeanGenericSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/MyReader1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/MyReader2.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/MyToCoreReader1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/MyToCoreReader2.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/StringMyReader1.java
  inject-java/src/test/groovy/io/micronaut/inject/foreach/generic/StringMyReader2.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/annotation/EachBean.java
  inject/src/main/java/io/micronaut/context/annotation/Provided.java
Labels: type: improvement

#10998 #9607: Endpoint path must support URI path as per rfc3986 appendix-B
  management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
  management/src/test/groovy/io/micronaut/management/URIPatternEndpointSpec.groovy
Labels: type: improvement

#11005 KSP: Simple Java properties should have access to field annotations
  inject-kotlin/build.gradle
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinSimplePropertyElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#11015 Use ReentrantLock instead of synchronized in CancellableMonoSink
  http-client/src/main/java/io/micronaut/http/client/netty/CancellableMonoSink.java
Labels: type: bug

#11019 Correct HTTP client body handler
  http-client/src/test/groovy/io/micronaut/http/body/BodyReadersSpec.groovy
  http/src/main/java/io/micronaut/http/body/ContextlessMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/MessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/TextPlainObjectBodyWriter.java
Labels: type: improvement

#11017 Implement `@PreMatching` request filter methods
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/AbstractJdkHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/ServerPreFilterSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
  http-server/src/main/java/io/micronaut/http/server/annotation/PreMatching.java
  http/src/main/java/io/micronaut/http/body/TextPlainObjectBodyReader.java
  http/src/main/java/io/micronaut/http/filter/BaseFilterProcessor.java
  http/src/main/java/io/micronaut/http/filter/FilterRunner.java
  http/src/main/java/io/micronaut/http/filter/InternalHttpFilter.java
  router/src/main/java/io/micronaut/web/router/BeanDefinitionFilterRoute.java
  router/src/main/java/io/micronaut/web/router/DefaultFilterRoute.java
  router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
  router/src/main/java/io/micronaut/web/router/FilterRoute.java
  router/src/main/java/io/micronaut/web/router/Router.java
  router/src/main/java/io/micronaut/web/router/ServerFilterRouteBuilder.java
  router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java
  src/main/docs/guide/httpServer/filters/filtermethods.adoc
Labels: type: improvement
