Repository micronaut-projects/micronaut-core, pull requests merged in 2024-12, with the labels that each got.

#11378 Add ability to configure NettyThreadFactory and set `daemon` and `priority` flags
  core/src/main/java/io/micronaut/core/bind/annotation/AbstractArgumentBinder.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyThreadFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/configuration/NettyGlobalConfiguration.java
Labels: type: improvement

#11396 Fix ClassCastException of BeanReadPropertyImpl to BeanProperty
  core/src/main/java/io/micronaut/core/beans/BeanIntrospection.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
Labels: type: bug

#11387 Add correct message, when set duration / period value in wrong format.
  context/src/main/java/io/micronaut/runtime/converters/time/TimeConverterRegistrar.java
  context/src/test/groovy/io/micronaut/runtime/converters/time/TimeConverterConfigurationSpec.groovy
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
Labels: type: improvement

#11400 [core] Update common files for branch 4.8.x
  .github/renovate.json
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#11388 New liveness probe to check for deadlocked threads
  core/src/main/java/io/micronaut/core/util/NativeImageUtils.java
  core/src/test/java/io/micronaut/core/util/NativeImageUtilsInNativeImageTest.java
  core/src/test/java/io/micronaut/core/util/NativeImageUtilsTest.java
  inject/src/main/java/io/micronaut/context/condition/NotInNativeImage.java
  management/build.gradle.kts
  management/src/main/java/io/micronaut/management/health/indicator/threads/DeadlockedThreadsHealthIndicator.java
  management/src/main/java/io/micronaut/management/health/indicator/threads/package-info.java
  management/src/test/groovy/io/micronaut/management/health/aggregator/HealthAggregatorSpec.groovy
  management/src/test/groovy/io/micronaut/management/health/indicator/threads/DeadlockedThreadsHealthIndicatorConfigurationSpec.groovy
  management/src/test/groovy/io/micronaut/management/health/indicator/threads/DeadlockedThreadsHealthIndicatorSpec.groovy
  management/src/test/groovy/io/micronaut/management/health/monitor/HealthMonitorTaskSpec.groovy
  management/src/test/java/io/micronaut/management/health/indicator/threads/DeadlockedThreadsHealthIndicatorTest.java
  src/main/docs/guide/management/providedEndpoints/healthEndpoint/deadlockedThreads.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#11438 Add link to Gradle plugin portal
  src/main/docs/guide/ioc.adoc
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
Labels: type: docs

#11433 Update bouncy castle bcpkix
  src/main/docs/guide/httpServer/serverConfiguration/https.adoc
Labels: type: docs

#11443 [GR-60327] Review and update 15.4 Micronaut for GraalVM content.
  src/main/docs/guide/languageSupport/graal.adoc
  src/main/docs/guide/languageSupport/graal/graalFAQ.adoc
  src/main/docs/guide/languageSupport/graal/graalServices.adoc
Labels: type: docs

#11448 fix: Error Page Key should consider error messages
  http-server-netty/src/test/java/io/micronaut/http/server/exceptions/response/HtmlErrorResponseCacheTest.java
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/DefaultHtmlErrorResponseBodyProvider.java
Labels: type: bug

#11451 Process constructors regradless of builder. Fixes #11432
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
  test-suite/src/test/java/io/micronaut/test/lombok/RobotRecord.java
Labels: type: bug

#11440 Fix client backpressure for streaming requests
  http-client/build.gradle
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/Http1ResponseHandler.java
  http-client/src/main/java/io/micronaut/http/client/netty/ReactiveClientReader.java
  http-client/src/main/java/io/micronaut/http/client/netty/ReactiveClientWriter.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ReactiveClientReaderSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/ReactiveClientWriterSpec.groovy
  http-client/src/test/java/io/micronaut/http/client/ProxyBackpressureTest.java
  http-client/src/test/resources/junit-platform.properties
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
Labels: type: bug

#11452 [GR-60327] Update {graalVersion} version for docs.
  gradle.properties
  src/main/docs/guide/languageSupport/graal/graalServices.adoc
Labels: type: docs, relates-to: graal

#11464 apply .convention-core-library
  aop/build.gradle
  buffer-netty/build.gradle
  context-propagation/build.gradle
  context/build.gradle
  core-processor/build.gradle
  core-reactive/build.gradle
  core/build.gradle
  discovery-core/build.gradle
  function-client/build.gradle
  function-web/build.gradle
  function/build.gradle
  graal/build.gradle
  http-client-core/build.gradle
  http-client-jdk/build.gradle.kts
  http-client-tck/build.gradle.kts
  http-client/build.gradle
  http-netty/build.gradle
  http-server-netty/build.gradle
  http-server-tck/build.gradle.kts
  http-server/build.gradle
  http-tck/build.gradle.kts
  http-validation/build.gradle
  http/build.gradle
  inject-groovy-test/build.gradle
  inject-groovy/build.gradle
  inject-java-test/build.gradle
  inject-java/build.gradle
  inject-kotlin-test/build.gradle
  inject-kotlin/build.gradle
  inject/build.gradle
  jackson-core/build.gradle
  jackson-databind/build.gradle
  json-core/build.gradle
  management/build.gradle
  messaging/build.gradle
  retry/build.gradle
  router/build.gradle
  runtime-osx/build.gradle
  runtime/build.gradle
  websocket/build.gradle
Labels: relates-to: build

#11465 apply Sonatype Scan Gradle Plugin
  .github/workflows/gradle.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io/micronaut/build/internal/io.micronaut.build.internal.convention-core-library.gradle
  gradle/libs.versions.toml
Labels: relates-to: build, relates-to: security

#11416 Add semicolonIsNormalChar and maxParams properties to the server config
  http-netty/src/main/java/io/micronaut/http/netty/AbstractNettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http/src/main/java/io/micronaut/http/form/FormConfiguration.java
  http/src/main/java/io/micronaut/http/form/FormConfigurationProperties.java
  http/src/main/java/io/micronaut/http/uri/DefaultFormUrlEncodedDecoder.java
  http/src/main/java/io/micronaut/http/uri/QueryStringDecoder.java
  http/src/test/java/io/micronaut/http/form/FormConfigurationTest.java
  http/src/test/java/io/micronaut/http/form/FormConfigurationViaPropertyTest.java
Labels: type: improvement
