Repository micronaut-projects/micronaut-core, pull requests merged in 2024-08, with the labels that each got.

#11006 Fix returning unit from suspended methods
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  test-suite-kotlin/src/test/kotlin/io/micronaut/http/server/ControllerSuspendTest.kt
Labels: type: bug

#11050 Allow DELETE request body in http-client-jdk
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/HttpRequestFactory.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/HttpMethodDeleteTest.java
Labels: type: bug

#11035 10799 deduce cloud environment app engine
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
Labels: type: improvement

#11052 KSP: Generate beans in the process method instead in the finish method
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/beans/BeanDefinitionProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/introduction/MyRepo3Spec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/aop/introduction/CoroutineCrudRepository.kt
  inject-kotlin/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#10982 Can't find micronautserviceconfigs when running as jlink-ed application
  core/src/main/java/io/micronaut/core/io/IOUtils.java
  core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java
  core/src/main/java/io/micronaut/core/io/service/ServiceLoaderFeature.java
  core/src/main/java/io/micronaut/core/io/service/ServiceScanner.java
  core/src/test/java/io/micronaut/core/io/service/SoftServiceLoaderTest.java
  core/src/test/resources/test.jar
Labels: type: improvement

#11061 Fix resolution of `@Retryable(value=)` attribute
  retry/src/main/java/io/micronaut/retry/annotation/Retryable.java
  retry/src/test/groovy/io/micronaut/retry/intercept/SimpleRetrySpec.groovy
Labels: type: bug

#11063 [core] Update common files for branch 4.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#11069 Correct order of body handlers
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  http/src/main/java/io/micronaut/http/body/ConversionTextPlainHandler.java
  http/src/main/java/io/micronaut/http/body/DefaultMessageBodyHandlerRegistry.java
Labels: type: bug

#11057 imp: remove @Experimental from ServerFilter
  http/src/main/java/io/micronaut/http/annotation/ClientFilter.java
  http/src/main/java/io/micronaut/http/annotation/RequestFilter.java
  http/src/main/java/io/micronaut/http/annotation/ResponseFilter.java
  http/src/main/java/io/micronaut/http/annotation/ServerFilter.java
Labels: type: improvement

#11055 Avoid using `ElementQuery#named`
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/ast/ElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/ast/utils/EnclosedElementsQuery.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/processing/FactoryBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/KotlinReconstructionSpec.groovy
Labels: type: improvement

#11060 Fix usage of `@Header(name="..")`
  http-client-core/src/main/java/io/micronaut/http/client/bind/DefaultHttpClientBinderRegistry.java
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/HeadersTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/HeadersTest.java
  http/src/main/java/io/micronaut/http/bind/binders/HeaderAnnotationBinder.java
  http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java
Labels: type: bug

#11064 Remove old HttpBody API
  http-server-netty/src/main/java/io/micronaut/http/server/netty/FormRouteCompleter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyRequestLifecycle.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/HttpBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ImmediateMultiObjectBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ImmediateSingleObjectBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/ManagedBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/MultiObjectBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/StreamingMultiObjectBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/NettyConverters.java
Labels: type: improvement

#11065 Add API to access main context from bootstrap context
  inject/src/main/java/io/micronaut/context/BootstrapContextAccess.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/test/groovy/io/micronaut/context/BootstrapAccessSpec.groovy
Labels: type: improvement

#11078 Add a ByteBody-based write API
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWriteContext.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/InputStreamBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/NettyBodyAdapter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/NettyByteBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/StreamFileBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/StreamingNettyByteBody.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/SystemFileBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/BlockingWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/Http2ServerHandlerSpec.groovy
  http/src/main/java/io/micronaut/http/body/InternalByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/AvailableByteArrayBody.java
  http/src/main/java/io/micronaut/http/body/stream/ByteQueue.java
  http/src/main/java/io/micronaut/http/body/stream/ExtendedInputStream.java
  http/src/main/java/io/micronaut/http/body/stream/InputStreamByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/StreamPair.java
  http/src/test/groovy/io/micronaut/http/body/stream/StreamPairSpec.groovy
Labels: type: improvement

#11087 Issue with Requires condition with missingClasses as string values
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  core/src/test/groovy/io/micronaut/core/annotation/AnnotationValueSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/requires/RequiresSpec.groovy
Labels: type: bug

#11090 KSP: Fix overridden suspended method
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/CustomRepository.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/InterceptorSpec.kt
Labels: type: bug, lang: kotlin

#11102 Correct custom media-type resolving
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/codec/JsonCodecAdditionalType2Test.java
  http/src/main/java/io/micronaut/http/body/DefaultMessageBodyHandlerRegistry.java
Labels: type: bug

#11103 KSP: Fix interceptors with parameter defaults
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/defaults_intercepted/DefaultsInterceptedController.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/defaults_intercepted/DefaultsInterceptedControllerSpec.kt
Labels: type: bug

#11107 Fix NettyBodyAdapter backpressure for empty buffers
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/NettyBodyAdapter.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/body/NettyBodyAdapterSpec.groovy
Labels: type: bug

#11115 Fix stream backpressure when compressing
  http-server-netty/src/main/java/io/micronaut/http/server/netty/body/InputStreamBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/CompressionSpec.groovy
Labels: type: bug

#11109 Replace the DefaultHttpClient constructors with a builder
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClientBuilder.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyHttpClientFactory.java
  http-client/src/test/groovy/io/micronaut/http/body/BodyReadersSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/services/ManualHttpServiceDefinitionSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/http/client/proxy/ProxyRequestSpec.groovy
Labels: type: improvement

#11110 Allow customization of the Bootstrap in NettyClientCustomizer
  http-client/src/main/java/io/micronaut/http/client/netty/CompositeNettyClientCustomizer.java
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/NettyClientCustomizer.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/AbstractCompositeCustomizer.java
Labels: type: improvement
