Repository micronaut-projects/micronaut-core, pull requests merged in 2024-11, with the labels that each got.

#11278 Add new `definitionType` parameter for `@Client` annotation
  http-client-core/src/main/java/io/micronaut/http/client/annotation/Client.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/test/groovy/io/micronaut/http/client/ClientIntroductionAdviceSpec.groovy
Labels: type: enhancement

#11306 Minor server optimizations
  benchmarks/build.gradle
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/ControllersBenchmark.java
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/RawClientBenchmark.java
  benchmarks/src/typeCheckTest/java/example/TypeThrashingTest.java
  core/src/main/java/io/micronaut/core/convert/value/ConvertibleValuesMap.java
  core/src/main/java/io/micronaut/core/naming/NameUtils.java
  core/src/test/java/io/micronaut/core/naming/NameUtilsTest.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyCharSequenceBodyWriter.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultHttpCompressionStrategy.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Compressor.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: improvement

#11311 Specific `RequestArgumentBinder`
  core/src/main/java/io/micronaut/core/bind/annotation/AbstractArgumentBinder.java
  http-server/src/main/java/io/micronaut/http/server/ExecutableRouteInfo.java
  http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
  http/src/main/java/io/micronaut/http/bind/binders/CookieAnnotationBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/CookieObjectArgumentBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/HeaderAnnotationBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/PathVariableAnnotationBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/QueryValueArgumentBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/RequestArgumentBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/RequestAttributeAnnotationBinder.java
  router/src/main/java/io/micronaut/web/router/DefaultMethodBasedRouteInfo.java
Labels: type: improvement

#11288 Migrate netty HttpClient to ExecutionFlow
  core/src/main/java/io/micronaut/core/execution/DelayedExecutionFlow.java
  core/src/main/java/io/micronaut/core/execution/DelayedExecutionFlowImpl.java
  core/src/main/java/io/micronaut/core/execution/ExecutionFlow.java
  core/src/main/java/io/micronaut/core/execution/ImperativeExecutionFlow.java
  core/src/test/groovy/io/micronaut/core/execution/DelayedExecutionFlowSpec.groovy
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
  http-client/src/test/groovy/io/micronaut/http/client/ClientScopeSpec.groovy
  http-netty/src/main/java/io/micronaut/http/netty/body/AvailableNettyByteBody.java
  http-netty/src/main/java/io/micronaut/http/netty/body/StreamingNettyByteBody.java
  http-netty/src/test/groovy/io/micronaut/http/netty/body/AvailableNettyByteBodySpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/body/StreamingNettyByteBodySpec.groovy
  http/src/main/java/io/micronaut/http/body/ByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/AvailableByteArrayBody.java
  http/src/main/java/io/micronaut/http/body/stream/InputStreamByteBody.java
  http/src/main/java/io/micronaut/http/reactive/execution/ReactiveExecutionFlow.java
  http/src/main/java/io/micronaut/http/reactive/execution/ReactorExecutionFlowImpl.java
  http/src/test/groovy/io/micronaut/http/body/stream/AvailableByteArrayBodySpec.groovy
  http/src/test/groovy/io/micronaut/http/body/stream/InputStreamByteBodySpec.groovy
Labels: type: improvement

#11312 Minor improvement to `PropagatedContext`
  core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
Labels: type: improvement

#11314 Minor route executor improvement
  http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
  router/src/main/java/io/micronaut/web/router/DefaultUrlRouteInfo.java
Labels: type: improvement

#11318 KSP: Correct aggregating dependencies
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinOutputVisitor.kt
Labels: type: bug

#11294 Remove context propagation filter
  core-reactive/src/main/java/io/micronaut/core/async/propagation/ReactivePropagation.java
  http-client-core/src/main/java/io/micronaut/http/client/filters/ClientServerContextFilter.java
  http-client-core/src/main/java/io/micronaut/http/client/filters/ClientServerRequestTracingPublisher.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/context/FlatMapAndRequestInReactorContextSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/context/HttpClientFilterRequestInReactorContextSpec.groovy
  http/src/main/java/io/micronaut/http/context/ServerRequestContext.java
Labels: type: improvement

#11309 Add lost SERVICE_ID request attribute with jdk http client.
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/AbstractJdkHttpClient.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/ServiceIdSpec.groovy
Labels: type: improvement

#11313 Inner classes with builder don't get introspected
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
  test-suite/src/test/java/io/micronaut/test/lombok/SimpleEntity.java
Labels: type: bug

#11284 deprecate HttpResponse::getStatus
  http-client-core/src/main/java/io/micronaut/http/client/exceptions/HttpClientResponseException.java
  http-client/src/test/groovy/io/micronaut/http/client/docs/httpstatus/HttpStatusSpec.groovy
  http/src/main/java/io/micronaut/http/HttpResponse.java
Labels: type: improvement

#11304 [Fix #10585] Add http-client error log for non-CompletableFuture responses
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  test-suite-logback/build.gradle
  test-suite-logback/src/test/groovy/io/micronaut/logback/LoggerClientExceptionSpec.groovy
  test-suite-logback/src/test/java/io/micronaut/logback/clients/TeapotClient.java
  test-suite-logback/src/test/java/io/micronaut/logback/controllers/TeapotController.java
Labels: type: improvement

#11317 Improvements to `ExecutionFlow`
  core/src/main/java/io/micronaut/core/execution/CompletableFutureExecutionFlowImpl.java
  core/src/main/java/io/micronaut/core/execution/DelayedExecutionFlow.java
  core/src/main/java/io/micronaut/core/execution/DelayedExecutionFlowImpl.java
  core/src/main/java/io/micronaut/core/execution/ExecutionFlow.java
  core/src/main/java/io/micronaut/core/execution/ImperativeExecutionFlowImpl.java
  http/src/main/java/io/micronaut/http/reactive/execution/ReactorExecutionFlowImpl.java
Labels: type: improvement

#11297 Optimizations in reactor <-> ExecutionFlow transformations
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyPublisherBodyBinder.java
  http/src/main/java/io/micronaut/http/filter/MethodFilter.java
  http/src/main/java/io/micronaut/http/reactive/execution/FlowAsMono.java
  http/src/main/java/io/micronaut/http/reactive/execution/ReactiveExecutionFlow.java
  http/src/main/java/io/micronaut/http/reactive/execution/ReactorExecutionFlowImpl.java
  http/src/test/groovy/io/micronaut/http/reactive/execution/ReactorExecutionFlowImplSpec.groovy
Labels: type: improvement

#11330 Support merging with mapper annotation
  context/src/main/java/io/micronaut/runtime/beans/MapperIntroduction.java
  context/src/test/groovy/io/micronaut/runtime/beans/MapperAnnotationSpec.groovy
  context/src/test/groovy/io/micronaut/runtime/beans/MapperMergingAnnotationSpec.groovy
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/MapperVisitor.java
  core/src/test/java/io/micronaut/core/io/service/SoftServiceLoaderTest.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/visitor/MapperVisitorSpec.groovy
  inject/src/main/java/io/micronaut/context/annotation/Mapper.java
  src/main/docs/guide/ioc/beanMappers.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/AdditionalMappers.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/ChristmasMappers.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/ChristmasTypes.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/mappers/MappersSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/AdditionalMappers.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/ChristmasMappers.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/ChristmasTypes.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/mappers/MappersSpec.kt
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/AdditionalMappers.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/ChristmasMappers.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/ChristmasTypes.java
  test-suite/src/test/java/io/micronaut/docs/ioc/mappers/MappersSpec.java
Labels: type: enhancement

#11365 Only subscribe to body once actually requested to
  http-client/src/main/java/io/micronaut/http/client/netty/StreamWriter.java
Labels: type: bug

#11370 Fixed: ConcurrentModificationException in FullNettyClientHttpResponse::getBody
  http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/FullNettyClientHttpResponseSpec.groovy
Labels: type: bug

#11347 fix combination of lombok.Builder with Introspected without builder
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  test-suite/build.gradle
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
  test-suite/src/test/java/io/micronaut/test/lombok/MyEntity.java
Labels: type: bug

#11369 feat: allow endpoint path customization
  management/src/main/java/io/micronaut/management/endpoint/EndpointConfiguration.java
  management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointCustomPathSpec.groovy
Labels: type: improvement

#11379 Fix check for configuration properties
  context/src/main/java/io/micronaut/runtime/beans/MapperIntroduction.java
  core-processor/src/main/java/io/micronaut/inject/configuration/ConfigurationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/processing/DeclaredBeanElementCreator.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/JdkBlockingHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http/src/main/java/io/micronaut/http/bind/binders/RequestAttributeAnnotationBinder.java
  http/src/main/java/io/micronaut/http/body/stream/UpstreamBalancer.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationBuilderSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  router/src/main/java/io/micronaut/web/router/DefaultUriRouteMatch.java
Labels: type: bug
