Repository micronaut-projects/micronaut-core, pull requests merged in 2024-04, with the labels that each got.

#10674 Fix Jakarta Inject TCK dependency
  src/main/docs/guide/ioc/beanImport.adoc
Labels: type: docs

#10685 Set Accept header correctly in declarative client
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client/src/test/groovy/io/micronaut/http/client/ClientIntroductionAdviceSpec.groovy
Labels: type: bug

#10696 Remove gorm from docs and version catalog
  gradle/libs.versions.toml
  inject/src/main/java/io/micronaut/context/env/Environment.java
  src/main/docs/guide/aop/introductionAdvice.adoc
  src/main/docs/guide/cli/createProject.adoc
  src/main/docs/guide/configurations/dataAccess.adoc
  src/main/docs/guide/configurations/dataAccess/hibernateSupport.adoc
  src/main/docs/guide/httpServer/errorHandling/exceptionHandler/builtInExceptionHandlers.adoc
  src/main/docs/guide/languageSupport/groovy.adoc
Labels: type: docs

#10712 Fix NPE when part conversion fails
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyPartUploadAnnotationBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/FileUploadSpec.groovy
Labels: type: bug

#10713 Fix duplicate CompletedFileUpload in publisher if route is delayed
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyPublisherPartUploadBinder.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/FileUploadSpec.groovy
Labels: type: bug

#10705 Implement HTTP/2 server push
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ServerPushSpec.groovy
Labels: type: improvement

#10720 Correct extracting embedded annotations expression
  inject-java/src/test/groovy/io/micronaut/aop/compile/IntroductionCompileSpec.groovy
  inject-java/src/test/groovy/io/micronaut/expressions/EmbeddedExpressionAnnotation.java
  inject-java/src/test/groovy/io/micronaut/expressions/EmbeddedExpressionsSpec.groovy
  inject/src/main/java/io/micronaut/inject/annotation/EvaluatedAnnotationValue.java
Labels: type: bug

#10706 Implement HTTP/2 access logging
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogConnectionEncoder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogFrameListener.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogManager.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java
  test-suite/src/test/groovy/io/micronaut/http/Http2AccessLoggerSpec.groovy
  test-suite/src/test/groovy/io/micronaut/http/HttpAccessLogger.groovy
  test-suite/src/test/groovy/io/micronaut/http2/Http2AccessLoggerSpec.groovy
Labels: type: improvement

#10704 KSP: Fix computation of Kotlin Defaults Mask in Data Classes with 32+ parameters.
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/KotlinBeanIntrospectionSpec.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/TestEntity7.kt
Labels: type: bug

#10724 Add support for json-schema media type.
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
  json-core/src/main/java/io/micronaut/json/codec/JsonMediaTypeCodec.java
Labels: type: improvement

#10723 bug: Writeable responses not being offloaded since 4.0.0
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/body/WriteableOffloadSpec.groovy
Labels: type: bug

#10729 bug: Writeable responses not being offloaded since 4.0.0
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/body/WriteableOffloadSpec.groovy
Labels: type: bug

#10735 Fix #10733
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy
Labels: type: bug

#10736 Fix: create commands
  src/main/docs/guide/languageSupport/groovy.adoc
Labels: type: docs

#10732 Enable Http2ServerHandler by default
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyServerCustomizer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogFrameListener.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/Http2AccessLogManager.java
  src/main/docs/guide/httpServer/serverConfiguration/nettyServerPipeline.adoc
  test-suite/src/test/groovy/io/micronaut/http/HttpAccessLogger.groovy
Labels: type: improvement

#10743 Make BlockHint public
  http-client/src/main/java/io/micronaut/http/client/netty/BlockHint.java
Labels: type: improvement

#10753 Support accessing the injection point qualifier of each-beans
  inject-java/src/test/groovy/io/micronaut/aop/introduction/InterceptorQualifierSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyDataSource.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyDataSourceHelper.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyDataSourceHelper2.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyDataSourceHelper3.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyInterceptedDataSourceFactory.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyInterceptedInterface.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyInterceptedInterfaceWrapper.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyInterceptedIntroducer.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyInterceptedPoint.java
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/inject/InjectionPoint.java
Labels: type: improvement

#10775 Define default value for Cookie Max-Age
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/CookeFactorySpec.groovy
  http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyServerCookieEncoderSpec.groovy
  http/src/main/java/io/micronaut/http/cookie/Cookie.java
  http/src/main/java/io/micronaut/http/cookie/CookieHttpCookieAdapter.java
  http/src/main/resources/META-INF/services/io.micronaut.http.cookie.CookieFactory
  http/src/test/groovy/io/micronaut/http/cookie/DefaultServerCookieEncoderSpec.groovy
  http/src/test/java/io/micronaut/http/cookie/CookieHttpCookieAdapterTest.java
Labels: type: bug

#10780 refactor: use Blocking HTTP Client in HealthEndpointSpec
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
Labels: type: improvement

#10759 The health check endpoint configuration must be more explicit on regards of sensitive
  management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
  src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc
Labels: type: docs

#10761 HTTP/2 prior knowledge support
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/Http2CompressionSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/context/ContextURISpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/H2cSpec.groovy
Labels: type: improvement
