Repository micronaut-projects/micronaut-core, pull requests merged in 2024-02, with the labels that each got.

#10437 KSP: Fix empty arrays in annotations
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/annotations/AnnotateArraySpec.groovy
Labels: type: bug

#10445 Restore thread contexts in reversed order
  core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
  core/src/test/groovy/io/micronaut/core/propagation/PropagatedContextSpec.groovy
Labels: type: bug

#10444 Fix for context propagation bug
  core-reactive/build.gradle
  core-reactive/src/main/java/io/micronaut/core/async/propagation/ReactivePropagation.java
  core-reactive/src/test/groovy/io/micronaut/core/async/propagation/ReactivePropagationSpec.groovy
Labels: type: bug

#10447 Fix overridden methods list
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
Labels: type: bug

#10451 KSP: Exclude companion object from enum constants list
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinEnumElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#10423 [core] Update common files for branch 4.3.x
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build

#10459 doc: link to static resources guide
  src/main/docs/guide/httpServer/staticResources.adoc
Labels: type: docs

#10466 Inline `SameSiteConverter` to fix Graalvm Dev build
  http/src/main/java/io/micronaut/http/HttpTypeConverterRegistrar.java
  http/src/main/java/io/micronaut/http/cookie/SameSiteConverter.java
Labels: relates-to: graal

#10470 remove withJansi
  src/main/docs/guide/logging/logback.adoc
Labels: type: docs

#10469 Fix parameter expressions for executable methods
  core-processor/src/main/java/io/micronaut/inject/writer/EvaluatedExpressionProcessor.java
  inject-java/src/test/groovy/io/micronaut/expressions/ParameterExpressionsSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractExecutableMethodsDefinition.java
Labels: type: bug

#10457 [core] Update common files for branch 4.3.x
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  gradlew.bat
Labels: relates-to: build

#10476 KSP: Fix processing elements with a high priority visitor
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/order/MyVisitor1.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/order/MyVisitor2.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/order/MyVisitor3.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/order/VisitMyAnnotation.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/order/VisitorOrderSpec.groovy
  inject-kotlin/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#10487 KSP: Mark dependencies as aggregated if the visitor is of aggregated type
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinOutputVisitor.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/beans/BeanDefinitionProcessor.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
Labels: type: bug

#10431 doc: change Grails creator copy
  README.md
  src/main/docs/guide/introduction.adoc
Labels: type: docs

#10493 doc: Document how to retrieve RouteMatch
  src/main/docs/guide/httpServer/routing.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/web/router/routematch/RouteMatchTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/web/router/routematch/RouteMatchTest.kt
  test-suite/src/test/java/io/micronaut/docs/web/router/routematch/RouteMatchTest.java
Labels: type: docs

#10497 KSP: Fix duplicate properties when an accessor is overriden
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#10501 Do not override with 404 when returning response inside CompletableFuture
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/BodyTest.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: bug

#10499 [core] Update common files for branch 4.3.x
  .github/workflows/graalvm-dev.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#10519 Correct generating a copy constructor
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
Labels: type: bug

#10490 Don't generate `BeanDefinitionReference` and `BeanIntrospectionReference`
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractAnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core/src/main/java/io/micronaut/core/io/service/ServiceLoaderInitialization.java
  core/src/main/resources/META-INF/native-image/io.micronaut/micronaut-core/native-image.properties
  inject-groovy-test/src/main/groovy/io/micronaut/ast/transform/test/AbstractBeanDefinitionSpec.groovy
  inject-groovy/src/functionalTest/groovy/io/micronaut/context/ApplicationContextConfigurerSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
  inject-java-helper2/build.gradle
  inject-java-helper2/src/main/java/io/micronaut/inject/test/external/ExternalBean.java
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectorSpec.groovy
  inject-java/build.gradle
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/DoNotInitializeBean.java
  inject-java/src/test/groovy/io/micronaut/inject/beans/StaticInitSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/external/ExternalBeanImport.java
  inject-kotlin-test/src/main/groovy/io/micronaut/annotation/processing/test/KotlinCompiler.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/beans/BeanDefinitionProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/BeanIntrospectionSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinitionAndReference.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/RequiresCondition.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospectionAndReference.java
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
  settings.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectorSpec.groovy
Labels: type: improvement

#10523 Fix process EachProperty configurations with abstract class for KSP
  core-processor/src/main/java/io/micronaut/inject/configuration/ConfigurationUtils.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/AbstractConfig.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/AbstractConfigImpl.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ConfigurationPropertiesInheritanceSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/NotAbstractConfig.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/NotAbstractConfigImpl.java
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/configproperties/inheritance/ConfigurationPropertiesInheritanceSpec.groovy
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/inheritance/AbstractConfig.kt
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/inheritance/AbstractConfigImpl.kt
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/inheritance/NotAbstractConfig.kt
  inject-kotlin/src/test/kotlin/io/micronaut/kotlin/processing/beans/configproperties/inheritance/NotAbstractConfigImpl.kt
Labels: type: bug

#10516 Fix special case of NameUtils.underscoreSeparate where the first char is the separator char
  core/src/main/java/io/micronaut/core/naming/NameUtils.java
  core/src/test/groovy/io/micronaut/core/naming/NameUtilsSpec.groovy
Labels: type: bug

#10539 Move empty arrays to static variables
  aop/src/main/java/io/micronaut/aop/chain/DefaultInterceptorRegistry.java
  aop/src/main/java/io/micronaut/aop/chain/MethodInterceptorChain.java
  context/src/main/java/io/micronaut/runtime/Micronaut.java
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/context/visitor/BeanImportVisitor.java
  core-processor/src/main/java/io/micronaut/inject/ast/ParameterElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/beans/BeanParameterElement.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/processing/AbstractBeanElementCreator.java
  core-processor/src/main/java/io/micronaut/inject/visitor/VisitorContext.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractBeanDefinitionBuilder.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationClassValue.java
  core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
  core/src/main/java/io/micronaut/core/cli/CommandLineParser.java
  core/src/main/java/io/micronaut/core/cli/DefaultCommandLine.java
  core/src/main/java/io/micronaut/core/convert/DefaultMutableConversionService.java
  core/src/main/java/io/micronaut/core/io/service/ServiceLoaderInitialization.java
  core/src/main/java/io/micronaut/core/optim/StaticOptimizations.java
  core/src/main/java/io/micronaut/core/util/StringUtils.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  http-client-core/src/main/java/io/micronaut/http/client/HttpVersionSelection.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/SslSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/SslSpec.groovy
  http-validation/src/main/java/io/micronaut/validation/routes/rules/MissingParameterRule.java
  http-validation/src/main/java/io/micronaut/validation/routes/rules/NullableParameterRule.java
  http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
  http/src/main/java/io/micronaut/http/uri/UriTemplate.java
  http/src/main/java/io/micronaut/http/uri/UriTypeMatchTemplate.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AnnotationProcessingOutputVisitor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataHierarchy.java
  inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataSupport.java
  jackson-core/src/main/java/io/micronaut/jackson/core/tree/JsonNodeTraversingParser.java
  management/src/main/java/io/micronaut/management/endpoint/refresh/RefreshEndpoint.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
Labels: type: improvement

#10532 [core] Update common files for branch 4.3.x
  .github/workflows/graalvm-dev.yml
Labels: relates-to: build

#10545 Create synthesized annotations cache lazily
  inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadata.java
  inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
Labels: type: improvement

#10550 Accept inetd-style FDs
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EpollEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueEventLoopGroupFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NettyChannelType.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/NioEventLoopGroupFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  src/main/docs/guide/httpServer/serverConfiguration/listener.adoc
Labels: type: improvement
