Repository micronaut-projects/micronaut-core, pull requests merged in 2025-05, with the labels that each got.

#11798 fix config properties refresh for each property
  context/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshScope.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
  runtime/src/test/groovy/io/micronaut/runtime/context/scope/RefreshScopeSpec.groovy
Labels: type: bug

#11800 Add JFR event for HTTP requests
  core/src/main/java/io/micronaut/core/util/NativeImageUtils.java
  gradle/libs.versions.toml
  http-server-netty/build.gradle.kts
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http1RequestEvent.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2RequestEvent.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/Http2ServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/HttpRequestEvent.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/MultiplexedServerHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/handler/Http1RequestEventTest.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/handler/Http2RequestEventTest.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/handler/HttpRequestEventTest.java
Labels: type: improvement

#11805 Implement jitter in @Retryable to avoid thundering herd
  retry/src/main/java/io/micronaut/retry/RetryState.java
  retry/src/main/java/io/micronaut/retry/annotation/Retryable.java
  retry/src/main/java/io/micronaut/retry/intercept/AnnotationRetryStateBuilder.java
  retry/src/main/java/io/micronaut/retry/intercept/CircuitBreakerRetry.java
  retry/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java
  retry/src/test/groovy/io/micronaut/retry/intercept/CircuitBreakerRetrySpec.groovy
  retry/src/test/groovy/io/micronaut/retry/intercept/SimpleRetryInstanceSpec.groovy
Labels: type: improvement

#11808 Don't clear metadata already cleared by type element visitor
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/ast/annotation/AbstractElementAnnotationMetadataFactory.java
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/test/groovy/io/micronaut/visitors/CollectingVisitor.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/GeneratorTrigger.java
  inject-java/src/test/groovy/io/micronaut/visitors/GeneratorVisitor.groovy
  inject-java/src/test/groovy/io/micronaut/visitors/IntroductionTestGenVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/IntroductionTestVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/PostponedVisitorsSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#11814 KSP: Fix casting exception
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  test-suite-kotlin-ksp/src/test/java/io/micronaut/serde/Serde.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/validation/validator/ByteArraySerde.kt
Labels: type: bug

#11759 Fix NPE on double cancellation in ReactorExecutionFlowImpl
  http/src/main/java/io/micronaut/http/reactive/execution/ReactorExecutionFlowImpl.java
  http/src/test/groovy/io/micronaut/http/reactive/execution/ReactorExecutionFlowImplSpec.groovy
Labels: type: bug

#11813 Fix check for Kotlin default properties
  core-processor/src/main/java/io/micronaut/inject/writer/MethodGenUtils.java
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/validation/validator/ControllerCfg.kt
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/validation/validator/ValidatorSpec.kt
Labels: type: bug

#11821 Prevent a circular call between `$Definition` and `$Exec`
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
Labels: type: bug, relates-to: graal
