Repository micronaut-projects/micronaut-core, pull requests merged in 2025-07, with the labels that each got.

#11918 Backport 4.8.x leak fixes to 4.7.x
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/Http1ResponseHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
Labels: type: bug

#11863 fix: Allow other executor instrumentations than context propagation
  context-propagation/src/main/java/io/micronaut/context/propagation/instrument/execution/ContextPropagatingExecutorService.java
  context-propagation/src/main/java/io/micronaut/context/propagation/instrument/execution/ContextPropagatingScheduledExecutorService.java
  context-propagation/src/main/java/io/micronaut/context/propagation/instrument/execution/ExecutorServiceInstrumenter.java
  context-propagation/src/test/groovy/io/micronaut/context/propagation/instrument/execution/ExecutorServiceInstrumenterSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: improvement

#11937 Add string: and base64: resource loaders
  core/src/main/java/io/micronaut/core/io/ResourceResolver.java
  core/src/main/java/io/micronaut/core/io/value/Base64ResourceLoader.java
  core/src/main/java/io/micronaut/core/io/value/StringResourceLoader.java
  core/src/main/java/io/micronaut/core/io/value/ValueResourceLoader.java
  core/src/test/java/io/micronaut/core/io/value/ValueResourceLoaderTest.java
  http/src/main/java/io/micronaut/http/resource/ResourceLoaderFactory.java
  inject/src/main/java/io/micronaut/context/conditions/MatchesPresenceOfResourcesCondition.java
  src/main/docs/guide/resources.adoc
Labels: type: improvement

#11947 Update snapshot instructions
  src/main/docs/guide/appendix/usingsnapshots.adoc
Labels: type: docs

#11939 Support loading keys and trusts from PEM files
  gradle/libs.versions.toml
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-server-netty/build.gradle.kts
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/ssl/PemSslConfigTest.java
  http/src/main/java/io/micronaut/http/ssl/PemParser.java
  http/src/main/java/io/micronaut/http/ssl/SslBuilder.java
  http/src/main/java/io/micronaut/http/ssl/SslConfiguration.java
  http/src/main/java/io/micronaut/http/util/HttpHeadersUtil.java
  http/src/test/java/io/micronaut/http/ssl/PemParserTest.java
  src/main/docs/guide/httpServer/serverConfiguration/https.adoc
Labels: type: improvement
