Repository micronaut-projects/micronaut-core, pull requests merged in 2025-02, with the labels that each got.

#11560 order const. param to ResourceBundleMessageSource
  context/build.gradle.kts
  context/src/test/java/io/micronaut/runtime/context/CompositeMessageSourceTest.java
  context/src/test/resources/i18n/messages.properties
  context/src/test/resources/i18n/messages_es.properties
  inject/src/main/java/io/micronaut/context/i18n/ResourceBundleMessageSource.java
  test-suite-groovy/src/test/groovy/io/micronaut/docs/i18n/MessageSourceFactory.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/i18n/MessageSourceFactory.kt
  test-suite/src/test/java/io/micronaut/docs/i18n/MessageSourceFactory.java
Labels: type: improvement

#11558 doc: HTTP Client cannot use Form & @JsonProperty
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/forms/FormsJacksonAnnotationsTest.java
  src/main/docs/guide/httpServer/formData.adoc
  test-suite-http-server-tck-jdk/src/test/java/io/micronaut/http/server/tck/netty/tests/JdkHttpServerTestSuite.java
Labels: type: docs

#11559 improvement: List<MessageSource> already ordered
  context/src/main/java/io/micronaut/runtime/context/CompositeMessageSource.java
Labels: type: improvement

#11573 Fix generating annotation metadata for enum constants
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
Labels: type: bug

#11588 Ban blocking continuation on event loop threads
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec6.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec7.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FiltersPropagatedContextSpec8.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterTest.java
  http/src/main/java/io/micronaut/http/filter/MethodFilter.java
Labels: type: improvement

#11589 Permit reentrant use of ReactiveByteBufferByteBody.SharedBuffer
  http/src/main/java/io/micronaut/http/body/ReactiveByteBufferByteBody.java
  http/src/test/java/io/micronaut/http/body/ReactiveByteBufferByteBodyTest.java
Labels: type: improvement

#11591 fix: don’t throw NPE if exception message is null
  http-server-netty/src/test/java/io/micronaut/http/server/exceptions/response/DefaultHtmlErrorResponseBodyProviderTest.java
  http-server/src/main/java/io/micronaut/http/server/exceptions/response/DefaultHtmlErrorResponseBodyProvider.java
Labels: type: bug

#11595 Promote Mapper annotation out of experimental status
  inject/src/main/java/io/micronaut/context/annotation/Mapper.java
Labels: type: improvement

#11581 Fixed conversion string to temporalAmount - Duration or Period
  context/src/main/java/io/micronaut/runtime/converters/time/TimeConverterRegistrar.java
  core/src/main/java/io/micronaut/core/convert/DefaultMutableConversionService.java
  http/src/main/java/io/micronaut/http/cookie/Cookie.java
  runtime/src/test/groovy/io/micronaut/runtime/converters/time/TimeConverterRegistrarSpec.groovy
Labels: type: bug

#11596 Fix duplicate name variable
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationBuilderSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configuration/MyOptions.java
  inject-java/src/test/groovy/io/micronaut/inject/configuration/MySQLClientConfiguration.java
Labels: type: bug

#11587 Environment refresh issues
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
  inject/src/test/resources/custom-bootstrap.yml
Labels: type: bug, status: in progress

#11600 Restore HttpRequestReceivedEvent
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
Labels: type: regression

#11599 [core] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#11609 Fix generating bytecode frames
  core-processor/build.gradle.kts
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/expressions/EvaluatedExpressionWriter.java
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanConfigurationWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/ByteCodeWriterUtils.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalReflectionMetadataWriter.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java
Labels: type: bug

#11605 KSP: Fix collect interface native properties
  aop/src/main/java/io/micronaut/aop/chain/AdapterIntroduction.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/inject/ast/ClassElementSpec.groovy
Labels: type: bug

#11610 Fix disabling eager each-property beans
  inject-java/src/test/groovy/io/micronaut/inject/ctx/DataSourceConfiguration.java
  inject-java/src/test/groovy/io/micronaut/inject/ctx/DatasourceConfigurationSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/ctx/DatasourceFactory.java
  inject-java/src/test/groovy/io/micronaut/inject/ctx/JdbcDataSourceEnabled.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: bug

#11616 KSP2: Fix NPE
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
Labels: type: improvement

#11617 Fix incorrect handling of unresolved class values.
  core/src/main/java/io/micronaut/core/annotation/AnnotationClassValue.java
  test-suite/src/test/java/io/micronaut/test/lombok/Bar.java
  test-suite/src/test/java/io/micronaut/test/lombok/Foo.java
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
Labels: type: bug

#11628 Provide more information when an invalid custom Logback xml file is specified
  context/src/main/java/io/micronaut/logging/impl/LogbackUtils.java
  management/src/main/java/io/micronaut/management/endpoint/loggers/impl/Log4jLoggingSystem.java
  test-suite-logback-external-configuration/src/test/groovy/io/micronaut/logback/ExternalConfigurationSpec.groovy
Labels: type: improvement
