Repository micronaut-projects/micronaut-core, pull requests merged in 2025-06, with the labels that each got.

#11832 Add support records for groovy
  core-processor/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
  inject-groovy/src/test/groovy/io/micronaut/ast/groovy/visitor/GroovyBeanPropertiesSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/ast/groovy/visitor/GroovyRecord.groovy
  inject-groovy/src/test/java/io/micronaut/sample/EmptyRecord.java
  inject-groovy/src/test/java/io/micronaut/sample/JavaRecord.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
Labels: type: improvement

#11809 Introduce `TypeElementQuery` to limit visitations of `TypeElementVisitor`
  core-processor/src/main/java/io/micronaut/context/visitor/BeanImportVisitor.java
  core-processor/src/main/java/io/micronaut/context/visitor/ConfigurationReaderVisitor.java
  core-processor/src/main/java/io/micronaut/context/visitor/ExecutableVisitor.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/MapperVisitor.java
  core-processor/src/main/java/io/micronaut/inject/visitor/DefaultTypeElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/visitor/TypeElementQuery.java
  core-processor/src/main/java/io/micronaut/inject/visitor/TypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/validation/visitor/async/AsyncTypeElementVisitor.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  http-validation/src/main/java/io/micronaut/validation/routes/FilterVisitor.java
  http-validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/TypeElementQuerySpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/visitor/TypeElementQueryVisitor.groovy
  inject-groovy/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
  inject-java/src/test/groovy/io/micronaut/visitors/BuilderVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/WitherVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/query/TypeElementQuerySpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/visitor/TypeElementQuerySpec.groovy
  inject-kotlin/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: enhancement

#11847 Propagate context to ExceptionHandler
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/handler/BlockingController.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/handler/DefaultExceptionHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/handler/MdcFilter.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/handler/NonBlockingController.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/handler/PropagatedContextExceptionHandlerTest.java
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
Labels: type: bug

#11844 Gradle 8.14.2
  buildSrc/src/main/groovy/io.micronaut.build.internal.convention-quality.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#11602 remove duplicated files
  src/main/docs/guide/config/evaluatedExpressions.adoc
  test-suite/src/main/java/io/micronaut/docs/expressions/ContextRegistrar.java
  test-suite/src/main/java/io/micronaut/docs/expressions/CustomEvaluationContext.java
  test-suite/src/test/java/io/micronaut/docs/expressions/ContextRegistrar.java
  test-suite/src/test/java/io/micronaut/docs/expressions/CustomEvaluationContext.java
Labels: type: improvement

#11861 Fix javadoc aggregation
  build.gradle
Labels: type: bug

#11862 Remove managed Kotlin 2 KSP 2 from BOM
  core-bom/build.gradle.kts
  gradle/libs.versions.toml
  test-inject-kotlin2-ksp2/build.gradle.kts
  test-inject-kotlin2-test/build.gradle.kts
  test-suite-kotlin2-ksp2/build.gradle.kts
Labels: type: bug

#11873 reactor 3.7.7
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#11891 Remove regex anchors from CacheControlTest
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/CacheControlTest.java
Labels: type: bug

#11526 doc: document how to Disable hostname verification in ssl config
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-client/src/test/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilderReplacement.java
  src/main/docs/guide/httpClient/httpClientImplementations/nettyHttpClient.adoc
Labels: type: docs

#11898 Fix StreamingFileUpload leak
  http-client/src/main/java/io/micronaut/http/client/netty/Http1ResponseHandler.java
  http-server-netty/build.gradle.kts
  http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/NettyStreamingFileUpload.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/BufferLeakDetectionExtension.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/FormDataDiskSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/BufferLeakDetection.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FlagAppender.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/StaticResourceResolutionSpec2.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/forms/UploadTest.java
  http-tck/build.gradle.kts
  http-tck/src/main/java/io/micronaut/http/tck/netty/LeakDetectionExtension.java
  http-tck/src/main/java/io/micronaut/http/tck/netty/TestLeakDetector.java
  http-tck/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  http/src/main/java/io/micronaut/http/body/stream/PublisherAsBlocking.java
  test-suite-http-server-tck-jdk/src/test/java/io/micronaut/http/server/tck/netty/tests/JdkHttpServerTestSuite.java
  test-suite-http-server-tck-netty/build.gradle.kts
  test-suite-http2-server-tck-netty/build.gradle.kts
Labels: type: bug
