Repository micronaut-projects/micronaut-core, pull requests merged in 2025-09, with the labels that each got.

#12026 Update netty
  gradle/libs.versions.toml
Labels: dependency-upgrade

#12035 Clarify documentation about underscores in properties
  src/main/docs/guide/config/propertySource.adoc
Labels: type: docs

#11935 [core] Update common files for branch 4.10.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#12057 Certificate provider API
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClientBuilder.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java
  http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslFactory.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-netty/build.gradle.kts
  http-netty/src/main/java/io/micronaut/http/netty/NettySslContextBuilder.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyTlsUtils.java
  http-netty/src/main/java/io/micronaut/http/netty/SslContextAutoLoader.java
  http-netty/src/main/java/io/micronaut/http/netty/SslContextHolder.java
  http-server-netty/build.gradle.kts
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultNettyEmbeddedServerFactory.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/DelegateNettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServices.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/NettyServerSslFactory.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/ssl/FileCertificateProviderTest.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/ssl/ResourceCertificateProviderTest.java
  http-server-netty/src/test/java/io/micronaut/http/server/netty/ssl/SelfSignedCertificateProviderTest.java
  http/build.gradle.kts
  http/src/main/java/io/micronaut/http/ssl/AbstractCertificateFileConfig.java
  http/src/main/java/io/micronaut/http/ssl/CertificateProvider.java
  http/src/main/java/io/micronaut/http/ssl/FileCertificateProvider.java
  http/src/main/java/io/micronaut/http/ssl/PemParser.java
  http/src/main/java/io/micronaut/http/ssl/ResourceCertificateProvider.java
  http/src/main/java/io/micronaut/http/ssl/SelfSignedCertificateProvider.java
  http/src/main/java/io/micronaut/http/ssl/SslBuilder.java
  http/src/main/java/io/micronaut/http/ssl/SslConfiguration.java
  src/main/docs/guide/certificates.adoc
  src/main/docs/guide/httpServer/serverConfiguration/https.adoc
Labels: type: enhancement

#12067 Avoid using service loading accessible classes
  core-reactive/src/main/java/io/micronaut/core/async/ReactiveStreamsTypeInformationProvider.java
  core/src/main/java/io/micronaut/core/type/RuntimeTypeInformation.java
  inject/src/main/java/io/micronaut/context/env/DefaultPropertyPlaceholderResolver.java
  inject/src/main/java/io/micronaut/inject/provider/ProviderTypeInformationProvider.java
  inject/src/main/resources/META-INF/services/io.micronaut.context.env.PropertyExpressionResolver
Labels: type: improvement

#12071 Properly adapt streaming body in RawHttpClient
  http-client-tck/src/main/java/io/micronaut/http/client/tck/tests/RawTest.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
Labels: type: bug

#12039 [core] Update common files for branch 4.10.x
  .clineignore
  .clinerules/coding.md
  .clinerules/docs.md
  .github/instructions/coding.instructions.md
  .github/instructions/docs.instructions.md
  .gitignore
Labels: relates-to: build
