Repository micronaut-projects/micronaut-core, pull requests merged in 2025-10, with the labels that each got.

#11985 Add ResponseBodyWriter for ByteBody
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/OctetTest.java
  http-server/src/main/java/io/micronaut/http/server/ResponseLifecycle.java
  http/src/main/java/io/micronaut/http/ServerHttpRequest.java
  http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
  http/src/main/java/io/micronaut/http/body/ByteBodyWriter.java
  http/src/main/java/io/micronaut/http/body/ContextlessMessageBodyHandlerRegistry.java
  http/src/main/java/io/micronaut/http/body/stream/BaseSharedBuffer.java
Labels: type: improvement

#11787 Feature/Support for QueryValue as a object
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/PaginationRequest.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/ParameterBindingSpec.groovy
  http/src/main/java/io/micronaut/http/bind/binders/QueryValueArgumentBinder.java
Labels: type: enhancement

#12078 Fix choosing record constructor
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
Labels: type: bug

#12087 ByteBody: add optional operation tracking
  http-netty/src/main/java/io/micronaut/http/netty/body/AvailableNettyByteBody.java
  http-netty/src/main/java/io/micronaut/http/netty/body/StreamingNettyByteBody.java
  http/src/main/java/io/micronaut/http/body/InternalByteBody.java
  http/src/main/java/io/micronaut/http/body/ReactiveByteBufferByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/AvailableByteArrayBody.java
  http/src/main/java/io/micronaut/http/body/stream/BaseSharedBuffer.java
  http/src/main/java/io/micronaut/http/body/stream/BaseStreamingByteBody.java
  http/src/main/java/io/micronaut/http/body/stream/InputStreamByteBody.java
Labels: type: improvement

#12083 [core] Update common files for branch 4.10.x
  .clinerules/coding.md
  .github/instructions/coding.instructions.md
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#12086 Precalculate replaces at compilation time
  aop/src/main/java/io/micronaut/aop/internal/InterceptorRegistryBean.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultReplacesDefinition.java
  inject/src/main/java/io/micronaut/context/event/ApplicationEventPublisherFactory.java
  inject/src/main/java/io/micronaut/inject/AdvisedBeanType.java
  inject/src/main/java/io/micronaut/inject/BeanDefinition.java
  inject/src/main/java/io/micronaut/inject/ReplacesDefinition.java
  inject/src/main/java/io/micronaut/inject/provider/AbstractProviderDefinition.java
  inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties
Labels: type: improvement

#12107 Collection of enum types not converting with ConfigurationBuilder
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesParseSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationBuilderSpec.groovy
Labels: type: bug
