Repository micronaut-projects/micronaut-core, pull requests merged in 2025-01, with the labels that each got.

#11480 Document HTTP client pooling configuration
  http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
  src/main/docs/guide/httpClient/nettyPooling.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#11481 Prefer constructor over builder if present in introspections
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
  test-suite/build.gradle
  test-suite/src/test/java/io/micronaut/test/lombok/Book.java
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
Labels: type: bug, type: regression

#11491 KSP: Correct usage + docs of `kotlin.allopen.annotations`
  gradle.properties
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinVisitorContext.kt
  settings.gradle
  src/main/docs/guide/languageSupport/kotlin/ksp.adoc
  test-suite-kotlin-ksp-all-open/build.gradle
  test-suite-kotlin-ksp-all-open/gradle.properties
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/AnotherOpenSingleton.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/AroundSpec.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/NotNull.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/NotNullExample.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/NotNullInterceptor.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/NotNullMyInlineInnerExample.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/NotNullResultInnerExample.kt
  test-suite-kotlin-ksp-all-open/src/test/kotlin/io/micronaut/docs/aop/around/OpenSingleton.kt
  test-suite-kotlin-ksp-all-open/src/test/resources/logback.xml
Labels: type: bug, lang: kotlin

#11490 Fix wrapping executable service multiple times
  context-propagation/src/main/java/io/micronaut/context/propagation/instrument/execution/ExecutorServiceInstrumenter.java
  inject/src/test/groovy/io/micronaut/context/PropagatedContext2Spec.groovy
Labels: type: bug

#11486 KSP: Fix repeatable annotation detection
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/annotation/KotlinAnnotationMetadataBuilder.kt
Labels: type: bug, lang: kotlin

#11422 KSP: Fixed method `isEnum()` for KotlinTypeArgumentElement
  core-bom/build.gradle.kts
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/aop/introduction/MyIsEnumInTypeArgumentSpec.groovy
  inject-kotlin/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: lang: kotlin, type: improvement

#11496 Properly discard inbound HttpContent when connection cancels before readComplete
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
Labels: type: bug

#11407 Use sourcegen bytecode generator to generate internal metadata
  benchmarks/src/jmh/java/io/micronaut/http/server/stack/SearchController.java
  core-processor/build.gradle.kts
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  core-processor/src/main/java/io/micronaut/expressions/EvaluatedExpressionWriter.java
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataGenUtils.java
  core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/ast/ReflectClassElement.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/AptClassWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractAnnotationMetadataWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/ArgumentExpUtils.java
  core-processor/src/main/java/io/micronaut/inject/writer/ArrayAwareSignatureWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanConfigurationWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/EvaluatedExpressionProcessor.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/GenUtils.java
  core-processor/src/main/java/io/micronaut/inject/writer/MethodGenUtils.java
  core-processor/src/main/java/io/micronaut/inject/writer/StringSwitchWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalReflectionMetadataWriter.java
  graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
  gradle/libs.versions.toml
  inject-groovy-test/src/main/groovy/io/micronaut/ast/transform/test/AbstractBeanDefinitionSpec.groovy
  inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
  inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
  inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
Labels: type: improvement

#11449 Support Tracing of Dependency Injection
  config/accepted-api-changes.json
  core/src/main/java/io/micronaut/core/annotation/AnnotationUtil.java
  core/src/main/java/io/micronaut/core/type/TypeInformation.java
  core/src/main/java/io/micronaut/core/util/AnsiColour.java
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/ConstructorCircularDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/ConstructorExceptionSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/FactoryCircularDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/FactoryDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/FieldCircularDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/NestedDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/PostConstructExceptionSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/failures/PropertyCircularDependencyFailureSpec.groovy
  inject-groovy/src/test/groovy/io/micronaut/inject/field/FieldInjectionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/aop/adapter/MethodAdapterSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/beans/BeanDefinitionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanfield/FactoryBeanFieldSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/factory/beanmethod/FactoryBeanMethodSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/failures/ctorcirculardependency/ConstructorCircularDependencyFailureSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/failures/ctorexception/ConstructorExceptionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/failures/fieldcirculardependency/FieldCircularDependencyFailureSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/failures/nesteddependency/NestedDependencyFailureSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/failures/postconstruct/PostConstructExceptionSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/field/simpleinjection/FieldInjectionSpec.groovy
  inject-kotlin/src/test/groovy/io/micronaut/kotlin/processing/beans/BeanDefinitionSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/BeanContextConfiguration.java
  inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/BeanResolutionTraceMode.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/context/DefaultFieldConstructorInjectionPoint.java
  inject/src/main/java/io/micronaut/context/DefaultFieldInjectionPoint.java
  inject/src/main/java/io/micronaut/context/env/AbstractPropertySourceLoader.java
  inject/src/main/java/io/micronaut/context/env/CommandLinePropertySource.java
  inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
  inject/src/main/java/io/micronaut/context/env/DefaultOrigin.java
  inject/src/main/java/io/micronaut/context/env/DefaultPropertyEntry.java
  inject/src/main/java/io/micronaut/context/env/Environment.java
  inject/src/main/java/io/micronaut/context/env/EnvironmentPropertySource.java
  inject/src/main/java/io/micronaut/context/env/KubernetesEnvironmentPropertySource.java
  inject/src/main/java/io/micronaut/context/env/PropertyEntry.java
  inject/src/main/java/io/micronaut/context/env/PropertySource.java
  inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
  inject/src/main/java/io/micronaut/context/env/SystemPropertiesPropertySource.java
  inject/src/main/java/io/micronaut/context/exceptions/MessageUtils.java
  inject/src/main/java/io/micronaut/inject/BeanDefinition.java
  inject/src/main/java/io/micronaut/inject/provider/BeanProviderDefinition.java
  inject/src/main/java/io/micronaut/inject/qualifiers/InterceptorBindingQualifier.java
  inject/src/test/groovy/io/micronaut/context/ConfigurationPathSpec.groovy
  jackson-core/src/main/java/io/micronaut/jackson/core/env/CloudFoundryVcapApplicationPropertySourceLoader.java
  jackson-core/src/main/java/io/micronaut/jackson/core/env/CloudFoundryVcapServicesPropertySourceLoader.java
  management/src/test/groovy/io/micronaut/management/endpoint/routes/RoutesEndpointSpec.groovy
  src/main/docs/guide/ioc.adoc
  src/main/docs/guide/ioc/iocDebugging.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#11500 Revert `MediaType` being comparable
  http/src/main/java/io/micronaut/http/MediaType.java
  http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy
Labels: type: bug

#11511 Use correct type for builder in generated introspections
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  test-suite/src/test/java/io/micronaut/test/lombok/BarCommand.java
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
Labels: type: bug

#11520 Fix logged exception when parsing invalid HTTP Host header
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/util/DefaultHttpHostResolver.java
  http-server/src/test/groovy/io/micronaut/http/server/util/DefaultHttpHostResolverSpec.groovy
Labels: type: bug

#11467 [core] Update common files for branch 4.8.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#11528 Fix dangling request when connection is closed without error
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FlagAppender.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
Labels: type: bug

#11529 Do not log ClosedChannelExceptions
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
Labels: type: bug

#11342 Move body writing logic into http-server
  core-reactive/src/main/java/io/micronaut/core/async/subscriber/LazySendingSubscriber.java
  core/src/main/java/io/micronaut/core/util/functional/ThrowingConsumer.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/ByteBodySubscriber.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/JdkRawHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-netty/src/main/java/io/micronaut/http/netty/NettyHttpHeaders.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyBodyAdapter.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyByteBodyFactory.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyCharSequenceBodyWriter.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyJsonHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWritableBodyWriter.java
  http-netty/src/test/groovy/io/micronaut/http/netty/body/DefaultHandlerSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyResponseLifecycle.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/PipeliningServerHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/handler/Http2ServerHandlerSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
  http-server/src/main/java/io/micronaut/http/server/ResponseLifecycle.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  http-server/src/main/java/io/micronaut/http/server/body/AbstractFileBodyWriter.java
  http-server/src/main/java/io/micronaut/http/server/body/FileBodyWriter.java
  http-server/src/main/java/io/micronaut/http/server/body/InputStreamBodyWriter.java
  http-server/src/main/java/io/micronaut/http/server/body/StreamFileBodyWriter.java
  http-server/src/main/java/io/micronaut/http/server/body/SystemFileBodyWriter.java
  http/src/main/java/io/micronaut/http/MutableHttpHeaders.java
  http/src/main/java/io/micronaut/http/body/AbstractBodyAdapter.java
  http/src/main/java/io/micronaut/http/body/ByteBodyFactory.java
  http/src/main/java/io/micronaut/http/body/ByteBufferBodyAdapter.java
  http/src/main/java/io/micronaut/http/body/CharSequenceBodyWriter.java
  http/src/main/java/io/micronaut/http/body/ConcatenatingSubscriber.java
  http/src/main/java/io/micronaut/http/body/ReactiveByteBufferByteBody.java
  http/src/main/java/io/micronaut/http/body/ResponseBodyWriter.java
  http/src/main/java/io/micronaut/http/body/ResponseBodyWriterWrapper.java
  http/src/main/java/io/micronaut/http/body/TextStreamBodyWriter.java
  http/src/main/java/io/micronaut/http/body/stream/BaseSharedBuffer.java
  http/src/main/java/io/micronaut/http/body/stream/BufferConsumer.java
  http/src/main/java/io/micronaut/http/body/stream/InputStreamByteBody.java
  http/src/test/groovy/io/micronaut/http/body/ConcatenatingSubscriberSpec.groovy
  http/src/test/groovy/io/micronaut/http/body/stream/InputStreamByteBodySpec.groovy
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
Labels: type: improvement

#11324 Replace HttpAttributes with accessors
  http-client-core/src/main/java/io/micronaut/http/client/ClientAttributes.java
  http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
  http-client-jdk/src/main/java/io/micronaut/http/client/jdk/AbstractJdkHttpClient.java
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/Http2Spec.groovy
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/OptionsRequestAttributesSpec.groovy
  http-client-jdk/src/test/groovy/io/micronaut/http/client/jdk/ServiceIdSpec.groovy
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/test/groovy/io/micronaut/http/client/ServiceIdSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/Http2Spec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/NettyBodyAnnotationBinder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/OptionsRequestAttributesSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/FilterErrorSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/filters/ServerPreFilterSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/interceptor/HttpFilterSpec.groovy
  http-server-netty/src/test/groovy/io/micronaut/websocket/WebsocketRouteMatchSpec.groovy
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/FilterErrorTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/HttpServerFilterTest.java
  http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/ResponseFilterTest.java
  http-server/src/main/java/io/micronaut/http/server/OptionsFilter.java
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
  http-server/src/main/java/io/micronaut/http/server/ResponseLifecycle.java
  http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java
  http-server/src/main/java/io/micronaut/http/server/binding/RouteInfoArgumentBinder.java
  http-server/src/main/java/io/micronaut/http/server/binding/RouteMatchArgumentBinder.java
  http-server/src/main/java/io/micronaut/http/server/cors/CrossOriginUtil.java
  http/src/main/java/io/micronaut/http/BasicHttpAttributes.java
  http/src/main/java/io/micronaut/http/HttpAttributes.java
  http/src/main/java/io/micronaut/http/HttpRequest.java
  http/src/main/java/io/micronaut/http/bind/binders/PathVariableAnnotationBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/QueryValueArgumentBinder.java
  http/src/main/java/io/micronaut/http/bind/binders/RequestAttributeAnnotationBinder.java
  http/src/main/java/io/micronaut/http/util/OutgoingHttpRequestProcessorImpl.java
  management/src/main/java/io/micronaut/management/endpoint/EndpointsFilter.java
  router/src/main/java/io/micronaut/web/router/DefaultRouter.java
  router/src/main/java/io/micronaut/web/router/RouteAttributes.java
  router/src/main/java/io/micronaut/web/router/RouteMatchUtils.java
  test-suite-groovy/src/test/groovy/io/micronaut/docs/web/router/routematch/RouteMatchTest.groovy
  test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendFilter.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendFilter.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/web/router/routematch/RouteMatchTest.kt
  test-suite-netty-ssl-graalvm/src/test/java/example/micronaut/HelloControllerTest.java
  test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyClientCustomizerSpec.groovy
  test-suite/src/test/groovy/io/micronaut/upload/PrincipalFilter.java
  test-suite/src/test/java/io/micronaut/docs/web/router/routematch/RouteMatchTest.java
Labels: type: improvement

#11537 Fix loading primitive classes + support primitive classes in annotations
  core-processor/src/main/java/io/micronaut/inject/processing/JavaModelUtils.java
  core-processor/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
  inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
  inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
  inject-java/src/test/groovy/io/micronaut/inject/annotation/MyAnnotationX.java
Labels: type: bug

#11523 Refactor and improve bean tracing APIs
  inject/src/main/java/io/micronaut/context/AbstractBeanResolutionContext.java
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/BeanContextConfiguration.java
  inject/src/main/java/io/micronaut/context/BeanResolutionTraceConfiguration.java
  inject/src/main/java/io/micronaut/context/BeanResolutionTraceMode.java
  inject/src/main/java/io/micronaut/context/BeanResolutionTracer.java
  inject/src/main/java/io/micronaut/context/ConsoleBeanResolutionTracer.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
Labels: type: improvement

#11544 Hide log exception on closed channel in http2 upgrade
  http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/fuzzing/FuzzyInputSpec.groovy
Labels: type: bug

#11300 Improve event loop locality of client requests
  http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
  http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
  http-client/src/test/groovy/io/micronaut/http/client/netty/ConnectionManagerSpec.groovy
  http-client/src/test/groovy/io/micronaut/http/client/netty/StickyEventLoopSpec.groovy
Labels: type: improvement

#11503 Added support for alias selection in the keystore
  http-netty/src/main/java/io/micronaut/http/netty/NettyTlsUtils.java
  http-netty/src/test/groovy/io/micronaut/http/netty/NettyTlsUtilsSpec.groovy
  http-netty/src/test/resources/kesytoreGenerateCommands.md
  http-netty/src/test/resources/keystoreWithMultipleAlias.jks
Labels: type: improvement

#11545 docs: add example for streaming data with Content-Disposition
  src/main/docs/guide/httpServer/transfers.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/transfer/DownloadController.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/transfer/DownloadController.kt
  test-suite/src/test/java/io/micronaut/docs/server/transfer/DownloadController.java
Labels: type: docs

#11524 Fix link to ConstraintExceptionHandler
  src/main/docs/guide/httpServer/errorHandling/exceptionHandler/builtInExceptionHandlers.adoc
Labels: type: docs

#11556 doc: split JSON Binding documentation into sections
  src/main/docs/guide/httpServer/formData.adoc
  src/main/docs/guide/httpServer/jsonBinding.adoc
  src/main/docs/guide/httpServer/jsonBinding/bindingUsingCompletableFuture.adoc
  src/main/docs/guide/httpServer/jsonBinding/bindingUsingPOJOs.adoc
  src/main/docs/guide/httpServer/jsonBinding/bindingUsingReactiveFrameworks.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationBeans.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationFeatures.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationFurtherCustomisingJsonFactory.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationNumberPrecision.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationServiceLoader.adoc
  src/main/docs/guide/httpServer/jsonBinding/jacksonConfiguration/jacksonConfigurationSupportForJsonView.adoc
  src/main/docs/guide/httpServer/jsonBinding/jsonMapper.adoc
  src/main/docs/guide/httpServer/jsonBinding/serializationUsingJacksonDatabind.adoc
  src/main/docs/guide/httpServer/jsonBinding/serializeUsingMicronautSerialization.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#11555 doc: add @Consumes FORM_URLENCODED to formData.adoc
  src/main/docs/guide/httpServer/formData.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/form/Person.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/form/PersonController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/server/form/PersonControllerSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/form/Person.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/form/PersonController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/form/PersonControllerTest.kt
  test-suite/src/test/java/io/micronaut/docs/server/form/Person.java
  test-suite/src/test/java/io/micronaut/docs/server/form/PersonController.java
  test-suite/src/test/java/io/micronaut/docs/server/form/PersonControllerTest.java
Labels: type: docs

#11527 add support for programmatically adding bean configurations
  inject-java/src/test/groovy/io/micronaut/inject/configurations/RequiresBeanSpec.groovy
  inject/src/main/java/io/micronaut/context/AbstractBeanConfiguration.java
  inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/BeanDefinitionRegistry.java
  inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
  inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
  inject/src/main/java/io/micronaut/inject/BeanConfiguration.java
  inject/src/main/java/io/micronaut/inject/ConditionalBeanConfiguration.java
Labels: type: enhancement
