Repository micronaut-projects/micronaut-core, pull requests merged in 2025-03, with the labels that each got.

#11646 Fix `findIndexedProperty` logic
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
Labels: type: bug

#11648 fix compiler warning for unrecognised options
  core-processor/src/main/java/io/micronaut/context/visitor/InternalApiTypeElementVisitor.java
Labels: type: bug

#11652 fix introduction advise skipping methods of generated super interfaces
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/IntroductionTest.java
  inject-java/src/test/groovy/io/micronaut/visitors/IntroductionTestGen.java
  inject-java/src/test/groovy/io/micronaut/visitors/IntroductionTestVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/PostponedVisitorsSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#11654 Fix introduction advice on generated types with error checking APIs
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  core-processor/src/main/java/io/micronaut/inject/ast/ClassElement.java
  core-processor/src/main/java/io/micronaut/inject/ast/UnresolvedTypeKind.java
  inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java
  inject-java/src/test/groovy/io/micronaut/visitors/Builder.java
  inject-java/src/test/groovy/io/micronaut/visitors/BuilderVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/PostponedVisitorsSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#11445 Documentation for Custom http status code
  src/main/docs/guide/httpServer/statusAnnotation.adoc
Labels: type: docs

#11679 Add sonar exclusion for MutableHttpRequestWrapper to fix build
  build.gradle
Labels: type: bug, relates-to: build

#11678 Fix early release in TextPlainObjectBodyReader
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  http/src/main/java/io/micronaut/http/body/TextPlainObjectBodyReader.java
Labels: type: bug

#11680 Fix accessing package protected fields from a different package
  core-processor/src/main/java/io/micronaut/inject/ast/MemberElement.java
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/DispatchWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/ExecutableMethodsDefinitionWriter.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/MuxedEvent1.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/outer/MuxedEvent2.java
Labels: type: bug

#11684 On route mismatch, only consider alternate media types if method matches
  http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
  http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
Labels: type: bug

#11681 Small ResponseBodyWriter improvements
  http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyByteBufMessageBodyHandler.java
  http-netty/src/main/java/io/micronaut/http/netty/body/NettyWritableBodyWriter.java
  http-server/src/main/java/io/micronaut/http/server/body/InputStreamBodyWriter.java
  http/src/main/java/io/micronaut/http/body/CharSequenceBodyWriter.java
  http/src/main/java/io/micronaut/http/body/ResponseBodyWriter.java
  http/src/main/java/io/micronaut/http/body/TextPlainObjectBodyWriter.java
  http/src/main/java/io/micronaut/http/body/WritableBodyWriter.java
  json-core/src/main/java/io/micronaut/json/body/JsonMessageHandler.java
Labels: type: improvement

#11685 ThreadLocal bean improvements
  benchmarks/src/jmh/java/io/micronaut/context/scope/ThreadLocalScopeBenchmark.java
  context/src/main/java/io/micronaut/runtime/context/scope/ThreadLocal.java
  context/src/main/java/io/micronaut/runtime/context/scope/ThreadLocalCustomScope.java
  inject/src/main/java/io/micronaut/context/AbstractInitializableBeanDefinition.java
  runtime/src/test/groovy/io/micronaut/runtime/context/scope/ThreadLocalScopeSpec.groovy
Labels: type: improvement

#11666 Add thread-core-ratio config option and change default to 1
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupConfiguration.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupRegistry.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupConfiguration.java
  http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupFactory.java
  http-netty/src/test/groovy/io/micronaut/http/netty/channel/EventLoopGroupSpec.groovy
  http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
  http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
Labels: type: improvement

#11665 Fix warning when sending already-available streaming body
  http-client/src/main/java/io/micronaut/http/client/netty/StreamWriter.java
  http-client/src/test/groovy/io/micronaut/http/client/RawHttpClientSpec.groovy
  http/src/main/java/io/micronaut/http/body/stream/LazyUpstream.java
Labels: type: bug

#11687 Fix package-private constructor calls for imported introspections
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/MethodGenUtils.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/PackagePrivateConstructor.java
Labels: type: bug

#11691 Fix infinite recursion in reflective constructor call
  core-processor/src/main/java/io/micronaut/inject/writer/MethodGenUtils.java
  core/src/main/java/io/micronaut/core/reflect/InstantiationUtils.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/outer/Test.java
Labels: type: bug

#11693 Fix compatibility with the Espresso JVM.
  management/src/main/java/io/micronaut/management/health/indicator/threads/DeadlockedThreadsHealthIndicator.java
Labels: type: improvement

#11694 Bean definition executable methods skipped if implementing a generated interface
  core-processor/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
  inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
  inject-java/src/test/groovy/io/micronaut/visitors/InterfaceGen.java
  inject-java/src/test/groovy/io/micronaut/visitors/InterfaceGenVisitor.java
  inject-java/src/test/groovy/io/micronaut/visitors/PostponedVisitorsSpec.groovy
  inject-java/src/test/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
Labels: type: bug

#11695 Backport reflective constructor call to 4.7.x
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
  core-processor/src/main/java/io/micronaut/inject/writer/WriterUtils.java
  core/src/main/java/io/micronaut/core/reflect/InstantiationUtils.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/PackagePrivateConstructor.java
  inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/outer/Test.java
Labels: type: bug

#11686 Fix Lombok builder with private access
  core-processor/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
  test-suite/src/test/java/io/micronaut/test/lombok/LombokIntrospectedBuilderTest.java
  test-suite/src/test/java/io/micronaut/test/lombok/RobotRecordWithPackageAccessBuilder.java
  test-suite/src/test/java/io/micronaut/test/lombok/RobotRecordWithPrivateAccessBuilder.java
  test-suite/src/test/java/io/micronaut/test/lombok/RobotRecordWithProtectedAccessBuilder.java
Labels: type: bug

#11696 KSP: Avoid initializing annotation metadata
  inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
Labels: type: improvement

#11697 test: Native Test for a Kotlin DataClasss serialised with JacksonDatabind
  gradle.properties
  gradle/libs.versions.toml
  test-suite-kotlin-graalvm/build.gradle
  test-suite-kotlin-graalvm/src/test/kotlin/example/micronaut/jacksondatabind/DataClassSerializationTest.kt
  test-suite-kotlin-graalvm/src/test/kotlin/example/micronaut/jacksondatabind/Greeting.kt
  test-suite-kotlin-graalvm/src/test/kotlin/example/micronaut/jacksondatabind/GreetingService.kt
  test-suite-kotlin-graalvm/src/test/kotlin/example/micronaut/jacksondatabind/HolaController.kt
Labels: lang: kotlin, relates-to: graal

#11702 AOP: Fix delegated method invocation
  core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepo6.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepo6Service.java
  inject-java/src/test/groovy/io/micronaut/aop/introduction/MyRepoIntroductionSpec.groovy
Labels: type: bug
